export function createConsumerLocationJourneyService({locations,checkins,locationEvidence,locationQuality,engagement,analytics,offline,routing,live}={}){
  if(!locations||!checkins)throw new Error('Location journey requires locations and check-in services.');
  const emit=(type,detail)=>{if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent(`kleenest:journey-${type}`,{detail}))};
  const canonical=async locationId=>{if(!locationId)throw new Error('Canonical location is required.');const place=await locations.getById(locationId);if(!place)throw new Error('Location could not be resolved.');return{locationId:String(place.location_id??place.id),place};};
  const outcome=async(type,locationId,payload={})=>{try{await analytics?.record(type,{featureCode:`location_journey_${type}`,subjectType:'location',subjectId:locationId,locationId,metadata:payload})}catch{}emit(type,{locationId,payload});return{locationId,payload};};
  const routeOutcome=async(type,locationId,route,payload={})=>{const result=await outcome(type,locationId,{routeId:route?.routeId??route?.id??null,...payload});try{await live?.publish?.({type:`user.route.${type}`,locationId,payload:{routeId:route?.routeId??route?.id??null,route,...payload}})}catch{}return result;};
  return Object.freeze({
    resolve:canonical,
    async view(locationId,metadata={}){const{locationId:id,place}=await canonical(locationId);try{await locations.recordView(id,metadata)}catch{}await outcome('viewed',id,metadata);return place;},
    async directions(locationId,metadata={}){const{locationId:id,place}=await canonical(locationId);try{await analytics?.directionsRequested(id,metadata)}catch{}await outcome('directions-requested',id,metadata);return{locationId:id,place};},
    async route(locationId,routeInput={}){const{locationId:id,place}=await canonical(locationId);if(!routing?.request)throw new Error('Routing service is unavailable.');const result=await routing.request({locationId:id,...routeInput});await routeOutcome('route-generated',id,result);return{place,result};},
    async routeStarted(locationId,route){const{locationId:id}=await canonical(locationId);if(!routing?.start)throw new Error('Routing lifecycle service is unavailable.');const result=await routing.start({locationId:id,route});await routeOutcome('route-started',id,route,{result});return result;},
    async routeApproaching(locationId,route,metadata={}){const{locationId:id}=await canonical(locationId);if(!routing?.approaching)throw new Error('Routing approaching lifecycle is unavailable.');const result=await routing.approaching({locationId:id,route});await routeOutcome('route-approaching',id,route,{result,...metadata});return result;},
    async routeArrived(locationId,route,metadata={}){const{locationId:id}=await canonical(locationId);if(!routing?.arrived)throw new Error('Routing arrival lifecycle is unavailable.');const result=await routing.arrived({locationId:id,route});await routeOutcome('route-arrived',id,route,{result,...metadata});return result;},
    async routeStopArrived({routeId,routeStopId,checkInId,locationId=null}={}){if(!routeId||!routeStopId||!checkInId)throw new Error('Route, route stop, and qualifying check-in are required.');const result=await routing?.arriveStop?.({routeId,routeStopId,checkInId});if(!result)throw new Error('Authoritative route-stop arrival is unavailable.');if(locationId)await outcome('route-stop-arrived',String(locationId),{routeId,routeStopId,checkInId,result});return result;},
    async routeDeparted(locationId,route,metadata={}){const{locationId:id}=await canonical(locationId);if(!routing?.departed)throw new Error('Routing departure lifecycle is unavailable.');const result=await routing.departed({locationId:id,route});await routeOutcome('route-departed',id,route,{result,...metadata});return result;},
    async routeCompleted(routeId,metadata={}){if(!routing?.complete)throw new Error('Routing completion service is unavailable.');const result=await routing.complete(routeId);await outcome('route-completed',String(routeId),{result,...metadata});try{await live?.publish?.({type:'user.route.completed',locationId:null,payload:{routeId,result,...metadata}})}catch{}return result;},
    async arrival(locationId,metadata={}){const{locationId:id,place}=await canonical(locationId);try{await analytics?.arrival(id,metadata);await live?.publish?.({type:'user.arrival',locationId:id,payload:metadata})}catch{}await outcome('arrived',id,metadata);return{locationId:id,place};},
    async departure(locationId,metadata={}){const{locationId:id,place}=await canonical(locationId);try{await analytics?.departure(id,metadata);await live?.publish?.({type:'user.departure',locationId:id,payload:metadata})}catch{}await outcome('departed',id,metadata);return{locationId:id,place};},
    async checkIn({locationId,method='map',latitude=null,longitude=null,placeId=null,qrToken=null}={}){const id=String(locationId??placeId??'');if(!id)throw new Error('Canonical location is required for check-in.');let result;if(method==='qr')result=await checkins.byQr({placeId:id,qrToken});else if(method==='gps')result=await checkins.byGps({locationId:id,latitude,longitude});else result=await checkins.fromMap({locationId:id,latitude,longitude});const checkInId=result?.id??result?.check_in_id??result?.checkin_id??null;try{await analytics?.checkIn(id,{checkInId,qrCodeId:method==='qr'?qrToken:null,pointsAwarded:Number(result?.points_awarded||0)})}catch{}await outcome('checked-in',id,{method,checkInId});return result;},
    async evidence(locationId,kind,payload={}){const{locationId:id}=await canonical(locationId);const operation={restroom:'restroomObservation',amenity:'amenityObservation',quality:'qualityObservation',bathroom:'trustedBathroomVerification',verification:'verification'}[kind||'restroom'];if(!locationEvidence?.[operation])throw new Error(`Location evidence operation unavailable: ${kind||'restroom'}`);const result=await locationEvidence[operation]({...payload,locationId:id});await outcome('evidence-submitted',id,{kind,result});return result;},
    async quality(locationId){const{locationId:id}=await canonical(locationId);if(!locationQuality)throw new Error('Location quality service is unavailable.');return locationQuality.get?.(id)??locationQuality.snapshot?.(id);},
    async engagement(type,referenceId,payload={}){if(!engagement?.[type])throw new Error(`Engagement operation unavailable: ${type}`);const result=await engagement[type](referenceId,payload);await outcome(type,String(payload.locationId??referenceId),{result});return result;},
    async queueOffline({packId,eventType,payload,clientEventId}={}){if(!offline?.queue)throw new Error('Offline service is unavailable.');if(!payload?.locationId&&!payload?.placeId)throw new Error('Offline journey events require canonical locationId.');return offline.queue({packId,eventType,payload,clientEventId});},
    async syncOffline(){if(!offline?.sync)throw new Error('Offline service is unavailable.');const result=await offline.sync();emit('offline-synced',result);return result;}
  });
}
