export function createLocationQualityService(client, { analytics = null, progression = null } = {}){
  if(!client) throw new Error('Supabase client is required.');
  const rpc=(name,args={})=>client.rpc(name,args).then(({data,error})=>{if(error)throw error;return data;});
  const emit=(type,detail)=>{if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent(`kleenest:${type}`,{detail}))};
  const requireLocation=locationId=>{if(!locationId)throw new Error('Canonical location is required.');return locationId};
  const activity=async(type,locationId,metadata={})=>{if(analytics?.record)await analytics.record(type,{featureCode:`location_${type}`,subjectType:'location',subjectId:locationId,locationId,metadata}).catch(()=>null);emit('location-activity',{type,locationId,metadata})};
  return Object.freeze({
    submit:async(locationId,input={})=>{const id=requireLocation(locationId);const result=await rpc('submit_location_quality_observation',{p_location_id:id,p_stars:Number(input.stars),p_cleanliness:Number(input.cleanliness),p_accessibility:input.accessibility,p_safety:input.safety,p_availability:input.availability,p_condition:input.condition,p_feedback:input.feedback??null,p_check_in_id:input.checkInId??null,p_photo_id:input.photoId??null,p_metadata:{...(input.metadata||{}),canonical_location_id:id}});await activity('quality_observation_submitted',id,{check_in_id:input.checkInId??null,stars:Number(input.stars),photo_id:input.photoId??null});emit('location-evidence-updated',{locationId:id,result});return result},
    verifyCheckIn:async(qrCode,lat,lng)=>{const result=await rpc('verify_checkin',{p_qr_code:qrCode,p_lat:lat,p_lng:lng});const row=Array.isArray(result)?result[0]:result;const locationId=row?.location_id||row?.locationId||null;if(locationId)await activity('qr_checkin_verified',locationId,{check_in_id:row?.check_in_id||row?.id||null});return result},
    gpsCheckIn:async(locationId,lat,lng)=>{const id=requireLocation(locationId);const result=await rpc('kleenest_map_check_in',{p_location_id:id,p_lat:lat,p_lng:lng});const row=Array.isArray(result)?result[0]:result;if(id)await activity('gps_checkin_recorded',id,{check_in_id:row?.check_in_id||row?.id||null});return result},
    checkInRewards:checkInId=>rpc('checkin_rewards_summary',{p_checkin_id:checkInId}),
    bathroomSignal:async(locationId,hasPublicBathroom,metadata={})=>{const id=requireLocation(locationId);if(typeof hasPublicBathroom!=='boolean')throw new Error('Bathroom signal must be boolean.');const result=await rpc('record_bathroom_verification',{p_location_id:id,p_has_public_bathroom:hasPublicBathroom,p_lat:metadata.latitude??null,p_lng:metadata.longitude??null,p_distance_meters:metadata.distanceMeters??null});await activity('bathroom_signal_submitted',id,{has_public_bathroom:hasPublicBathroom});emit('bathroom-signal-recorded',{locationId:id,hasPublicBathroom,result});return result},
    amenityObservation:async(locationId,amenityId,present,checkInId=null)=>{const id=requireLocation(locationId);if(!amenityId)throw new Error('Amenity is required.');if(typeof present!=='boolean')throw new Error('Amenity observation must be boolean.');const result=await rpc('submit_amenity_observation',{p_location_id:id,p_amenity_id:amenityId,p_status:present?'present':'absent',p_confidence:1,p_verification_method:'user',p_check_in_id:checkInId,p_photo_id:null,p_notes:null,p_metadata:{canonical_location_id:id}});await activity('amenity_observation_submitted',id,{amenity_id:amenityId,present,check_in_id:checkInId});emit('location-evidence-updated',{locationId:id,amenityId,present,result});return result},
  });
}
