export function createConsumerLocationJourneyService({locations,checkins,locationEvidence,locationQuality,engagement,analytics,offline,routing,live}={}){
  if(!locations||!checkins)throw new Error('Location journey requires locations and check-in services.');
  const emit=(type,detail)=>{if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent(`kleenest:journey-${type}`,{detail}))};
  const canonical=async locationId=>{if(!locationId)throw new Error('Canonical location is required.');const place=await locations.getById(locationId);if(!place)throw new Error('Location could not be resolved.');return{locationId:String(place.location_id??place.id),place};};
  const outcome=async(type,locationId,payload={})=>{try{await analytics?.record(type,{featureCode:`location_journey_${type}`,subjectType:'location',subjectId:locationId,locationId,metadata:payload})}catch{}emit(type,{locationId,payload});return{locationId,payload};};
  return Object.freeze({
    resolve:canonical,
    async view(locationId,metadata={}){const{locationId:id,place}=await canonical(locationId);try{await locations.recordView(id,metadata)}catch{}await outcome('viewed',id,metadata);return place;},
    async directions(locationId,metadata={}){const{locationId:id,place}=await canonical(locationId);try{await analytics?.directionsRequested(id,metadata)}catch{}await outcome('directions-requested',id,metadata);return{locationId:id,place};},
    async arrival(locationId,metadata={}){const{locationId:id,place}=await canonical(locationId);try{await analytics?.arrival(id,metadata);await live?.publish?.({type:'user.arrival',locationId:id,payload:metadata})}catch{}await outcome('arrived',id,metadata);return{locationId:id,place};},
    async departure(locationId,metadata={}){const{locationId:id,place}=await canonical(locationId);try{await analytics?.departure(id,metadata);await live?.publish?.({type:'user.departure',locationId:id,payload:metadata})}catch{}await outcome('departed',id,metadata);return{locationId:id,place};},
    async checkIn({locationId,method='map',latitude=null,longitude=null,placeId=null,qrToken=null}={}){const id=String(locationId??placeId??'');if(!id)throw new Error('Canonical location is required for check-in.');let result;if(method==='qr')result=await checkins.byQr({placeId:id,qrToken});else if(method==='gps')result=await checkins.byGps({locationId:id,latitude,longitude});else result=await checkins.fromMap({locationId:id,latitude,longitude});const checkInId=result?.id??result?.check_in_id??result?.checkin_id??null;try{await analytics?.checkIn(id,{checkInId,qrCodeId:method==='qr'?qrToken:null,pointsAwarded:Number(result?.points_awarded||0)})}catch{}await outcome('checked-in',id,{method,checkInId});return result;},
    async evidence(locationId,payload={}){const{locationId:id}=await canonical(locationId);if(!locationEvidence?.submit)throw new Error('Location evidence service is unavailable.');const result=await locationEvidence.submit(id,payload);await outcome('evidence-submitted',id,{result});return result;},
    async quality(locationId){const{locationId:id}=await canonical(locationId);if(!locationQuality?.get)throw new Error('Location quality service is unavailable.');return locationQuality.get(id);},
    async engagement(type,referenceId,payload={}){if(!engagement?.[type])throw new Error(`Engagement operation unavailable: ${type}`);const result=await engagement[type](referenceId,payload);await outcome(type,String(payload.locationId??referenceId),{result});return result;},
    async queueOffline({packId,eventType,payload,clientEventId}={}){if(!offline?.queue)throw new Error('Offline service is unavailable.');if(!payload?.locationId&&!payload?.placeId)throw new Error('Offline journey events require canonical locationId.');return offline.queue({packId,eventType,payload,clientEventId});},
    async syncOffline(){if(!offline?.sync)throw new Error('Offline service is unavailable.');const result=await offline.sync();emit('offline-synced',result);return result;},
    async route(locationId,routeInput={}){const{locationId:id,place}=await canonical(locationId);if(!routing)throw new Error('Routing service is unavailable.');const result=await routing.routeTo?.({locationId:id,...routeInput});await outcome('route-generated',id,{result});return{place,result};}
  });
}
