import { normalizePlace } from '../locations/place.js';
import { buildDiscoveryRequest } from './networkDiscoveryPolicy.js';

export const MAP_CATEGORIES = Object.freeze([
  { id: 'all', label: 'All' }, { id: 'restroom', label: 'Bathrooms' }, { id: 'restaurant', label: 'Restaurants' },
  { id: 'cafe', label: 'Cafes' }, { id: 'gas_station', label: 'Gas' }, { id: 'shopping', label: 'Shopping' },
  { id: 'park', label: 'Parks' }, { id: 'service', label: 'Services' }, { id: 'health', label: 'Health' },
  { id: 'public_safety', label: 'Public safety' }, { id: 'cooling_center', label: 'Cooling centers' },
  { id: 'government', label: 'Government & public' }, { id: 'brand', label: 'Brands' }
]);
const RPC_CATEGORIES = new Set(['restroom','restaurant','cafe','gas_station','shopping','park','health','public_safety','cooling_center','government','brand','service']);
function sourceMetadata(row){const metadata=row?.source_metadata&&typeof row.source_metadata==='object'?row.source_metadata:{};const tags=row?.osm_tags&&typeof row.osm_tags==='object'?row.osm_tags:{};const brand=row?.brand??metadata.brand??metadata.brand_name??tags.brand??tags['brand:name']??null;const operator=row?.operator_name??metadata.operator??metadata.operator_name??tags.operator??null;return{metadata,tags,brand,operator};}
function canonicalCategory(row,source){const raw=String(row?.category??row?.place_type??'service').toLowerCase();const tags=source.tags||{};const name=String(row?.name??'').toLowerCase();const bathroom=row?.bathroom_verification_status==='has_bathroom'||row?.bathroom_verification_status==='verified'||['restroom','bathroom','toilet'].includes(raw)||['toilets','restroom','bathroom'].includes(String(tags.amenity||'').toLowerCase())||['yes','public','customers'].includes(String(tags.toilets||'').toLowerCase())||['yes','public','customers'].includes(String(tags.restroom||'').toLowerCase())||['yes','public','customers'].includes(String(tags.bathroom||'').toLowerCase());if(bathroom)return'restroom';if(source.brand&&raw==='service')return'brand';if(raw.includes('restaurant')||raw.includes('fast_food')||raw==='food')return'restaurant';if(raw.includes('cafe')||raw.includes('coffee'))return'cafe';if(raw.includes('gas')||raw.includes('fuel'))return'gas_station';if(raw.includes('shop')||raw.includes('retail')||raw.includes('supermarket')||raw.includes('mall'))return'shopping';if(raw.includes('park')||raw.includes('recreation'))return'park';if(raw.includes('hospital')||raw.includes('clinic')||raw.includes('health')||raw.includes('medical')||raw.includes('pharmacy'))return'health';if(raw.includes('police')||raw.includes('fire')||raw.includes('emergency')||raw.includes('public_safety')||raw.includes('public safety'))return'public_safety';if(raw.includes('cooling')||raw.includes('heat relief')||raw.includes('warming'))return'cooling_center';if(raw.includes('government')||raw.includes('library')||raw.includes('library_dropoff')||['city hall','town hall','county office','courthouse','court house','municipal','post office','dmv','department of motor vehicles'].some(term=>name.includes(term)))return'government';return raw;}
function normalize(row){const source=sourceMetadata(row);const brand=source.brand;const category=canonicalCategory(row,source);return normalizePlace({...row,id:row.id??row.location_id,location_id:row.location_id??row.id,category,distance_km:row.distance_km??(row.distance_meters==null?undefined:row.distance_meters/1000),distance_miles:row.distance_miles??(row.distance_meters==null?undefined:row.distance_meters/1609.344),amenities:row.amenities??source.metadata.amenities??[],fixtures:row.fixtures??source.metadata.fixtures??{},brand,operator_name:source.operator,osm_tags:row.osm_tags??source.metadata.osm_tags??{},source_dataset:row.source_dataset??source.metadata.source_dataset??null,source_external_id:row.source_external_id??source.metadata.source_external_id??null,is_verified:row.is_verified??row.verification_status==='verified'});}
function normalizePrepared(row){return normalize({...row,distance_meters:row.distance_meters==null?undefined:Number(row.distance_meters)});}
function distanceMeters(lat1,lng1,lat2,lng2){const r=v=>v*Math.PI/180,a1=r(lat1),a2=r(lat2),dLat=r(lat2-lat1),dLng=r(lng2-lng1),a=Math.sin(dLat/2)**2+Math.cos(a1)*Math.cos(a2)*Math.sin(dLng/2)**2;return 6371008.8*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
function categoryMatches(r,c){const type=String(r.place_type??r.category??'').toLowerCase();const normalized=String(r.category??'').toLowerCase();const metadata=sourceMetadata(r);const tags=metadata.tags||{};const name=String(r.name??'').toLowerCase();const bathroom=r.bathroom_verification_status==='has_bathroom'||r.bathroom_verification_status==='verified'||['restroom','bathroom','toilet'].includes(type)||['restroom','bathroom','toilet'].includes(normalized)||['toilets','restroom','bathroom'].includes(String(tags.amenity||'').toLowerCase())||['yes','public','customers'].includes(String(tags.toilets||'').toLowerCase())||['yes','public','customers'].includes(String(tags.restroom||'').toLowerCase())||['yes','public','customers'].includes(String(tags.bathroom||'').toLowerCase());const brand=Boolean(r.brand||metadata.brand);const governmentName=['city hall','town hall','county office','courthouse','court house','municipal','public library','library district','post office','dmv','department of motor vehicles'].some(term=>name.includes(term));if(!c)return true;if(type===c||normalized===c)return true;if(c==='restroom')return bathroom;if(c==='government')return type.includes('government')||type.includes('library')||type==='library_dropoff'||normalized==='government'||governmentName||['true','yes'].includes(String(metadata.metadata.government??'').toLowerCase())||['true','yes'].includes(String(metadata.metadata.is_government??'').toLowerCase());if(c==='brand')return brand||normalized==='brand';if(c==='restaurant')return type.includes('restaurant')||type.includes('food')||type.includes('fast_food')||normalized==='restaurant';if(c==='cafe')return type.includes('cafe')||type.includes('coffee')||normalized==='cafe';if(c==='gas_station')return type.includes('gas')||type.includes('fuel')||normalized==='gas_station';if(c==='shopping')return type.includes('shop')||type.includes('retail')||type.includes('supermarket')||type.includes('mall')||normalized==='shopping';if(c==='park')return type.includes('park')||type.includes('recreation')||normalized==='park';if(c==='health')return type.includes('hospital')||type.includes('clinic')||type.includes('health')||type.includes('medical')||type.includes('pharmacy')||normalized==='health';if(c==='public_safety')return type.includes('police')||type.includes('fire')||type.includes('emergency')||type.includes('public_safety')||type.includes('public safety')||normalized==='public_safety';if(c==='cooling_center')return type.includes('cooling')||type.includes('heat relief')||type.includes('warming')||normalized==='cooling_center';return false;}
function amenityNamesFrom(amenities){return Object.entries(amenities&&typeof amenities==='object'?amenities:{}).filter(([,enabled])=>Boolean(enabled)).map(([name])=>String(name));}
function amenityMatches(row,amenityNames){if(!amenityNames.length)return true;const source=sourceMetadata(row);const values=[];const collect=value=>{if(Array.isArray(value))values.push(...value);else if(value&&typeof value==='object')Object.entries(value).forEach(([k,v])=>{if(v===true||v==='true'||v==='yes'||v==='public'||v==='customers'||v==='accessible')values.push(k);if(typeof v==='string')values.push(`${k}:${v}`);});else if(value!=null)values.push(String(value));};collect(row?.amenities);collect(row?.fixtures);collect(source.metadata?.amenities);collect(source.metadata?.fixtures);collect(source.tags);const haystack=values.map(v=>String(v).toLowerCase().replace(/[_-]+/g,' '));return amenityNames.every(name=>{const needle=String(name).toLowerCase().replace(/[_-]+/g,' ');return haystack.some(value=>value===needle||value.includes(needle)||needle.includes(value));});}
function identityText(value){return String(value??'').trim().toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}