import { normalizePlace } from '../locations/place.js';

export const MAP_CATEGORIES = Object.freeze([
  { id: 'all', label: 'All' }, { id: 'restroom', label: 'Bathrooms' }, { id: 'restaurant', label: 'Restaurants' },
  { id: 'cafe', label: 'Cafes' }, { id: 'gas_station', label: 'Gas' }, { id: 'shopping', label: 'Shopping' },
  { id: 'park', label: 'Parks' }, { id: 'service', label: 'Services' }, { id: 'health', label: 'Health' },
  { id: 'public_safety', label: 'Public safety' }, { id: 'cooling_center', label: 'Cooling centers' },
  { id: 'government', label: 'Government & public' }, { id: 'brand', label: 'Brands' }
]);
function sourceMetadata(row){const metadata=row?.source_metadata&&typeof row.source_metadata==='object'?row.source_metadata:{};const tags=row?.osm_tags&&typeof row.osm_tags==='object'?row.osm_tags:{};const brand=row?.brand??metadata.brand??metadata.brand_name??tags.brand??tags['brand:name']??null;const operator=row?.operator_name??metadata.operator??metadata.operator_name??tags.operator??null;return{metadata,tags,brand,operator};}
function normalize(row){const source=sourceMetadata(row);const brand=source.brand;const rawCategory=String(row?.category??row?.place_type??'service').toLowerCase();const category=brand&&rawCategory==='service'?'brand':rawCategory;return normalizePlace({...row,id:row.id??row.location_id,location_id:row.location_id??row.id,category,distance_km:row.distance_km??(row.distance_meters==null?undefined:row.distance_meters/1000),distance_miles:row.distance_miles??(row.distance_meters==null?undefined:row.distance_meters/1609.344),amenities:row.amenities??source.metadata.amenities??[],fixtures:row.fixtures??source.metadata.fixtures??{},brand,operator_name:source.operator,osm_tags:row.osm_tags??source.metadata.osm_tags??{},source_dataset:row.source_dataset??source.metadata.source_dataset??null,source_external_id:row.source_external_id??source.metadata.source_external_id??null,is_verified:row.is_verified??row.verification_status==='verified'});}
function normalizePrepared(row){return normalize({...row,distance_meters:row.distance_meters==null?undefined:Number(row.distance_meters)});}
function distanceMeters(lat1,lng1,lat2,lng2){const r=v=>v*Math.PI/180,a1=r(lat1),a2=r(lat2),dLat=r(lat2-lat1),dLng=r(lng2-lng1),a=Math.sin(dLat/2)**2+Math.cos(a1)*Math.cos(a2)*Math.sin(dLng/2)**2;return 6371008.8*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
function categoryMatches(r,c){const type=String(r.place_type??r.category??'').toLowerCase();const brand=Boolean(r.brand||sourceMetadata(r).brand);if(!c)return true;if(type===c)return true;if(c==='restroom')return r.has_bathroom===true||r.has_restroom===true||r.bathroom_verification_status==='has_bathroom';if(c==='government')return r.is_government===true||type.includes('government');if(c==='brand')return brand;if(c==='restaurant')return type.includes('restaurant')||type.includes('food')||type.includes('fast_food');if(c==='cafe')return type.includes('cafe')||type.includes('coffee');if(c==='gas_station')return type.includes('gas')||type.includes('fuel');if(c==='shopping')return type.includes('shop')||type.includes('retail')||type.includes('supermarket')||type.includes('mall');return false;}
async function directSupabaseNearby(client,{latitude,longitude,radiusKm,limit,category,search}){const radiusM=Math.round(Math.min(Math.max(Number(radiusKm)||8,1),100)*1000),latDelta=radiusM/111320,lngDelta=radiusM/(111320*Math.max(Math.cos(latitude*Math.PI/180),.2));const{data,error}=await client.from('locations').select('*').eq('is_active',true).gte('latitude',latitude-latDelta).lte('latitude',latitude+latDelta).gte('longitude',longitude-lngDelta).lte('longitude',longitude+lngDelta).limit(2000);if(error)throw error;const c=category==='all'?null:String(category).toLowerCase(),q=String(search||'').trim().toLowerCase();return(data??[]).filter(r=>Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude))).map(r=>({...r,...(()=>{const s=sourceMetadata(r);return{brand:s.brand,operator_name:s.operator}})(),distance_meters:distanceMeters(latitude,longitude,Number(r.latitude),Number(r.longitude))})).filter(r=>r.distance_meters<=radiusM).filter(r=>categoryMatches(r,c)).filter(r=>!q||[r.name,r.brand,r.operator_name,r.address,r.city,r.state,r.place_type,r.category,r.description,r.owner_name].filter(Boolean).join(' ').toLowerCase().includes(q)).sort((a,b)=>a.distance_meters-b.distance_meters).slice(0,Math.min(Math.max(Number(limit)||500,1),500)).map(normalize);}
export function createMapNetworkService(client){if(!client)throw new Error('Supabase client is required.');
 async function discoverNearby({latitude,longitude,radiusKm=8}={}){if(latitude==null||longitude==null)return null;const radius=Math.min(Math.max(Number(radiusKm)||8,1),50);const{data,error}=await client.functions.invoke('ingest-map-candidates',{body:{latitude,longitude,radius_km:radius}});if(error)throw error;return data??null;}
 async function nearby({latitude,longitude,radiusKm=8,limit=500,category='all',search='',amenities={},discover=true}={}){if(latitude==null||longitude==null)return[];const amenityNames=Object.entries(amenities).filter(([,enabled])=>Boolean(enabled)).map(([name])=>name);let data=[];try{const{data:rpcData,error}=await client.rpc('map_network_nearby_v1',{p_lat:latitude,p_lng:longitude,p_radius_m:Math.round(radiusKm*1000),p_limit:Math.min(Math.max(limit,1),500),p_category:category==='all'?null:category,p_search:String(search).trim()||null,p_amenity_names:amenityNames.length?amenityNames:null});if(!error&&Array.isArray(rpcData))data=rpcData.map(normalize);}catch{}if(!data.length){try{data=await directSupabaseNearby(client,{latitude,longitude,radiusKm,limit,category,search});}catch{}}if(!data.length&&discover){try{await discoverNearby({latitude,longitude,radiusKm:Math.min(Math.max(Number(radiusKm)||8,8),50)});data=await directSupabaseNearby(client,{latitude,longitude,radiusKm,limit,category,search});}catch{}}return data;}
 async function prepareNearby({latitude,longitude,radiusKm=8}={}){if(latitude==null||longitude==null)return null;const{data:authData}=await client.auth.getUser();const{data,error}=await client.rpc('prepare_universal_location_discovery',{p_lat:latitude,p_lng:longitude,p_radius_m:Math.round(Math.min(Math.max(Number(radiusKm)||8,1),50)*1000),p_user_id:authData?.user?.id||null});if(error)throw error;const locations=Array.isArray(data?.locations)?data.locations.map(normalizePrepared):[];return{...data,locations};}
 async function search(search,{latitude,longitude,radiusKm=50,limit=200}={}){const query=String(search??'').trim();if(!query)return[];if(latitude!=null&&longitude!=null)return nearby({latitude,longitude,radiusKm,limit,search:query});const{data,error}=await client.rpc('search_locations',{search_text:query,max_results:Math.min(limit,200)});if(error)throw error;return(data??[]).filter(r=>Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude))).map(normalize);}
 return Object.freeze({nearby,prepareNearby,discoverNearby,search});}