import { normalizePlace } from '../locations/place.js';
import { buildDiscoveryRequest } from './networkDiscoveryPolicy.js';

export const MAP_CATEGORIES = Object.freeze([
  { id: 'all', label: 'All' }, { id: 'restroom', label: 'Bathrooms' }, { id: 'restaurant', label: 'Restaurants' },
  { id: 'cafe', label: 'Cafes' }, { id: 'gas_station', label: 'Gas' }, { id: 'shopping', label: 'Shopping' },
  { id: 'park', label: 'Parks' }, { id: 'service', label: 'Services' }, { id: 'health', label: 'Health' },
  { id: 'public_safety', label: 'Public safety' }, { id: 'cooling_center', label: 'Cooling centers' },
  { id: 'government', label: 'Government & public' }, { id: 'brand', label: 'Brands' }
]);
function sourceMetadata(row){const metadata=row?.source_metadata&&typeof row.source_metadata==='object'?row.source_metadata:{};const tags=row?.osm_tags&&typeof row.osm_tags==='object'?row.osm_tags:{};const brand=row?.brand??metadata.brand??metadata.brand_name??tags.brand??tags['brand:name']??null;const operator=row?.operator_name??metadata.operator??metadata.operator_name??tags.operator??null;return{metadata,tags,brand,operator};}
function normalize(row){const source=sourceMetadata(row);const brand=source.brand;const rawCategory=String(row?.category??row?.place_type??'service').toLowerCase();const category=brand&&rawCategory==='service'?'brand':rawCategory;return normalizePlace({...row,id:row.id??row.location_id,location_id:row.location_id??row.id,category,distance_km:row.distance_km??(row.distance_meters==null?undefined:row.distance_meters/1000),distance_miles:row.distance_miles??(row.distance_meters==null?undefined:row.distance_meters/1609.344),amenities:row.amenities??source.metadata.amenities??[],fixtures:row.fixtures??source.metadata.fixtures??{},brand,operator_name:source.operator,osm_tags:row.osm_tags??source.metadata.osm_tags??{},source_dataset:row.source_dataset??source.metadata.source_dataset??null,source_external_id:row.source_external_id??source.metadata.source_external_id??null,is_verified:row.is_verified??row.verification_status==='verified'});}
function normalizePrepared(row){return normalize({...row,distance_meters:row.distance_meters==null?undefined:Number(row.distance_meters)});}
function distanceMeters(lat1,lng1,lat2,lng2){const r=v=>v*Math.PI/180,a1=r(lat1),a2=r(lat2),dLat=r(lat2-lat1),dLng=r(lng2-lng1),a=Math.sin(dLat/2)**2+Math.cos(a1)*Math.cos(a2)*Math.sin(dLng/2)**2;return 6371008.8*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
function categoryMatches(r,c){const type=String(r.place_type??r.category??'').toLowerCase();const metadata=sourceMetadata(r);const tags=metadata.tags||{};const bathroom=r.bathroom_verification_status==='has_bathroom'||r.bathroom_verification_status==='verified'||['restroom','bathroom','toilet'].includes(type)||['restroom','bathroom','toilet'].includes(String(r.category||'').toLowerCase())||['toilets','restroom','bathroom'].includes(String(tags.amenity||'').toLowerCase())||['yes','public','customers'].includes(String(tags.toilets||'').toLowerCase())||['yes','public','customers'].includes(String(tags.restroom||'').toLowerCase())||['yes','public','customers'].includes(String(tags.bathroom||'').toLowerCase());const brand=Boolean(r.brand||metadata.brand);if(!c)return true;if(type===c)return true;if(c==='restroom')return bathroom;if(c==='government')return r.is_government===true||type.includes('government');if(c==='brand')return brand;if(c==='restaurant')return type.includes('restaurant')||type.includes('food')||type.includes('fast_food');if(c==='cafe')return type.includes('cafe')||type.includes('coffee');if(c==='gas_station')return type.includes('gas')||type.includes('fuel');if(c==='shopping')return type.includes('shop')||type.includes('retail')||type.includes('supermarket')||type.includes('mall');return false;}
function identityText(value){return String(value??'').trim().toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function stableIdentity(row){const id=row?.location_id??row?.id;if(id!=null&&String(id).trim())return `id:${String(id).trim()}`;const dataset=row?.source_dataset||row?.source||'';const external=row?.source_external_id||row?.external_id||row?.osm_id||row?.place_id;if(external!=null&&String(external).trim())return `external:${identityText(dataset)}:${String(external).trim()}`;return null;}
function placeFingerprint(row){const name=identityText(row?.brand||row?.operator_name||row?.business_name||row?.name);const address=identityText([row?.address,row?.city,row?.state,row?.postal_code].filter(Boolean).join(' '));return `${name}|${address}`;}
function dedupePlaces(rows){const result=[];const byStable=new Map();const fingerprints=[];for(const row of rows||[]){const stable=stableIdentity(row);if(stable&&byStable.has(stable))continue;if(stable)byStable.set(stable,row);const lat=Number(row?.latitude),lng=Number(row?.longitude),fingerprint=placeFingerprint(row);const duplicate=fingerprints.find(existing=>existing.fingerprint===fingerprint&&Number.isFinite(lat)&&Number.isFinite(lng)&&distanceMeters(lat,lng,existing.lat,existing.lng)<=80);if(duplicate)continue;fingerprints.push({fingerprint,lat,lng});result.push(row);}return result;}
function cachedNearby(rows,{latitude,longitude,radiusKm,limit,category,search}){const radiusM=Math.round(Math.min(Math.max(Number(radiusKm)||8,1),100)*1000),q=String(search||'').trim().toLowerCase();return dedupePlaces((rows||[]).map(row=>({...row,...(row.snapshot||{}),id:row.snapshot?.id??row.location_id??row.id,location_id:row.location_id??row.snapshot?.location_id??row.id,source:row.source??row.snapshot?.source??'offline_cache',source_dataset:row.source_dataset??row.snapshot?.source_dataset??'kleenest_offline_pack'})).filter(r=>Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude))).map(r=>({...r,distance_meters:distanceMeters(latitude,longitude,Number(r.latitude),Number(r.longitude))})).filter(r=>r.distance_meters<=radiusM).filter(r=>categoryMatches(r,category==='all'?null:String(category).toLowerCase())).filter(r=>!q||[r.name,r.brand,r.operator_name,r.address,r.city,r.state,r.place_type,r.category,r.description].filter(Boolean).join(' ').toLowerCase().includes(q)).sort((a,b)=>a.distance_meters-b.distance_meters).slice(0,Math.min(Math.max(Number(limit)||500,1),500)).map(normalize));}
function filterLive(rows,{latitude,longitude,radiusKm,limit,category,search}){const radiusM=Math.round(Math.min(Math.max(Number(radiusKm)||8,1),100)*1000),q=String(search||'').trim().toLowerCase();return dedupePlaces((rows||[]).filter(r=>Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude))).map(r=>({...r,distance_meters:distanceMeters(latitude,longitude,Number(r.latitude),Number(r.longitude))})).filter(r=>r.distance_meters<=radiusM).filter(r=>categoryMatches(r,category==='all'?null:String(category).toLowerCase())).filter(r=>!q||[r.name,r.brand,r.operator_name,r.address,r.city,r.state,r.place_type,r.category,r.description].filter(Boolean).join(' ').toLowerCase().includes(q)).sort((a,b)=>a.distance_meters-b.distance_meters).slice(0,Math.min(Math.max(Number(limit)||500,1),500)).map(normalize));}
async function directSupabaseNearby(client,{latitude,longitude,radiusKm,limit,category,search}){const radiusM=Math.round(Math.min(Math.max(Number(radiusKm)||8,1),100)*1000),latDelta=radiusM/111320,lngDelta=radiusM/(111320*Math.max(Math.cos(latitude*Math.PI/180),.2));const{data,error}=await client.from('locations').select('*').eq('is_active',true).gte('latitude',latitude-latDelta).lte('latitude',latitude+latDelta).gte('longitude',longitude-lngDelta).lte('longitude',longitude+lngDelta).limit(2000);if(error)throw error;const c=category==='all'?null:String(category).toLowerCase(),q=String(search||'').trim().toLowerCase();return dedupePlaces((data??[]).filter(r=>Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude))).map(r=>({...r,...(()=>{const s=sourceMetadata(r);return{brand:s.brand,operator_name:s.operator}})(),distance_meters:distanceMeters(latitude,longitude,r.latitude,r.longitude)})).filter(r=>r.distance_meters<=radiusM).filter(r=>categoryMatches(r,c)).filter(r=>!q||[r.name,r.brand,r.operator_name,r.address,r.city,r.state,r.postal_code,r.place_type,r.category,r.description,r.owner_name].filter(Boolean).join(' ').toLowerCase().includes(q)).sort((a,b)=>a.distance_meters-b.distance_meters).slice(0,Math.min(Math.max(Number(limit)||500,1),500)).map(normalize));}
export function createMapNetworkService(client,{offline=null}={}){if(!client)throw new Error('Supabase client is required.');
 async function currentAuthUserId(){try{const{data}=await client.auth.getUser();return data?.user?.id||null;}catch{return null;}}
 async function recordDiscovery(request,discoveredCount=0){try{await client.rpc('record_location_discovery_event',{p_latitude:request.latitude,p_longitude:request.longitude,p_radius_km:request.radiusKm,p_sources:request.sources,p_discovered_count:discoveredCount});}catch{}}
 async function discoverNearby({latitude,longitude,radiusKm=8,userId=null,category='all'}={}){const resolvedUserId=await currentAuthUserId();const request=buildDiscoveryRequest({latitude,longitude,radiusKm,userId:resolvedUserId||userId||null});if(!request)return null;const{data,error}=await client.functions.invoke('ingest-map-candidates',{body:{latitude:request.latitude,longitude:request.longitude,radius_km:request.radiusKm,category,sources:request.sources,collect:request.collect,enrich_existing:request.enrichExisting,share_network_events:request.shareNetworkEvents}});if(error)throw error;const result=data??{};await recordDiscovery(request,Number(result?.discovered)||Number(result?.discovered_count)||0);return result;}
 async function nearby({latitude,longitude,radiusKm=8,limit=500,category='all',search='',amenities={},discover=true}={}){if(latitude==null||longitude==null)return[];if(typeof navigator!=='undefined'&&navigator.onLine===false)return cachedNearby(await offline?.cachedLocations?.(),{latitude,longitude,radiusKm,limit,category,search});const amenityNames=Object.entries(amenities).filter(([,enabled])=>Boolean(enabled)).map(([name])=>name);let data=[],lastError=null;const runRpc=async()=>{const{data:rpcData,error}=await client.rpc('map_network_nearby_v1',{p_lat:latitude,p_lng:longitude,p_radius_m:Math.round(radiusKm*1000),p_limit:Math.min(Math.max(limit,1),500),p_category:category==='all'?null:category,p_search:String(search).trim()||null,p_amenity_names:amenityNames.length?amenityNames:null});if(error)throw error;return dedupePlaces(Array.isArray(rpcData)?rpcData.map(normalize):[]);};try{data=await runRpc();}catch(error){lastError=error;}if(!data.length){try{data=await directSupabaseNearby(client,{latitude,longitude,radiusKm,limit,category,search});}catch(error){lastError=lastError||error;}}if(discover){try{const discovery=await discoverNearby({latitude,longitude,radiusKm,category});const live=filterLive(discovery?.locations,{latitude,longitude,radiusKm,limit,category,search});if(live.length){const byId=new Map(data.map(r=>[stableIdentity(r)||`fp:${placeFingerprint(r)}`,r]));for(const row of live){const key=stableIdentity(row)||`fp:${placeFingerprint(row)}`;if(!byId.has(key))byId.set(key,row);}data=dedupePlaces([...byId.values()].sort((a,b)=>(a.distance_km??Infinity)-(b.distance_km??Infinity)).slice(0,Math.min(Math.max(Number(limit)||500,1),500)));}}catch(error){lastError=lastError||error;}if(!data.length){try{const prepared=await prepareNearby({latitude,longitude,radiusKm,category,search,limit});data=Array.isArray(prepared?.locations)?prepared.locations:[];}catch(error){lastError=lastError||error;}}}if(!data.length&&lastError)throw new Error(`Nearby location retrieval failed: ${lastError.message||lastError}`);return data;}
 async function prepareNearby({latitude,longitude,radiusKm=8,userId=null,category='all',search='',limit=500}={}){const request=buildDiscoveryRequest({latitude,longitude,radiusKm,userId});if(!request)return null;const{data:authData}=await client.auth.getUser();const{data,error}=await client.rpc('prepare_universal_location_discovery',{p_lat:request.latitude,p_lng:request.longitude,p_radius_m:Math.round(request.radiusKm*1000),p_user_id:authData?.user?.id||null});if(error)throw error;const locations=filterLive(Array.isArray(data?.locations)?data.locations.map(normalizePrepared):[],{latitude,longitude,radiusKm,limit,category,search});await recordDiscovery(request,locations.length);return{...data,locations};}
 async function search(search,{latitude,longitude,radiusKm=50,limit=200}={}){const query=String(search??'').trim();if(!query)return[];if(latitude!=null&&longitude!=null)return nearby({latitude,longitude,radiusKm,limit,search:query});const{data,error}=await client.rpc('search_locations',{search_text:query,max_results:Math.min(limit,200)});if(error)throw error;return dedupePlaces((data??[]).filter(r=>Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude))).map(normalize));}
 return Object.freeze({nearby,prepareNearby,discoverNearby,search});}
