export function createBusinessManagementService(client) {
  if (!client) throw new Error('Supabase client is required.');
  async function user() { const { data: { user }, error } = await client.auth.getUser(); if (error) throw error; if (!user) throw new Error('Sign in to continue.'); return user; }
  async function rpc(name, args = {}) { await user(); const { data, error } = await client.rpc(name, args); if (error) throw error; return data; }
  return Object.freeze({
    listBusinesses: () => rpc('get_business_dashboard', {}),
    listLocations: businessId => rpc('business_list_locations', { p_business_id: businessId }),
    createLocation: (businessId, payload) => rpc('business_manage_location', { p_business_id: businessId, p_location_id: null, p_action: 'create', p_payload: payload }),
    updateLocation: (businessId, locationId, payload) => rpc('business_manage_location', { p_business_id: businessId, p_location_id: locationId, p_action: 'update', p_payload: payload }),
    listQrs: businessId => rpc('business_qr_detail', { p_business_id: businessId }),
    createQr: (businessId, locationId, payload) => rpc('business_manage_qr', { p_business_id: businessId, p_location_id: locationId, p_qr_id: null, p_action: 'create', p_payload: payload }),
    createQrProgram: (qrCodeId, programType, name, description = null, rewardConfig = {}, triggerCount = 1) => rpc('create_qr_engagement_program', { p_qr_code_id: qrCodeId, p_program_type: programType, p_name: name, p_description: description, p_reward_config: rewardConfig, p_trigger_count: triggerCount }),
    listQrPrograms: qrCodeId => rpc('list_qr_engagement_programs', { p_qr_code_id: qrCodeId }),
    resolveQrAction: code => rpc('resolve_custom_qr_action', { p_code: code }),
    redeemQr: (code, metadata = {}) => rpc('redeem_qr_code', { p_code: code, p_metadata: metadata }),
    recordQrAttribution: (qrCodeId, locationId, businessId, actionType, source, metadata = {}) => rpc('record_qr_attribution', { p_qr_code_id: qrCodeId, p_location_id: locationId, p_business_id: businessId, p_action_type: actionType, p_source: source, p_metadata: metadata }),
    listCampaigns: businessId => rpc('business_list_campaigns', { p_business_id: businessId }),
    createCampaign: (businessId, payload) => rpc('business_manage_campaign', { p_business_id: businessId, p_campaign_id: null, p_action: 'create', p_name: payload.name, p_campaign_type: payload.type ?? 'general', p_goal: payload.goal ?? '', p_status: payload.status ?? 'draft' }),
    listEvents: businessId => rpc('business_list_events', { p_business_id: businessId }),
    listPromotions: businessId => rpc('business_promotion_detail', { p_business_id: businessId }),
    createPromotion: (businessId, payload) => rpc('business_create_promotion', { p_business_id: businessId, p_title: payload.name ?? payload.title ?? '', p_description: payload.description ?? null, p_discount: payload.discount ?? null, p_location_id: payload.locationId ?? null, p_starts_at: payload.startsAt ?? undefined, p_ends_at: payload.endsAt ?? undefined }),
    listContests: businessId => rpc('business_list_contests', { p_business_id: businessId }),
    analytics: businessId => rpc('business_summary_analytics', { p_business_id: businessId }),
    leaderboard: (metric = 'check_ins', limit = 10) => rpc('get_business_leaderboard', { p_metric: metric, p_limit: limit }),
    networkLeaderboard: (leaderboardKey, limit = 25) => rpc('get_platform_leaderboard', { p_leaderboard_key: leaderboardKey, p_limit: limit }),
    locationIntelligence: businessId => rpc('business_location_intelligence', { p_business_id: businessId }),
    growthAnalytics: businessId => rpc('business_growth_analytics', { p_business_id: businessId }),
    roiAnalytics: businessId => rpc('business_roi_analytics', { p_business_id: businessId }),
    visitorAnalytics: businessId => rpc('business_visitors_analytics', { p_business_id: businessId }),
    engagementFunnel: businessId => rpc('get_business_engagement_funnel', { p_business_id: businessId }),
    occupancyAnalytics: businessId => rpc('business_occupancy_analytics', { p_business_id: businessId }),
    benchmarkAnalytics: businessId => rpc('business_benchmark_analytics', { p_business_id: businessId }),
    campaignAnalytics: businessId => rpc('business_campaign_analytics', { p_business_id: businessId }),
    promotionAnalytics: businessId => rpc('business_promotion_analytics', { p_business_id: businessId }),
    qrAnalytics: businessId => rpc('business_qr_analytics', { p_business_id: businessId }),
    eventAnalytics: businessId => rpc('business_event_analytics', { p_business_id: businessId }),
    mediaAnalytics: businessId => rpc('business_media_analytics', { p_business_id: businessId }),
    partnerAnalytics: businessId => rpc('business_partner_analytics', { p_business_id: businessId }),
    partnerProgramUsage: partnerProgramId => rpc('business_partner_program_usage', { p_partner_program_id: partnerProgramId }),
    rewardsAnalytics: businessId => rpc('business_rewards_analytics', { p_business_id: businessId }),
    engagementAnalytics: businessId => rpc('business_engagement_analytics', { p_business_id: businessId }),
    reviewAnalytics: businessId => rpc('business_review_analytics', { p_business_id: businessId }),
    replyToReview: (businessId, reviewId, reply) => rpc('business_reply_review', { p_business_id: businessId, p_review_id: reviewId, p_reply: String(reply ?? '').trim() })
  });
}
