export const PRODUCT_TYPES = Object.freeze({ ONE_TIME: 'one_time', RECURRING: 'recurring' });
export const PRODUCT_CODES = Object.freeze({ PREMIUM: 'premium', FAMILY: 'family', BUSINESS: 'business', FLEET: 'fleet', ENTERPRISE: 'enterprise' });
const FALLBACK_COMMERCIAL_MODEL = Object.freeze({ premium: { type: PRODUCT_TYPES.ONE_TIME, priceCents: 500, currency: 'USD', interval: null }, premium_user: { type: PRODUCT_TYPES.ONE_TIME, priceCents: 500, currency: 'USD', interval: 'once' }, family: { type: PRODUCT_TYPES.ONE_TIME, priceCents: 2000, currency: 'USD', interval: 'once', maxMembers: 5 }, business: { type: PRODUCT_TYPES.RECURRING, currency: 'USD', interval: 'month' }, business_standard: { type: PRODUCT_TYPES.RECURRING, currency: 'USD', interval: 'month' }, business_growth: { type: PRODUCT_TYPES.RECURRING, currency: 'USD', interval: 'month' }, fleet: { type: PRODUCT_TYPES.RECURRING, currency: 'USD', interval: 'month' }, enterprise: { type: PRODUCT_TYPES.RECURRING, currency: 'USD', interval: 'month' } });
export function normalizePlan(plan) { const code = String(plan?.code ?? plan?.slug ?? plan?.tier ?? '').toLowerCase(); const fallback = FALLBACK_COMMERCIAL_MODEL[code] ?? {}; const interval = plan?.interval ?? fallback.interval ?? null; const inferredType = interval === 'once' ? PRODUCT_TYPES.ONE_TIME : interval ? PRODUCT_TYPES.RECURRING : null; return Object.freeze({ ...plan, code, billingType: plan?.billing_type ?? plan?.type ?? inferredType ?? fallback.type ?? null, priceCents: Number(plan?.price_cents ?? fallback.priceCents ?? 0), currency: String(plan?.currency ?? fallback.currency ?? 'USD').toUpperCase(), interval, maxMembers: Number(plan?.max_members ?? plan?.max_users ?? fallback.maxMembers ?? 0) || null }); }
export function isOneTimePlan(plan) { return normalizePlan(plan).billingType === PRODUCT_TYPES.ONE_TIME; }
export function isRecurringPlan(plan) { return normalizePlan(plan).billingType === PRODUCT_TYPES.RECURRING; }
export function getCommercialModel(code) { return FALLBACK_COMMERCIAL_MODEL[String(code ?? '').toLowerCase()] ?? null; }
const rowTime=row=>Math.max(...['updated_at','created_at','current_period_start','current_period_end'].map(key=>Date.parse(row?.[key]||'')||0));
export function createBillingService(client) { if (!client) throw new Error('Supabase client is required.'); return Object.freeze({
  listPlans: async () => { const { data, error } = await client.from('pricing_catalog').select('*').eq('active', true).order('price_cents', { ascending: true }); if (error) throw error; return (data ?? []).map(normalizePlan); },
  getMySubscription: async () => { const { data, error } = await client.rpc('user_subscription_summary'); if (error) throw error; const summary = Array.isArray(data) ? data[0] ?? null : data ?? null; const rows = Array.isArray(summary?.subscriptions) ? [...summary.subscriptions] : []; if (!rows.length) return null; rows.sort((a,b)=>{const aLive=['active','trialing','past_due'].includes(String(a?.status??'').toLowerCase())?1:0;const bLive=['active','trialing','past_due'].includes(String(b?.status??'').toLowerCase())?1:0;const aRecurring=a?.provider==='stripe'?1:0;const bRecurring=b?.provider==='stripe'?1:0;return bLive-aLive||bRecurring-aRecurring||rowTime(b)-rowTime(a);}); const active = rows[0]; return Object.freeze({ ...active, profile: summary?.profile ?? null, subscriptions: rows }); },
  getMyEntitlements: async () => { const { data, error } = await client.rpc('get_current_user_product_entitlements'); if (error) throw error; return Array.isArray(data) ? data : data ? [data] : []; },
  getCommercialModel
}); }
