import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const URL=Deno.env.get("SUPABASE_URL")!,ANON=Deno.env.get("SUPABASE_ANON_KEY")!,SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(URL,SERVICE,{auth:{persistSession:false}});
const headers={"content-type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers});
const clamp=(n:number,a:number,b:number)=>Math.min(Math.max(n,a),b);
async function auth(req:Request){const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)throw new Error("Authentication required");if(token===SERVICE)return;const c=createClient(URL,ANON,{auth:{persistSession:false}});const {data,error}=await c.auth.getUser(token);if(error||!data.user)throw new Error("Invalid authentication");}
function osmQuery(s:number,w:number,n:number,e:number){return `[out:json][timeout:25];(nwr[amenity~"restaurant|cafe|fuel|toilets|clinic|hospital|fire_station|police"](${s},${w},${n},${e});nwr[shop](${s},${w},${n},${e});nwr[leisure=park](${s},${w},${n},${e});nwr[toilets=yes](${s},${w},${n},${e});nwr[changing_table=yes](${s},${w},${n},${e}););out center tags;`;}
function normOsm(el:any){const t=el.tags||{},c=el.center||{lat:el.lat,lon:el.lon},bath=t.amenity==='toilets'||t.toilets==='yes'||t.changing_table==='yes';const type=t.amenity==='restaurant'?'restaurant':t.amenity==='cafe'?'cafe':t.amenity==='fuel'?'gas_station':t.shop?'shopping':t.leisure==='park'?'park':t.amenity==='clinic'||t.amenity==='hospital'?'health':t.amenity==='fire_station'||t.amenity==='police'?'public_safety':bath?'restroom':'service';return {source_id:`osm:${el.type}:${el.id}`,latitude:c.lat,longitude:c.lon,name:t.name||t.operator||(bath?'Public restroom':'Unnamed place'),place_type:type,address:[t['addr:housenumber'],t['addr:street']].filter(Boolean).join(' ')||null,city:t['addr:city']||null,state:t['addr:state']||null,postal_code:t['addr:postcode']||null,phone:t.phone||t['contact:phone']||null,website:t.website||t['contact:website']||null,source_metadata:{source:'OpenStreetMap',osm_type:el.type,osm_id:String(el.id),access:t.access||null,fee:t.fee||null,wheelchair:t.wheelchair||null,changing_table:t.changing_table||null,bathroom_confirmed:bath}};}
function normRefuge(x:any){return {source_id:`refuge_restrooms:${x.id}`,latitude:Number(x.latitude),longitude:Number(x.longitude),name:x.name||'REFUGE restroom',place_type:'restroom',address:x.street||null,city:x.city||null,state:x.state||null,postal_code:null,phone:null,website:null,source_metadata:{source:'REFUGE Restrooms',refuge_id:x.id,accessible:x.accessible??null,unisex:x.unisex??null,changing_table:x.changing_table??null,approved:x.approved??null,upvotes:x.upvote??null,downvotes:x.downvote??null,comment:x.comment??null,directions:x.directions??null,updated_at:x.updated_at??null}};}
async function fetchOsm(s:number,w:number,n:number,e:number){const eps=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];for(const ep of eps){try{const r=await fetch(ep,{method:'POST',headers:{'content-type':'text/plain','user-agent':'KleenestApp/1.0'},body:osmQuery(s,w,n,e)});if(r.ok){const d=await r.json();return Array.isArray(d.elements)?d.elements:[];}}catch{}}return [];}
async function fetchRefuge(lat:number,lng:number){const u=`https://www.refugerestrooms.org/api/v1/restrooms/by_location?lat=${encodeURIComponent(lat)}&lng=${encodeURIComponent(lng)}`;const r=await fetch(u,{headers:{'user-agent':'KleenestApp/1.0'}});if(!r.ok)throw new Error(`REFUGE acquisition HTTP ${r.status}`);const d=await r.json();return Array.isArray(d.restrooms)?d.restrooms:Array.isArray(d)?d:[];}
async function persist(source:string,rows:any[]){let imported=0,updated=0;for(let i=0;i<rows.length;i+=250){const out=await db.rpc('ingest_external_locations',{p_source_key:source,p_rows:rows.slice(i,i+250)});if(out.error)throw out.error;imported+=Number(out.data?.imported_locations||0);updated+=Number(out.data?.updated_locations||0);}return {imported,updated};}
Deno.serve(async req=>{try{if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return json({ok:false,error:{code:'METHOD_NOT_ALLOWED'}},405);await auth(req);const b=await req.json(),lat=Number(b.latitude),lng=Number(b.longitude),radius=clamp(Number(b.radiusKm)||10,1,25);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<-90||lat>90||lng<-180||lng>180)throw new Error('Valid latitude and longitude are required');const dLat=radius/111,dLng=radius/(111*Math.max(Math.cos(lat*Math.PI/180),0.2)),s=lat-dLat,w=lng-dLng,n=lat+dLat,e=lng+dLng;const [osm,refuge]=await Promise.allSettled([fetchOsm(s,w,n,e),fetchRefuge(lat,lng)]);const osmRows=osm.status==='fulfilled'?Array.from(new Map(osm.value.map((x:any)=>[`${x.type}:${x.id}`,normOsm(x)])).values()).filter((x:any)=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)):[];const refugeRows=refuge.status==='fulfilled'?refuge.value.map(normRefuge).filter((x:any)=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)):[];let imported=0,updated=0;const errors:any[]=[];if(osmRows.length){const r=await persist('osm',osmRows);imported+=r.imported;updated+=r.updated;}if(refugeRows.length){const r=await persist('refuge_restrooms',refugeRows);imported+=r.imported;updated+=r.updated;}if(osm.status==='rejected')errors.push({code:'OSM_ACQUISITION_FAILED',stage:'acquisition',message:String(osm.reason),retryable:true});if(refuge.status==='rejected')errors.push({code:'REFUGE_ACQUISITION_FAILED',stage:'acquisition',message:String(refuge.reason),retryable:true});return json({ok:true,acquisition_status:(osmRows.length||refugeRows.length)?'success':'empty',persistence_status:'succeeded',job_status:'completed',discovered:osmRows.length+refugeRows.length,imported,updated,errors,providers:{osm:osmRows.length,refuge_restrooms:refugeRows.length}});}catch(e){return json({ok:false,error:{code:'MAP_BOOTSTRAP_FAILED',message:e instanceof Error?e.message:String(e)}},500);}});
