import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Activity, AlertTriangle, MapPinned, Settings2, Radio, Users, Building2, Wrench, Network, ShieldCheck, Database, ExternalLink, Globe2, RefreshCw } from 'lucide-react';
import { useAppContext } from '../AppContext.jsx';
import WorkspaceShell from './WorkspaceShell.jsx';
import AiAssistPanel from './AiAssistPanel.jsx';
import './AdminMaintenancePage.css';

const MARKETS = [['STL','St. Louis'],['KCMO','Kansas City'],['NYC','New York City'],['LA','Los Angeles'],['CHI','Chicago'],['DFW','Dallas–Fort Worth'],['HOU','Houston'],['DC','Washington, DC'],['MIA','Miami'],['PHL','Philadelphia']];
const INGESTION_SOURCES = [
  { key:'osm', name:'OpenStreetMap / Overpass', url:'https://www.openstreetmap.org', kind:'Broad geospatial bootstrap', status:'Active ingestion', description:'Primary free map bootstrap source. Amenity tags, addresses, brands and operators normalize into canonical locations.' },
  { key:'data_gov', name:'Data.gov', url:'https://data.gov', kind:'Public-data catalog', status:'Active ingestion', description:'U.S. public datasets are cataloged and imported through the governed external-location pipeline.' },
  { key:'refuge_restrooms', name:'REFUGE Restrooms', url:'https://refugerestrooms.org', kind:'Restroom-specific evidence', status:'Registered source', description:'Complementary restroom-oriented evidence source. Records remain independent evidence until reconciled to canonical locations.' },
  { key:'stlouis_open_data', name:'City of St. Louis Open Data', url:'https://www.stlouis-mo.gov/data/', kind:'Municipal provenance', status:'Registered source', description:'Local civic/facility context with source attribution. Raw municipal data is not automatically treated as restroom verification.' },
  { key:'nps', name:'National Park Service', url:'https://www.nps.gov/subjects/developer/api-documentation.htm', kind:'Federal public data', status:'Registered source', description:'National Park Service API data is available as a governed external source for future location and facility reconciliation.' },
  { key:'transit_gtfs', name:'Transit GTFS feeds', url:'https://gtfs.org/', kind:'Transit / amenity context', status:'Registered source', description:'Agency GTFS feeds can contribute transit context and nearby amenities while preserving originating-feed provenance.' },
];
const n=v=>Number.isFinite(Number(v))?Number(v):0;

export default function AdminMaintenancePage(){
  const { services, profile, isPlatformOwner, loading: authLoading } = useAppContext();
  const [busy, setBusy] = useState('');
  const [result, setResult] = useState(null);
  const [resultOperation, setResultOperation] = useState('');
  const [snapshot,setSnapshot]=useState(null);
  const [snapshotError,setSnapshotError]=useState('');
  const [open, setOpen] = useState(true);
  const loadSnapshot=async()=>{if(authLoading||!isPlatformOwner||!profile)return;setSnapshotError('');try{setSnapshot(await services.admin.controlPlaneSnapshot(profile));}catch(error){setSnapshotError(error?.message||'Unable to load owner control-plane snapshot.');}};
  useEffect(()=>{void loadSnapshot();},[authLoading,isPlatformOwner,profile]);
  const run = async (key, fn) => { if(authLoading || !isPlatformOwner || !profile)return; setBusy(key); setResult(null); setResultOperation(key); try{setResult(await fn());await loadSnapshot();}catch(error){setResult({ok:false,error:error?.message||String(error)})}finally{setBusy('')} };
  const ingest = (key, source, market) => run(key, () => services.admin.ingestMarket(profile, source, market));
  const catalog = () => run('catalog', () => services.admin.catalogPublicDatasets(profile, 50));

  if(authLoading)return <WorkspaceShell workspace="admin"><section className="empty-state"><ShieldCheck size={28}/><h2>Loading administration</h2><p>Waiting for the authenticated owner session before starting administrative operations.</p></section></WorkspaceShell>;
  if(!isPlatformOwner)return <WorkspaceShell workspace="consumer"><section className="empty-state"><ShieldCheck size={28}/><h2>Administration unavailable</h2><p>Platform owner access is required for security and maintenance operations.</p></section></WorkspaceShell>;

  const overview=snapshot?.overview||{},integrity=snapshot?.integrity||{},capSummary=snapshot?.capabilities?.summary||{},resources=Array.isArray(snapshot?.resources?.items)?snapshot.resources.items:[];
  return <WorkspaceShell workspace="admin"><section className="page admin-maintenance">
    <header className="admin-hero"><div><span className="eyebrow">ADMINISTRATION · CONTROL PLANE</span><h1>Network operations & platform health</h1><p>Govern the Kleenest network from one owner-only surface with authoritative platform health, capability contracts, backend resources, ingestion, diagnostics, and source provenance.</p></div><div className="hero-actions"><button className="button secondary" onClick={loadSnapshot}><RefreshCw size={17}/>Refresh health</button><Link className="button secondary" to="/admin/capabilities"><Network size={17}/>Capability Hub</Link><Link className="button secondary" to="/admin/operational-capabilities"><Database size={17}/>Operational catalog</Link></div></header>

    {snapshotError&&<p className="form-error" role="alert">{snapshotError}</p>}
    <section className="admin-panel"><div className="panel-heading"><div><span className="eyebrow">OWNER CONTROL PLANE</span><h2>Platform health snapshot</h2><p>One protected snapshot joins platform counts, integrity findings, capability authorization health, and live backend catalog state.</p></div><ShieldCheck size={22}/></div><div className="reward-stats"><div className="reward-stat"><Users size={18}/><strong>{n(overview.users)}</strong><span>users</span></div><div className="reward-stat"><Building2 size={18}/><strong>{n(overview.businesses)}</strong><span>businesses</span></div><div className="reward-stat"><MapPinned size={18}/><strong>{n(overview.locations)}</strong><span>locations</span></div><div className="reward-stat"><AlertTriangle size={18}/><strong>{n(integrity.high)}</strong><span>high integrity issues</span></div><div className="reward-stat"><Activity size={18}/><strong>{n(capSummary.backend_contract_present)}</strong><span>secured capability contracts</span></div><div className="reward-stat"><Database size={18}/><strong>{resources.length}</strong><span>cataloged backend resources</span></div></div><p className="muted">Integrity status: <strong>{integrity.status||'unavailable'}</strong> · Snapshot source remains live owner-only database authority.</p></section>

    <section className="admin-panel"><div className="panel-heading"><div><span className="eyebrow">CONTROL CENTER</span><h2>Network operations</h2></div><MapPinned size={22}/></div><div className="action-row"><Link className="button secondary" to="/admin/crud"><Settings2 size={18}/>Network CRUD</Link><Link className="button secondary" to="/owner/audit"><ShieldCheck size={18}/>Owner audit</Link><Link className="button secondary" to="/fleet"><Radio size={18}/>Fleet operations</Link><Link className="button secondary" to="/business"><Building2 size={18}/>Business operations</Link><Link className="button secondary" to="/map"><MapPinned size={18}/>Network map</Link><Link className="button secondary" to="/notifications"><Users size={18}/>Community activity</Link></div></section>

    <section className="admin-panel"><div className="panel-heading"><div><span className="eyebrow">DIAGNOSTICS</span><h2>Data health & reconciliation</h2><p>These controls operate against protected owner-only functions and refresh the control-plane snapshot after completion.</p></div><Wrench size={22}/></div><div className="action-row"><button disabled={!!busy} onClick={()=>run('health',()=>services.admin.health(profile))}>{busy==='health'?'Checking…':'Backend health'}</button><button disabled={!!busy} onClick={()=>run('refresh',()=>services.admin.refreshDerived(profile))}>{busy==='refresh'?'Refreshing…':'Refresh derived data'}</button><button disabled={!!busy} onClick={()=>run('quality',()=>services.admin.locationQuality(profile))}>{busy==='quality'?'Auditing…':'Location quality audit'}</button><button disabled={!!busy} onClick={()=>run('addresses',()=>services.admin.backfillAddresses(profile,25))}>{busy==='addresses'?'Backfilling…':'Backfill 25 addresses'}</button></div></section>

    <section className="admin-panel"><div className="panel-heading"><div><span className="eyebrow">SOURCE REGISTRY · 6 ACTIVE</span><h2>Ingestion sources</h2><p>These are the governed external sources now represented by the canonical registry. Source records are evidence; they do not bypass canonical identity or verification rules.</p></div><Globe2 size={22}/></div><div className="source-grid">{INGESTION_SOURCES.map(source=><article className="source-card" key={source.key}><div className="source-meta"><span>{source.kind}</span><span>{source.status}</span></div><strong>{source.name}</strong><p>{source.description}</p><a className="source-link" href={source.url} target="_blank" rel="noreferrer">Source documentation <ExternalLink size={13}/></a><div className="source-actions">{source.key==='osm'&&<button disabled={!!busy} onClick={()=>run('osm-top',()=>services.admin.ingestTopMarkets(profile,'osm'))}>{busy==='osm-top'?'Running…':'Run OSM top markets'}</button>}{source.key==='data_gov'&&<button disabled={!!busy} onClick={()=>run('data-top',()=>services.admin.ingestTopMarkets(profile,'datagov'))}>{busy==='data-top'?'Running…':'Run Data.gov top markets'}</button>}{source.key!=='osm'&&source.key!=='data_gov'&&<button disabled={!!busy} onClick={catalog}>{busy==='catalog'?'Cataloging…':'Catalog datasets'}</button>}</div></article>)}</div><div className="notice">Registered-source actions deliberately use the existing governed ingestion/catalog boundary. New sources are visible now without pretending their provider-specific adapters are complete.</div></section>

    <section className="admin-panel"><button type="button" className="admin-collapse" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span><span className="eyebrow">MARKET INGESTION</span><h2>Run OSM / Data.gov by market</h2><p>Use the canonical market-bathroom-ingest-v5 path for bounded city ingestion.</p></span><Wrench size={22}/></button>{open&&<div className="market-grid"><div className="market-card"><strong>Top markets</strong><span>Run the bounded ten-market batch.</span><div className="action-row"><button disabled={!!busy} onClick={()=>run('osm-top',()=>services.admin.ingestTopMarkets(profile,'osm'))}>{busy==='osm-top'?'Running…':'OSM top 10'}</button><button disabled={!!busy} onClick={()=>run('data-top',()=>services.admin.ingestTopMarkets(profile,'datagov'))}>{busy==='data-top'?'Running…':'Data.gov top 10'}</button><button disabled={!!busy} onClick={catalog}>{busy==='catalog'?'Cataloging…':'Catalog public datasets'}</button></div></div>{MARKETS.map(([code,label])=><div className="market-card" key={code}><strong>{label}</strong><span>{code}</span><div className="action-row"><button disabled={!!busy} onClick={()=>ingest(`${code}-osm`,'osm',code)}>{busy===`${code}-osm`?'Running…':`${label} OSM`}</button><button disabled={!!busy} onClick={()=>ingest(`${code}-data`,'datagov',code)}>{busy===`${code}-data`?'Running…':`${label} Data.gov`}</button><button disabled={!!busy} onClick={()=>run(`${code}-both`,async()=>({osm:await services.admin.ingestMarket(profile,'osm',code),data_gov:await services.admin.ingestMarket(profile,'datagov',code)}))}>{busy===`${code}-both`?'Running…':`${label} both`}</button></div></div>)}</div>}</section>

    <section className="admin-panel"><div className="panel-heading"><div><span className="eyebrow">DATASET INTELLIGENCE</span><h2>Catalog & review external evidence</h2><p>Cataloged datasets remain governed evidence and can be reviewed before canonical ingestion.</p></div><Database size={22}/></div><div className="action-row"><button disabled={!!busy} onClick={catalog}>{busy==='catalog'?'Cataloging…':'Discover public datasets'}</button><Link className="button secondary" to="/intelligence">Open network intelligence</Link><Link className="button secondary" to="/admin/crud">Review external data</Link></div></section>

    {result&&<AiAssistPanel task="admin_operations" title="Admin operations copilot" description="Summarizes the authoritative result below and highlights failures, stale or low-quality signals, unusual counts, and the safest next checks. It cannot run maintenance actions." instruction="Summarize this administrative operation result. Identify concrete problems or anomalies and recommend only non-destructive next checks. Do not claim any repair occurred." context={{operation:resultOperation,result}} actionLabel="Analyze operation"/>}
    {result&&<pre className="result">{JSON.stringify(result,null,2)}</pre>}
  </section></WorkspaceShell>;
}
