import { useMemo, useState } from 'react';
import { CheckCircle2, Eye, MapPin, RotateCcw, Save, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import WorkspaceShell from './WorkspaceShell.jsx';
import { useAppContext } from '../AppContext.jsx';
import { CATEGORY_GLYPHS, MAP_ICON_OPTIONS, placeStatus } from './MapMarkerSystem.jsx';
import './MapIdentity.css';

function keyFor(id) { return `kleenest.map.identity.${id}`; }
function readIdentity(id, fallback = {}) { try { const raw = window.localStorage.getItem(keyFor(id)); return raw ? { ...fallback, ...JSON.parse(raw) } : fallback; } catch { return fallback; } }

export default function BusinessMapIdentityPage() {
  const { user, selectedBusiness, selectedBusinessId, businessMemberships, isPlatformOwner } = useAppContext();
  const businesses = Array.isArray(businessMemberships) ? businessMemberships : [];
  const current = useMemo(() => businesses.find(b => String(b.business_id || b.id) === String(selectedBusinessId)) || selectedBusiness || businesses[0] || null, [businesses, selectedBusiness, selectedBusinessId]);
  const businessId = current?.business_id || current?.id || '';
  const fallback = { logoUrl: current?.logo_url || current?.logoUrl || '', iconKey: current?.map_icon || current?.map_icon_key || 'auto' };
  const [identity, setIdentity] = useState(() => readIdentity(businessId, fallback));
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const icon = MAP_ICON_OPTIONS.find(item => item.id === identity.iconKey) || MAP_ICON_OPTIONS[0];
  const status = placeStatus({ premium: true, is_verified: true });
  const save = () => { if (!businessId) return; try { window.localStorage.setItem(keyFor(businessId), JSON.stringify(identity)); window.dispatchEvent(new CustomEvent('kleenest:business-map-identity-updated', { detail: { businessId } })); setMessage('Map identity saved. Your preferred icon and logo will appear on close-zoom map markers.'); setError(''); } catch (e) { setError(e.message || 'Unable to save map identity.'); } };
  const reset = () => { setIdentity(fallback); try { window.localStorage.removeItem(keyFor(businessId)); } catch {} setMessage('Map identity reset to business defaults.'); };
  if (!user && !isPlatformOwner) return <WorkspaceShell workspace="business"><section className="empty-state"><h2>Sign in to manage map identity</h2><Link className="primary" to="/auth">Sign in</Link></section></WorkspaceShell>;
  if (!businessId) return <WorkspaceShell workspace="business"><section className="empty-state"><h2>No business selected</h2><p>Connect or select a business before configuring its map identity.</p><Link className="secondary" to="/business">Business dashboard</Link></section></WorkspaceShell>;
  return <WorkspaceShell workspace="business"><section className="page map-identity-page"><div className="page-header"><div><span className="eyebrow">BUSINESS MAP IDENTITY</span><h1>How customers recognize you on the map</h1><p>Keep your recognizable business identity while Kleenest keeps status and trust signals consistent across the map.</p></div><Link className="secondary" to="/business">Back to business</Link></div>{message && <div className="identity-message success"><CheckCircle2 size={17}/>{message}</div>}{error && <div className="identity-message error">{error}</div>}<div className="identity-grid"><section className="detail-panel identity-controls"><div className="panel-heading"><div><span className="eyebrow">IDENTITY</span><h2>Marker preferences</h2></div><Sparkles size={22}/></div><label className="form-field"><span>Logo URL</span><input value={identity.logoUrl || ''} onChange={e => setIdentity(value => ({ ...value, logoUrl: e.target.value }))} placeholder="https://…/your-logo.png"/><small>Use a square or transparent logo. Kleenest will fall back to your preferred icon if the image cannot load.</small></label><div className="identity-icon-grid">{MAP_ICON_OPTIONS.filter(item => item.id !== 'auto').map(item => <button type="button" key={item.id} className={`identity-icon-option ${identity.iconKey === item.id ? 'active' : ''}`} onClick={() => setIdentity(value => ({ ...value, iconKey: item.id }))}><span>{item.glyph}</span><small>{item.label}</small></button>)}</div><div className="identity-actions"><button className="primary" onClick={save}><Save size={16}/> Save map identity</button><button className="secondary" onClick={reset}><RotateCcw size={16}/> Reset</button></div></section><section className="detail-panel marker-preview"><div className="panel-heading"><div><span className="eyebrow">LIVE PREVIEW</span><h2>Customer-facing marker</h2></div><Eye size={22}/></div><div className="preview-map"><div className="preview-marker"><div className="preview-identity">{identity.logoUrl ? <img src={identity.logoUrl} alt="Business logo" onError={e => { e.currentTarget.style.display = 'none'; e.currentTarget.nextElementSibling.style.display = 'inline-flex'; }}/>: null}<span className="preview-fallback">{identity.logoUrl ? icon.glyph : icon.glyph}</span></div><span className="preview-status">{status.glyph}</span><small>{current?.name || current?.business_name || 'Your business'}</small></div><div className="preview-label"><MapPin size={15}/><strong>{current?.name || current?.business_name || 'Your business'}</strong><span>{icon.label}</span></div></div><div className="preview-rules"><div><strong>Business identity</strong><span>{identity.logoUrl ? 'Your logo' : `${icon.glyph} ${icon.label}`}</span></div><div><strong>Kleenest status</strong><span>✓ Verified / ◆ Premium</span></div><div><strong>Map behavior</strong><span>Clusters at distance · branded marker when zoomed in</span></div></div></section></div></section></WorkspaceShell>;
}
