import { useEffect,useMemo,useRef,useState } from 'react';
import { Link } from 'react-router-dom';
import { RefreshCw,Sparkles } from 'lucide-react';
import { useAppContext } from '../AppContext.jsx';
import WorkspaceShell from './WorkspaceShell.jsx';
import BusinessIntelligenceActions from './BusinessIntelligenceActions.jsx';
import { buildBusinessRecommendations,rankBusinessRecommendations } from '../domains/business/intelligence-recommendations.js';
const rows=value=>{if(Array.isArray(value))return value;if(!value||typeof value!=='object')return[];for(const key of ['rows','locations','intelligence','items','data'])if(Array.isArray(value[key]))return value[key];return Object.values(value).filter(v=>v&&typeof v==='object'&&!Array.isArray(v));};
export default function BusinessIntelligencePage(){
 const {services,loading:authLoading,user,capabilities,isPlatformOwner,selectedBusiness,selectedBusinessId}=useAppContext();
 const [state,setState]=useState({business:null,locations:[],intelligence:[],actionLinks:[]});
 const [loading,setLoading]=useState(true);const [error,setError]=useState(null);const timer=useRef(null);const request=useRef(0);
 const load=async()=>{const id=++request.current;setLoading(true);setError(null);try{const businesses=await services.business.listBusinesses({includeDemo:isPlatformOwner});const available=Array.isArray(businesses)?businesses:businesses?.businesses||businesses?.data||[];const business=(selectedBusinessId&&available.find(b=>String(b.business_id??b.id)===String(selectedBusinessId)))||selectedBusiness||available[0]||null;if(!business){if(id===request.current)setState({business:null,locations:[],intelligence:[],actionLinks:[]});return;}const businessId=business.business_id||business.id;const [locations,intelligence,actionLinks]=await Promise.all([services.business.listLocations(businessId),services.businessIntelligence.locationIntelligence(businessId),services.businessIntelligence.actionLinks(businessId)]);if(id===request.current)setState({business,locations:rows(locations),intelligence:rows(intelligence),actionLinks:rows(actionLinks)});}catch(e){if(id===request.current)setError(e.message||'Unable to load business intelligence.')}finally{if(id===request.current)setLoading(false)}};
 const schedule=()=>{clearTimeout(timer.current);timer.current=setTimeout(load,350)};
 useEffect(()=>{if(user)void load();else if(!authLoading)setLoading(false);return()=>clearTimeout(timer.current)},[user,authLoading,isPlatformOwner,selectedBusinessId]);
 useEffect(()=>{if(!user)return undefined;const refresh=()=>schedule();window.addEventListener('kleenest:intelligence-updated',refresh);window.addEventListener('kleenest:location-activity',refresh);const unsubscribe=services.live.subscribe({onEvent:event=>{const type=String(event?.event_type||'');if(type.startsWith('location.')||type.startsWith('user.')||type.startsWith('business.')||type.startsWith('fleet.'))schedule()}});return()=>{clearTimeout(timer.current);window.removeEventListener('kleenest:intelligence-updated',refresh);window.removeEventListener('kleenest:location-activity',refresh);unsubscribe?.()}},[user,services]);
 const recommendations=useMemo(()=>rankBusinessRecommendations(buildBusinessRecommendations(state.intelligence)),[state.intelligence]);
 const linked=useMemo(()=>{const keys=new Set(recommendations.map(x=>`${x.location_id}:${x.recommendation?.type}`));return state.actionLinks.filter(x=>!keys.has(`${x.location_id}:${x.signal_type}`)).map(x=>({location_id:x.location_id,name:state.locations.find(l=>String(l?.id??l?.location_id)===String(x.location_id))?.name||'Managed location',recommendation:{type:x.signal_type,priority:x.status==='active'?'normal':'low',title:String(x.signal_type||'Intelligence action').replaceAll('_',' '),body:x.metadata?.description||'Persisted intelligence action from the network.',reasons:x.metadata?.confidence_score!=null?[`Confidence ${Math.round(Number(x.metadata.confidence_score))}`]:['Persisted intelligence action'],action_type:x.action_type}}))},[recommendations,state.actionLinks,state.locations]);
 if(authLoading||loading)return <WorkspaceShell workspace="business"><section className="empty-state" role="status"><p>Loading business intelligence…</p></section></WorkspaceShell>;
 if(!user)return <WorkspaceShell workspace="business"><section className="empty-state"><h2>Sign in to access business intelligence</h2><Link className="primary" to="/auth">Sign in</Link></section></WorkspaceShell>;
 if(!capabilities?.includes('business'))return <WorkspaceShell workspace="business"><section className="empty-state"><h2>Business access required</h2><p>This workspace is available to business accounts.</p><Link className="secondary" to="/">Return home</Link></section></WorkspaceShell>;
 if(error)return <WorkspaceShell workspace="business"><section className="empty-state" role="alert"><h2>Intelligence unavailable</h2><p>{error}</p><button className="secondary" onClick={load}><RefreshCw size={16}/>Retry</button></section></WorkspaceShell>;
 if(!state.business)return <WorkspaceShell workspace="business"><section className="empty-state"><h2>No business connected</h2><p>Connect a managed business before using intelligence actions.</p><Link className="primary" to="/business">Business dashboard</Link></section></WorkspaceShell>;
 const items=[...recommendations,...linked];
 return <WorkspaceShell workspace="business"><section className="page business-page"><div className="page-header"><div><span className="eyebrow">BUSINESS INTELLIGENCE</span><h1>{state.business.name||'Business intelligence'}</h1><p>Convert live network signals into concrete business and operational actions.</p></div><div className="hero-actions"><Link className="secondary" to="/business">Dashboard</Link><button className="secondary" onClick={load} disabled={loading}><RefreshCw size={16}/>Refresh</button></div></div><BusinessIntelligenceActions businessId={state.business.business_id||state.business.id} items={items} locations={state.locations} onComplete={load}/><section className="detail-panel business-card"><div className="panel-heading"><div><span className="eyebrow">SIGNAL RANKING</span><h2>What the network is seeing</h2></div><Sparkles size={22}/></div><div className="business-intelligence-list">{recommendations.length?recommendations.map(item=><div className="business-row" key={`${item.location_id}:${item.recommendation.type}`}><div><strong>{item.name}</strong><span>{item.recommendation.title} · {item.recommendation.body}</span><span>{item.recommendation.reasons?.join(' · ')||'Current intelligence available'}</span></div><div className="business-intelligence-score"><strong>{item.recommendation.priority.toUpperCase()}</strong><span>{item.recommendation.type.replaceAll('_',' ')}</span></div></div>):<p className="observation-copy">No actionable intelligence has accumulated yet.</p>}</div></section></section></WorkspaceShell>;
}
