import { useEffect, useState } from 'react';
import { Handshake, Plus, RefreshCw, Trash2, MapPin, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAppContext } from '../AppContext.jsx';
import WorkspaceShell from './WorkspaceShell.jsx';
import CapabilityGate from './CapabilityGate.jsx';

export default function BusinessPartnershipsPage(){
  const { services, selectedBusiness, selectedBusinessId, businessMemberships, loading: authLoading } = useAppContext();
  const memberships=Array.isArray(businessMemberships)?businessMemberships:[];
  const business=memberships.find(b=>String(b?.business_id||b?.id)===String(selectedBusinessId))||selectedBusiness||memberships[0];
  const businessId=business?.business_id||business?.id||'';
  const [programs,setPrograms]=useState([]),[locations,setLocations]=useState([]),[name,setName]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
  const load=async()=>{if(!businessId)return;setBusy('load');setError('');try{const [p,l]=await Promise.all([services.business.partners.list(),services.business.listLocations(businessId)]);setPrograms(Array.isArray(p)?p:[]);setLocations(Array.isArray(l)?l:[])}catch(e){setError(e?.message||'Unable to load partner programs.')}finally{setBusy('')}};
  useEffect(()=>{if(!authLoading&&businessId)void load()},[authLoading,businessId]);
  const create=async e=>{e.preventDefault();if(!name.trim())return;setBusy('create');setError('');try{await services.business.partners.create(businessId,name.trim());setName('');setMessage('Partner program created.');await load()}catch(e){setError(e?.message||'Unable to create partner program.')}finally{setBusy('')}};
  const toggle=async p=>{const id=p?.id||p?.partner_program_id;if(!id)return;setBusy(String(id));try{await services.business.partners.update(businessId,id,p?.name||'Partner program',!Boolean(p?.enabled));setMessage(Boolean(p?.enabled)?'Partner program disabled.':'Partner program enabled.');await load()}catch(e){setError(e?.message||'Unable to update partner program.')}finally{setBusy('')}};
  const remove=async p=>{const id=p?.id||p?.partner_program_id;if(!id)return;if(!window.confirm('Remove this partner program?'))return;setBusy(String(id));try{await services.business.partners.remove(businessId,id);setMessage('Partner program removed.');await load()}catch(e){setError(e?.message||'Unable to remove partner program.')}finally{setBusy('')}};
  const addLocation=async(p,l)=>{const pid=p?.id||p?.partner_program_id,lid=l?.id||l?.location_id;if(!pid||!lid)return;setBusy(`${pid}:${lid}`);try{await services.business.partners.addLocation(pid,lid);setMessage('Location added to partner program.');await load()}catch(e){setError(e?.message||'Unable to add location.')}finally{setBusy('')}};
  if(authLoading)return <WorkspaceShell workspace="business"><section className="empty-state"><Handshake size={30}/><h2>Loading partnerships</h2></section></WorkspaceShell>;
  if(!businessId)return <WorkspaceShell workspace="business"><section className="empty-state"><Handshake size={30}/><h2>No business selected</h2><Link className="secondary" to="/business">Business dashboard</Link></section></WorkspaceShell>;
  return <WorkspaceShell workspace="business"><main className="page"><div className="page-header"><div><span className="eyebrow">BUSINESS · PARTNERSHIPS</span><h1>Partner network</h1><p>Connect locations and customers to governed partner programs, preferred access and measurable engagement.</p></div><div className="hero-actions"><button className="secondary" onClick={load} disabled={busy==='load'}><RefreshCw size={16}/>Refresh</button><Link className="secondary" to="/business/intelligence">Intelligence</Link></div></div>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="success-copy" role="status">{message}</p>}<CapabilityGate kind="businessPartnerships" businessId={businessId} fallback={<section className="detail-panel"><h2>Partnerships require an enabled business capability</h2><p>Ask an administrator to enable the partnership capability for this business.</p></section>}><section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">CREATE</span><h2>New partner program</h2></div><Plus size={21}/></div><form className="form-actions" onSubmit={create}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Program name" maxLength={120} required/><button className="primary" disabled={busy==='create'}><Plus size={16}/>{busy==='create'?'Creating…':'Create program'}</button></form></section><section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">PROGRAMS</span><h2>Managed partner programs</h2></div><Handshake size={22}/></div>{programs.length?programs.map(p=><article className="business-row" key={p.id||p.partner_program_id}><div><strong>{p.name||'Partner program'}</strong><span>{p.description||'Governed partner access program.'} · {p.enabled?'Enabled':'Disabled'}</span></div><div className="hero-actions"><button className="secondary" onClick={()=>void toggle(p)} disabled={busy===String(p.id||p.partner_program_id)}>{p.enabled?'Disable':'Enable'}</button><button className="secondary" onClick={()=>void remove(p)} disabled={busy===String(p.id||p.partner_program_id)}><Trash2 size={15}/>Remove</button></div><div className="partner-location-actions"><Users size={15}/><span>Add a managed location:</span>{locations.slice(0,8).map(l=><button className="secondary" key={l.id||l.location_id} onClick={()=>void addLocation(p,l)} disabled={busy===`${p.id||p.partner_program_id}:${l.id||l.location_id}`}><MapPin size={14}/>{l.name||l.location_name||'Location'}</button>)}</div></article>):<div className="empty-state compact-state"><Handshake size={25}/><p>No partner programs yet. Create the first one above.</p></div>}</section></CapabilityGate></main></WorkspaceShell>;
}
