import { useEffect, useMemo, useState } from 'react';
import { Copy, ExternalLink, Plus, QrCode, RefreshCw, Trash2, ToggleLeft, ToggleRight } from 'lucide-react';
import { useAppContext } from '../AppContext.jsx';
import WorkspaceShell from './WorkspaceShell.jsx';

export default function BusinessQrStudioPage(){
  const {services,selectedBusiness}=useAppContext();
  const businessId=selectedBusiness?.business_id||selectedBusiness?.id||null;
  const [locations,setLocations]=useState([]),[codes,setCodes]=useState([]),[locationId,setLocationId]=useState(''),[label,setLabel]=useState(''),[purpose,setPurpose]=useState('Visit / engagement'),[actionType,setActionType]=useState('check_in'),[singleUse,setSingleUse]=useState(false),[maxRedemptions,setMaxRedemptions]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState('');
  const load=async()=>{if(!businessId)return;setBusy('load');setError('');try{const [ls,qs]=await Promise.all([services.business.listLocations(businessId),services.business.listQrs(businessId)]);setLocations(Array.isArray(ls)?ls:ls?.rows||[]);setCodes(Array.isArray(qs)?qs:qs?.rows||[]);}catch(e){setError(e?.message||'Unable to load business QR assets.')}finally{setBusy('')}};
  useEffect(()=>{void load()},[businessId]);
  const create=async()=>{if(!businessId||!locationId||!label.trim())return setError('Select a location and give the QR asset a label.');setBusy('create');setError('');try{await services.business.customQr.create(businessId,locationId,{label:label.trim(),purpose:purpose.trim()||'Engagement',actionType,actionPayload:{location_id:locationId},customization:{label:label.trim()},singleUse,maxRedemptions:maxRedemptions?Number(maxRedemptions):null});setLabel('');setMaxRedemptions('');await load();}catch(e){setError(e?.message||'Unable to create QR asset.')}finally{setBusy('')}};
  const toggle=async row=>{setBusy(`toggle:${row.id}`);try{await services.business.customQr.update(businessId,row.id,{label:row.label,purpose:row.purpose,actionType:row.action_type||row.actionType,actionPayload:row.action_payload||{},customization:row.customization||{},active:row.active===false,singleUse:!!row.single_use,maxRedemptions:row.max_redemptions??null});await load()}catch(e){setError(e?.message||'Unable to change QR status.')}finally{setBusy('')}};
  const remove=async row=>{if(!window.confirm(`Delete ${row.label||'this QR asset'}?`))return;setBusy(`remove:${row.id}`);try{await services.business.customQr.remove(businessId,row.id);await load()}catch(e){setError(e?.message||'Unable to delete QR asset.')}finally{setBusy('')}};
  const target=useMemo(()=>{const row=locations.find(x=>String(x.id||x.location_id)===String(locationId));return row||null},[locations,locationId]);
  const publicUrl=row=>{const code=row?.code||row?.qr_code||row?.token;return code?`${window.location.origin}${import.meta.env.BASE_URL||'/'}#/visit?locationId=${encodeURIComponent(row.location_id||locationId||'')}&qr=${encodeURIComponent(code)}`:''};
  const copy=async row=>{const url=publicUrl(row);if(!url)return;try{await navigator.clipboard.writeText(url)}catch{} };
  if(!businessId)return <WorkspaceShell workspace="business"><section className="empty-state"><QrCode size={28}/><h2>Select a business workspace</h2><p>QR Studio operates against the canonical business membership selected by the app shell.</p></section></WorkspaceShell>;
  return <WorkspaceShell workspace="business"><main className="page"><div className="page-header"><div><span className="eyebrow">BUSINESS · QR STUDIO</span><h1>Create and control QR experiences.</h1><p>Every QR asset belongs to a business location and can feed the same check-in, engagement, attribution, and analytics chain.</p></div><button className="secondary" onClick={load} disabled={busy!==''}><RefreshCw size={16}/>Refresh</button></div>{error&&<p className="form-error" role="alert">{error}</p>}
    <section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">NEW ASSET</span><h2>Create a QR experience</h2></div><Plus size={21}/></div><div className="form-grid"><label>Location<select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Select a business location</option>{locations.map(x=><option key={x.id||x.location_id} value={x.id||x.location_id}>{x.name||x.location_name||x.address||x.id}</option>)}</select></label><label>Label<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Front desk check-in"/></label><label>Purpose<input value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="Visit / engagement"/></label><label>Action<select value={actionType} onChange={e=>setActionType(e.target.value)}><option value="check_in">Check in</option><option value="engagement">Engagement</option><option value="redeem">Redeem</option><option value="campaign">Campaign</option><option value="custom">Custom</option></select></label><label>Max redemptions<input type="number" min="1" value={maxRedemptions} onChange={e=>setMaxRedemptions(e.target.value)} placeholder="Unlimited"/></label><label className="checkbox-row"><input type="checkbox" checked={singleUse} onChange={e=>setSingleUse(e.target.checked)}/> Single-use QR</label></div>{target&&<p className="muted">Linked location: {target.name||target.address||target.id}</p>}<button className="primary" disabled={busy!==''||!locationId||!label.trim()} onClick={create}><QrCode size={16}/>{busy==='create'?'Creating…':'Create QR asset'}</button></section>
    <section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">QR ASSETS</span><h2>Live business codes</h2></div><QrCode size={21}/></div>{busy==='load'?<p>Loading QR assets…</p>:codes.length?codes.map(row=>{const url=publicUrl(row);return <div className="business-row" key={row.id}><div><strong>{row.label||row.name||'QR asset'}</strong><span>{row.purpose||row.action_type||'Engagement'} · {row.active===false?'Inactive':'Active'}</span><small>{row.location_name||row.location_id||'Location linked'}{row.single_use?' · Single use':''}{row.max_redemptions?` · Max ${row.max_redemptions}`:''}</small></div><div className="hero-actions"><button className="secondary compact" disabled={busy!==''} onClick={()=>toggle(row)}>{row.active===false?<><ToggleLeft size={15}/>Activate</>:<><ToggleRight size={15}/>Deactivate</>}</button>{url&&<button className="secondary compact" onClick={()=>copy(row)}><Copy size={15}/>Copy link</button>}{url&&<a className="secondary compact" href={url} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Test</a>}<button className="secondary compact" disabled={busy!==''} onClick={()=>remove(row)}><Trash2 size={15}/>Delete</button></div></div>}):<p>No QR assets yet. Create the first one above.</p>}</section>
  </main></WorkspaceShell>;
}
