import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, MapPin, Route, ShieldCheck, Trophy, QrCode, Radio, Building2, BarChart3, Truck, Globe2, Bell, Settings, Search, AlertTriangle, Database, Server } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAppContext } from '../AppContext.jsx';
import { getCapabilitiesForWorkspace, getCapabilityRegistry, auditCapabilitySurface } from '../architecture/capabilityContract.js';
import WorkspaceShell from './WorkspaceShell.jsx';
import './CapabilityHubPage.css';

const CAPABILITY_ROUTES={identity:'/profile',locations:'/map',discovery:'/map',maps:'/map',checkins:'/activity',reviews:'/evidence',evidence:'/evidence',qr:'/engage',geofencing:'/engagement/orchestrate',progression:'/play',quests:'/play/quest',rewards:'/rewards',reputation:'/profile',leaderboards:'/leaderboards',business:'/business',businessLifecycle:'/business',access:'/access',monetization:'/pricing',fleet:'/fleet',enterprise:'/enterprise',social:'/community',family:'/family',notifications:'/notifications',analytics:'/intelligence',liveNetwork:'/intelligence',intelligence:'/intelligence',reporting:'/owner/reports',externalData:'/admin',offline:'/route',support:'/support',admin:'/admin'};
const ICONS={identity:ShieldCheck,locations:MapPin,discovery:Search,maps:MapPin,checkins:ShieldCheck,reviews:ShieldCheck,evidence:ShieldCheck,qr:QrCode,geofencing:Radio,progression:Trophy,quests:Trophy,rewards:Trophy,reputation:ShieldCheck,leaderboards:Trophy,business:Building2,businessLifecycle:Building2,access:ShieldCheck,monetization:BarChart3,fleet:Truck,enterprise:Globe2,social:Globe2,family:ShieldCheck,notifications:Bell,analytics:BarChart3,liveNetwork:Radio,intelligence:BarChart3,reporting:BarChart3,externalData:Database,offline:Route,support:Bell,admin:Settings};
const LABELS={businessLifecycle:'Business lifecycle',liveNetwork:'Live network',externalData:'External data'};
function normalizeWorkspace(value){const raw=String(value||'').toLowerCase();return ['consumer','profile','community','play','business','fleet','enterprise','admin','owner'].includes(raw)?raw:'consumer';}
export default function CapabilityHubPage(){
 const{capabilityRegistry,workspaceCapabilities,membershipTier,configured,services,activeWorkspace}=useAppContext();
 const[query,setQuery]=useState('');const[catalog,setCatalog]=useState([]),[contracts,setContracts]=useState([]);
 const registry=capabilityRegistry&&Object.keys(capabilityRegistry).length?capabilityRegistry:getCapabilityRegistry();
 const workspace=normalizeWorkspace(activeWorkspace||membershipTier);
 useEffect(()=>{let active=true;if(!configured||!services?.capabilityCoverage)return undefined;Promise.all([services.capabilityCoverage.list(),services.capabilityCoverage.catalog(),services.capabilityCoverage.contracts()]).then(([coverage,cat,contractRows])=>{if(!active)return;setCatalog(Array.isArray(cat)?cat:Array.isArray(coverage)?coverage:[]);setContracts(Array.isArray(contractRows)?contractRows:[])}).catch(()=>{if(active){setCatalog([]);setContracts([])}});return()=>{active=false};},[configured,services]);
 const visibleIds=useMemo(()=>new Set((workspaceCapabilities||[]).map(v=>typeof v==='string'?v:v?.code||v?.feature_code||v?.key).filter(Boolean)),[workspaceCapabilities]);
 const capabilities=useMemo(()=>getCapabilitiesForWorkspace(workspace).map(key=>({key,...(registry[key]||{})})).filter(item=>{const q=query.trim().toLowerCase();return !q||`${item.key} ${LABELS[item.key]||item.key} ${(item.facts||[]).join(' ')} ${(item.services||[]).join(' ')} ${item.flow||''}`.toLowerCase().includes(q)}).filter(item=>workspace==='owner'||workspace==='admin'||visibleIds.size===0||visibleIds.has(item.key)||!catalog.length||!catalog.find(v=>v?.feature_code===item.key)||catalog.find(v=>v?.feature_code===item.key)?.enabled!==false),[registry,workspace,visibleIds,catalog,query]);
 const runtimeAudit=useMemo(()=>auditCapabilitySurface({workspace,services:services||{},visibleCapabilities:workspaceCapabilities||[],catalog}),[workspace,services,workspaceCapabilities,catalog]);
 const supabaseFiltered=contracts.filter(c=>{const q=query.trim().toLowerCase();return !q||`${c.domain} ${c.canonical_capability} ${c.canonical_rpc} ${c.owner_surface}`.toLowerCase().includes(q)});
 const gapCount=runtimeAudit.missingServices.length+runtimeAudit.hidden.length+runtimeAudit.disabled.length;
 return <WorkspaceShell workspace={workspace}><main className="page capability-hub">
  <div className="page-header"><div><span className="eyebrow">KLEENEST PLATFORM</span><h1>Everything Kleenest can do.</h1><p>The capability registry is the product authority; live Supabase contracts and the feature catalog provide the current implementation state.</p></div><div className="hero-actions"><span className="membership-badge">Workspace · {workspace}</span><Link className="button secondary" to="/integration">Integration health <ArrowRight size={15}/></Link></div></div>
  <section className="detail-panel capability-runtime"><div><span className="eyebrow">LIVE CAPABILITY STATUS</span><h2>{configured?`Connected · ${workspace}`:'Connection needs attention'}</h2><p>{configured?'This surface is derived from the canonical registry and reconciled against current runtime services, workspace exposure, and the live feature catalog.':'Supabase is not currently configured for this runtime.'}</p></div><div className="runtime-stats"><div><strong>{capabilities.length}</strong><span>workspace capabilities</span></div><div><strong>{contracts.length}</strong><span>live Supabase contracts</span></div><div><strong>{catalog.length}</strong><span>catalog features</span></div><div><strong>{runtimeAudit.complete}</strong><span>fully reconciled</span></div></div></section>
  <section className="detail-panel capability-runtime"><div><span className="eyebrow"><Server size={14}/> CONTRACT AUDIT</span><h2>{gapCount?`${gapCount} reconciliation gap${gapCount===1?'':'s'}`:'Capability contract reconciled'}</h2><p>{gapCount?`${runtimeAudit.missingServices.length} missing runtime service coverage; ${runtimeAudit.hidden.length} hidden from this workspace; ${runtimeAudit.disabled.length} disabled in the live catalog.`:'The canonical registry, runtime services, workspace exposure, and live catalog agree for the audited surface.'}</p></div></section>
  <section className="detail-panel capability-search"><Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search capabilities, facts, services, Supabase RPCs, or domains…" aria-label="Search capabilities"/></section>
  <section className="capability-section"><div className="section-heading"><div><span className="eyebrow"><ShieldCheck size={14}/> CANONICAL CAPABILITY REGISTRY</span><h2>{workspace} capabilities</h2><p>These cards come from the canonical registry instead of a separately maintained static pathway list.</p></div><span className="tag">{capabilities.length} capabilities</span></div><div className="capability-grid">
   {capabilities.map(item=>{const Icon=ICONS[item.key]||Settings;const href=CAPABILITY_ROUTES[item.key]||'/integration';const contract=contracts.find(row=>row.canonical_capability===item.key||row.domain===item.key);const status=runtimeAudit.rows.find(row=>row.capability===item.key)?.status||'registry-defined';return <Link className="capability-card" to={href} key={item.key}><span className="capability-card-icon"><Icon size={20}/></span><span><strong>{LABELS[item.key]||item.key.replace(/([A-Z])/g,' $1').replace(/^./,v=>v.toUpperCase())}</strong><em>{item.flow||`${(item.services||[]).length} runtime service${(item.services||[]).length===1?'':'s'} · ${(item.facts||[]).length} canonical facts`}{contract?` · RPC: ${contract.canonical_rpc}`:''}</em></span><span className="tag">{status.replaceAll('-',' ').toUpperCase()}</span></Link>})}
   {!capabilities.length&&<div className="capability-card passive"><span className="capability-card-icon"><AlertTriangle size={19}/></span><span><strong>No matching capabilities</strong><em>Try a different search or workspace.</em></span></div>}
  </div></section>
  <section className="capability-section"><div className="section-heading"><div><span className="eyebrow"><Server size={14}/> LIVE SUPABASE CONTRACTS</span><h2>Authoritative backend capabilities</h2><p>Only active rows from the live capability-domain contract table are shown.</p></div><span className="tag">{supabaseFiltered.length} active contracts</span></div><div className="capability-grid">{supabaseFiltered.length?supabaseFiltered.map(item=><div className="capability-card passive" key={`${item.domain}:${item.canonical_rpc}`}><span className="capability-card-icon"><Database size={19}/></span><span><strong>{item.canonical_capability}</strong><em>{item.domain} · RPC: {item.canonical_rpc} · surface: {item.owner_surface}</em></span><span className="tag">ACTIVE</span></div>):<div className="capability-card passive"><span className="capability-card-icon"><Database size={19}/></span><span><strong>No matching Supabase contracts</strong><em>Try a different capability, RPC, or domain.</em></span></div>}</div></section>
  <section className="capability-section"><div className="section-heading"><div><span className="eyebrow">LIVE FEATURE CATALOG</span><h2>Current entitlement surface</h2></div><span className="tag">{catalog.length} features</span></div><div className="capability-grid">{catalog.filter(item=>{const q=query.trim().toLowerCase();return !q||`${item.feature_code} ${item.name} ${item.category} ${item.minimum_tier}`.toLowerCase().includes(q)}).map(item=><div className="capability-card passive" key={item.feature_code}><span className="capability-card-icon">{item.enabled?<ShieldCheck size={19}/>:<AlertTriangle size={19}/>}</span><span><strong>{item.name}</strong><em>{item.feature_code} · {item.category} · minimum tier: {item.minimum_tier}</em></span><span className="tag">{item.enabled?'ENABLED':'DISABLED'}</span></div>)}</div></section>
  <footer className="home-footer"><span>Capability status is read from the canonical registry plus live Supabase contracts and catalog data; this page no longer maintains an independent static capability inventory.</span><Link className="text-link" to="/pricing">Membership details <ArrowRight size={14}/></Link></footer>
 </main></WorkspaceShell>;
}
