import {useState} from 'react';
import {CheckCircle2,MapPin,QrCode,Star,Trophy} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useAppContext} from '../AppContext.jsx';
import WorkspaceShell from './WorkspaceShell.jsx';

function Result({result}){if(!result)return null;const entries=Array.isArray(result)?result:[result];return <div className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">RESULT</span><h2>Visit recorded</h2></div></div><div className="detail-grid">{entries.slice(0,8).map((item,i)=><div className="metric-card" key={i}><strong>{typeof item==='object'?item.name||item.title||item.status||`Result ${i+1}`:String(item)}</strong>{typeof item==='object'&&<span>{item.message||item.description||item.id||'Action completed'}</span>}</div>)}</div></div>}
export default function ConsumerActionCenter({locationId='',placeId='',qrToken=''}){
 const {services}=useAppContext(); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [result,setResult]=useState(null); const [rating,setRating]=useState(5); const [comment,setComment]=useState(''); const target=placeId||locationId;
 async function run(action){setBusy(true);setError('');try{setResult(await action())}catch(e){setError(e?.message||String(e))}finally{setBusy(false)}}
 return <WorkspaceShell><section className="page"><div className="page-header"><div><span className="eyebrow">VISIT CENTER</span><h1>Turn a visit into value</h1><p>Verify the place, contribute trusted information, and carry the result into reviews and progression.</p></div><div className="hero-actions"><Link className="secondary" to="/map"><MapPin size={16}/> Discover</Link><Link className="secondary" to="/play"><Trophy size={16}/> Progression</Link></div></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="detail-grid"><div className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">VERIFY</span><h2>Check in</h2></div><QrCode size={22}/></div><p>Use the venue QR or canonical place identity to establish a verified visit.</p><div className="hero-actions"><button className="primary" disabled={busy||!placeId||!qrToken} onClick={()=>run(()=>services.checkins.byQr({placeId,qrToken}))}><QrCode size={16}/> {busy?'Working…':'Check in with QR'}</button><button className="secondary" disabled={busy||!qrToken} onClick={()=>run(()=>services.qr.redeem(qrToken))}>Redeem QR</button></div></div><div className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">TRUST</span><h2>Inspect the location</h2></div><CheckCircle2 size={22}/></div><p>Report cleanliness, availability, safety, amenities, and other current signals.</p><div className="hero-actions"><Link className="secondary" to={`/evidence${target?`?locationId=${encodeURIComponent(target)}`:''}`}>Open evidence</Link><button className="secondary" disabled={busy||!locationId} onClick={()=>run(()=>services.locationEvidence.bathroomStatus(locationId))}>Bathroom status</button></div></div></div><div className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">REPUTATION</span><h2>Leave a verified review</h2></div><Star size={22}/></div><div className="form-grid"><label>Rating<select value={rating} onChange={e=>setRating(Number(e.target.value))}><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select></label><label>Comment<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="What should the next visitor know?"/></label></div><button className="primary" disabled={busy||!locationId||!comment.trim()} onClick={()=>run(()=>services.reviews.create({locationId,stars:rating,comment}))}>Submit review</button></div><Result result={result}/></section></WorkspaceShell>
}
