import { useEffect,useMemo,useState } from 'react';
import { Activity,Building2,MapPinned,RefreshCw,ShieldCheck,Users,Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAppContext } from '../AppContext.jsx';
import WorkspaceShell from './WorkspaceShell.jsx';
const arr=v=>Array.isArray(v)?v:[];
export default function EnterpriseCommandCenterPage(){
 const{services,businessMemberships,isPlatformOwner}=useAppContext();
 const[rows,setRows]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const businesses=arr(businessMemberships.length?businessMemberships:await services.business.listBusinesses({includeDemo:isPlatformOwner}));const source=businesses.filter(b=>String(b.business_tier||b.plan||b.plan_key||b.subscription_plan||'').toLowerCase()==='enterprise'||b.is_enterprise);const list=source.length?source:businesses;const next=await Promise.all(list.slice(0,25).map(async b=>{const id=b.business_id||b.id;const [locations,analytics,reviews,intelligence,partners,qr]=await Promise.allSettled([services.business.listLocations(id),services.business.analytics(id),services.business.reviewAnalytics(id),services.businessIntelligence.locationIntelligence(id),services.partners.preferredAnalytics(id),services.business.qrAnalytics(id)]);return{business:b,locations:arr(locations.value),analytics:analytics.value||{},reviews:reviews.value||{},signals:arr(intelligence.value),partners:partners.value||{},qr:qr.value||{}}}));setRows(next)}catch(e){setError(e.message||'Unable to load enterprise command center.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[businessMemberships.length,isPlatformOwner]);
 const totals=useMemo(()=>rows.reduce((s,r)=>{s.locations+=r.locations.length;s.checkins+=Number(r.analytics.check_ins||r.analytics.total_check_ins||0);s.reviews+=Number(r.reviews.total_reviews||r.reviews.review_count||0);s.signals+=r.signals.length;s.qrScans+=Number(r.qr.total_scans||r.qr.scans||r.qr.redemptions||0);return s},{locations:0,checkins:0,reviews:0,signals:0,qrScans:0}),[rows]);
 if(loading)return <WorkspaceShell workspace="enterprise"><section className="empty-state">Loading enterprise command center…</section></WorkspaceShell>;
 if(error)return <WorkspaceShell workspace="enterprise"><section className="empty-state" role="alert"><h2>Command center unavailable</h2><p>{error}</p><button className="secondary" onClick={load}><RefreshCw size={16}/>Retry</button></section></WorkspaceShell>;
 return <WorkspaceShell workspace="enterprise"><section className="page enterprise-page"><div className="page-header"><div><span className="eyebrow">KLEENEST ENTERPRISE</span><h1>Command center</h1><p>One operational view across managed organizations, locations, activity, QR engagement, reputation, partners, and intelligence.</p></div><div className="hero-actions"><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh network</button><Link className="primary" to="/map"><MapPinned size={17}/>Open network map</Link></div></div><section className="reward-stats"><div className="reward-stat"><Building2 size={20}/><strong>{rows.length}</strong><span>organizations</span></div><div className="reward-stat"><MapPinned size={20}/><strong>{totals.locations}</strong><span>locations</span></div><div className="reward-stat"><Users size={20}/><strong>{totals.checkins}</strong><span>check-ins</span></div><div className="reward-stat"><Activity size={20}/><strong>{totals.reviews}</strong><span>reviews</span></div><div className="reward-stat"><Zap size={20}/><strong>{totals.signals}</strong><span>signals</span></div><div className="reward-stat"><Zap size={20}/><strong>{totals.qrScans}</strong><span>QR activity</span></div></section><section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">PORTFOLIO</span><h2>Managed organizations</h2></div><ShieldCheck size={22}/></div>{rows.length?rows.map(row=>{const id=row.business.business_id||row.business.id;return <article className="business-row" key={id}><div><strong>{row.business.name||'Managed organization'}</strong><span>{row.business.city||row.business.address||'Enterprise network member'}</span><span>{row.locations.length} locations · {row.signals.length} intelligence signals · {row.partners?.preferred_uses??row.partners?.uses??0} preferred uses · {row.qr?.total_scans??row.qr?.scans??row.qr?.redemptions??0} QR activity</span></div><div className="hero-actions"><Link className="secondary" to={`/business?business=${encodeURIComponent(id)}`}>Business</Link><Link className="secondary" to="/business/intelligence"><Zap size={15}/>Intelligence</Link><Link className="secondary" to="/business/engagement"><Zap size={15}/>QR Engagement</Link><Link className="secondary" to="/fleet"><Activity size={15}/>Fleet</Link></div></article>}) : <div className="empty-state"><h3>No managed organizations found</h3><p>Connect an enterprise-enabled business to populate this portfolio.</p></div>}</section><section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">NETWORK PARTNERS</span><h2>Partner programs</h2></div></div><div className="hero-actions"><Link className="primary" to="/enterprise/partners">Open partner network</Link><Link className="secondary" to="/enterprise/campaigns">Manage campaigns</Link><Link className="secondary" to="/enterprise/performance">Network performance</Link></div></section></section></WorkspaceShell>;
}