import { useEffect, useState } from 'react';
import { Lock, Route as RouteIcon, UserRound, Truck } from 'lucide-react';
import { useAppContext } from '../AppContext.jsx';
import WorkspaceShell from './WorkspaceShell.jsx';
import FleetRouteCrudPanel from './FleetRouteCrudPanel.jsx';
import FleetOperationalSignalsPanel from './FleetOperationalSignalsPanel.jsx';
import FleetExceptionIntelligencePanel from './FleetExceptionIntelligencePanel.jsx';
import FleetAssetExceptionScorecardsPanel from './FleetAssetExceptionScorecardsPanel.jsx';
import FleetRouteExceptionDrilldownPanel from './FleetRouteExceptionDrilldownPanel.jsx';
import FleetExceptionTrendsPanel from './FleetExceptionTrendsPanel.jsx';
import { fleetAccessState } from '../domains/fleet/access.js';
const arr=value=>Array.isArray(value)?value:[];const idOf=value=>value?.id||value?.route_id||'';const labelOf=value=>value?.name||value?.title||value?.display_name||value?.unit_code||idOf(value)||'Unnamed';
function ReadOnlyRoutes({services,businessId}){const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let active=true;setLoading(true);services.fleet.currentUserDispatch(businessId||null).then(value=>{if(active)setData(value)}).catch(e=>{if(active)setError(e.message||'Unable to load your assigned Fleet routes.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[services,businessId]);const routes=arr(data?.routes),vehicle=data?.vehicle,driver=data?.driver;return <section className="detail-panel business-card fleet-route-readonly"><div className="panel-heading"><div><span className="eyebrow">FLEET DISPATCH · MY ROUTES</span><h2>Routes & assignments</h2><p className="muted"><Lock size={14}/> Driver view is self-scoped. Route creation, assignment, reordering, and dispatch controls are available only to Fleet controllers.</p></div><RouteIcon size={22}/></div>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<p className="muted">Loading your dispatch…</p>:!driver?<p className="muted">This Fleet account has not yet been linked to a driver record.</p>:<><div className="detail-grid"><div><span>Driver</span><strong>{labelOf(driver)}</strong></div><div><span>Vehicle</span><strong>{vehicle?labelOf(vehicle):'Unassigned'}</strong></div></div>{routes.length?routes.map(route=><article className="business-row crud-record-row" key={idOf(route)}><div className="crud-record-main"><strong>{labelOf(route)}</strong><span>{route.status||'planned'} · {route.distance_miles??'—'} mi · {route.stops_count??arr(route.stops).length} stops</span><span><Truck size={13}/> {vehicle?labelOf(vehicle):'Vehicle unassigned'} · <UserRound size={13}/> {labelOf(driver)}</span>{arr(route.stops).map(stop=><small key={stop.id}>#{stop.stop_order} · {stop.metadata?.display_name||'Assigned stop'} · {stop.status||'pending'}</small>)}</div></article>):<p className="muted">No routes are currently assigned to you.</p>}</>}</section>}
export default function FleetRoutesPage(){const{services,selectedBusinessId,selectedBusiness,isPlatformOwner,profile}=useAppContext();const businessId=selectedBusinessId||selectedBusiness?.business_id||selectedBusiness?.id||'',role=profile?.role||profile?.business_role||profile?.membership_role||'',tier=profile?.business_tier||profile?.tier||'',access=fleetAccessState({isPlatformOwner,role,businessTier:tier});if(!businessId&&!access.observe)return <WorkspaceShell workspace="fleet"><section className="empty-state"><RouteIcon size={36}/><h2>No Fleet access</h2><p>{isPlatformOwner?'Select an owner/demo Fleet business to manage routes.':'A Fleet membership is required to access routes.'}</p></section></WorkspaceShell>;return <WorkspaceShell workspace="fleet"><section className="page business-page"><section className="page-header"><div><span className="eyebrow">FLEET · ROUTE DISPATCH</span><h1>{access.operate?'Routes':'My routes'}</h1><p>{access.operate?'Create and manage operational routes, use map discovery to fill stops, assign drivers and vehicles, schedule work, and control route status from one workspace.':'Review the vehicle, route sequence, stops, schedule, and status assigned to your driver account.'}</p></div></section>{access.operate&&<><FleetOperationalSignalsPanel businessId={businessId}/><FleetExceptionIntelligencePanel businessId={businessId} canManage/><FleetExceptionTrendsPanel businessId={businessId}/><FleetAssetExceptionScorecardsPanel businessId={businessId}/><FleetRouteExceptionDrilldownPanel businessId={businessId}/><FleetRouteCrudPanel businessId={businessId}/></>}{!access.operate&&access.observe&&<ReadOnlyRoutes services={services} businessId={businessId||null}/>} {!access.observe&&<section className="empty-state"><Lock size={36}/><h2>Fleet route access unavailable</h2><p>This account does not currently have Fleet route access.</p></section>}</section></WorkspaceShell>}
