import { useEffect, useState } from 'react';
import { Gauge, Save } from 'lucide-react';
import { useAppContext } from '../AppContext.jsx';

const defaults={occupancyEnabled:true,occupancyFreshMinutes:30,highUtilizationPct:80,queueThreshold:1,highUtilizationWeight:15,queueWeight:10};
const fromPolicy=p=>({occupancyEnabled:p?.occupancy_enabled??true,occupancyFreshMinutes:p?.occupancy_fresh_minutes??30,highUtilizationPct:p?.high_utilization_pct??80,queueThreshold:p?.queue_threshold??1,highUtilizationWeight:p?.high_utilization_weight??15,queueWeight:p?.queue_weight??10});
export default function FleetDispatchSignalPolicyPanel({businessId,onSaved}){
 const{services}=useAppContext();
 const[form,setForm]=useState(defaults),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let alive=true;if(!businessId)return()=>{alive=false};services.fleet.dispatchSignalPolicy(businessId).then(p=>{if(alive)setForm(fromPolicy(p))}).catch(e=>{if(alive)setError(e?.message||'Unable to load dispatch signal policy.')});return()=>{alive=false}},[businessId,services]);
 const set=(key,value)=>setForm(v=>({...v,[key]:value}));
 const save=async()=>{setBusy(true);setError('');setMessage('');try{const policy=await services.fleet.updateDispatchSignalPolicy(businessId,form);setForm(fromPolicy(policy));setMessage('Dispatch signal policy saved.');onSaved?.(policy)}catch(e){setError(e?.message||'Unable to save dispatch signal policy.')}finally{setBusy(false)}};
 return <section className="detail-panel fleet-dispatch-policy"><div className="panel-heading"><div><span className="eyebrow">DISPATCH SIGNAL POLICY</span><h4>Occupancy-aware ranking</h4><p className="muted">Current occupancy only affects recommendations while it is fresh, and only through these visible thresholds and weights.</p></div><Gauge size={19}/></div>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success" role="status">{message}</p>}<label className="inline-control"><input type="checkbox" checked={form.occupancyEnabled} onChange={e=>set('occupancyEnabled',e.target.checked)}/><span>Use fresh occupancy signals in stop ranking</span></label><div className="form-row"><label className="form-field"><span>Fresh for (minutes)</span><input type="number" min="5" max="240" value={form.occupancyFreshMinutes} onChange={e=>set('occupancyFreshMinutes',e.target.value)}/></label><label className="form-field"><span>High utilization threshold (%)</span><input type="number" min="0" max="100" value={form.highUtilizationPct} onChange={e=>set('highUtilizationPct',e.target.value)}/></label><label className="form-field"><span>Queue threshold (people)</span><input type="number" min="0" max="10000" value={form.queueThreshold} onChange={e=>set('queueThreshold',e.target.value)}/></label></div><div className="form-row"><label className="form-field"><span>Utilization priority weight</span><input type="number" min="0" max="100" value={form.highUtilizationWeight} onChange={e=>set('highUtilizationWeight',e.target.value)}/></label><label className="form-field"><span>Queue priority weight</span><input type="number" min="0" max="100" value={form.queueWeight} onChange={e=>set('queueWeight',e.target.value)}/></label></div><div className="hero-actions"><button className="button secondary" type="button" onClick={save} disabled={busy}><Save size={14}/>{busy?'Saving…':'Save signal policy'}</button></div></section>;
}
