import { useEffect,useState } from 'react';
import { BarChart3, RefreshCw, Trophy } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAppContext } from '../AppContext.jsx';
import WorkspaceShell from './WorkspaceShell.jsx';
const arr=v=>Array.isArray(v)?v:[];
const obj=v=>v&&typeof v==='object'?v:{};
const idOf=v=>v?.id||v?.metric_definition_id||v?.target_id;
const labelOf=v=>v?.name||v?.metric_name||v?.metric_key||v?.target_name||v?.display_name||idOf(v)||'Metric';
export default function FleetPerformancePage(){
 const {services}=useAppContext();
 const [businesses,setBusinesses]=useState([]),[businessId,setBusinessId]=useState(''),[values,setValues]=useState([]),[config,setConfig]=useState([]),[leaders,setLeaders]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const loadBusinesses=async()=>{try{const rows=await services.business.listBusinesses();const next=arr(rows);setBusinesses(next);if(!businessId&&next[0])setBusinessId(String(next[0]?.business_id||next[0]?.id));}catch(e){setError(e.message||'Unable to load business access.')}finally{setLoading(false)}};
 const load=async()=>{if(!businessId)return;setLoading(true);setError('');try{const [c,v,l]=await Promise.all([services.fleetMetrics.configuration(businessId),services.fleetMetrics.values(businessId),services.fleet.leaderboard(businessId)]);setConfig(arr(c));setValues(arr(v));setLeaders(arr(l));}catch(e){setError(e.message||'Unable to load Fleet performance.')}finally{setLoading(false)}};
 useEffect(()=>{void loadBusinesses()},[]); useEffect(()=>{if(businessId)void load()},[businessId]);
 return <WorkspaceShell workspace="fleet"><section className="page business-page"><div className="page-header"><div><span className="eyebrow">FLEET · PERFORMANCE</span><h1>Fleet performance</h1><p>Configured metrics, current values, and driver performance from the canonical Fleet metric contracts.</p></div><div className="hero-actions"><button className="secondary" onClick={load} disabled={loading}><RefreshCw size={16}/>Refresh</button><Link className="secondary" to="/fleet">Operations</Link><Link className="secondary" to="/fleet/intelligence">Intelligence</Link></div></div><section className="detail-panel"><label className="form-field"><span>Business</span><select value={businessId} onChange={e=>setBusinessId(e.target.value)}>{businesses.map(b=>{const id=b?.business_id||b?.id;return <option key={id} value={id}>{b?.name||b?.business_name||id}</option>})}</select></label></section>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<div className="empty-state">Loading Fleet performance…</div>:<><section className="reward-stats"><div className="reward-stat"><BarChart3 size={20}/><strong>{config.length}</strong><span>configured metrics</span></div><div className="reward-stat"><strong>{values.length}</strong><span>current values</span></div><div className="reward-stat"><Trophy size={20}/><strong>{leaders.length}</strong><span>ranked drivers</span></div></section><section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">METRICS</span><h2>Current performance</h2></div></div>{values.length?values.map(v=><div className="business-row" key={idOf(v)||JSON.stringify(v)}><div><strong>{labelOf(v)}</strong><span>{v.value ?? v.current_value ?? v.score ?? '—'} {v.unit||''}</span></div><span className="muted">Goal: {v.goal ?? v.target ?? '—'}</span></div>):<p className="muted">No Fleet metric values are currently available.</p>}</section><section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">LEADERBOARD</span><h2>Driver performance</h2></div><Trophy size={22}/></div>{leaders.length?leaders.map((v,i)=><div className="business-row" key={idOf(v)||i}><div><strong>#{v.rank||i+1} {v.name||v.target_name||v.driver_name||'Driver'}</strong><span>{v.metric||v.metric_name||'safety_score'}</span></div><strong>{v.score ?? v.value ?? v.metric_value ?? '—'}</strong></div>):<p className="muted">No driver leaderboard data is currently available.</p>}</section><section className="detail-panel"><div className="panel-heading"><h2>Metric configuration</h2></div>{config.length?config.map(c=><div className="business-row" key={idOf(c)||JSON.stringify(c)}><div><strong>{labelOf(c)}</strong><span>{c.description||c.period||'Configured Fleet metric'}</span></div><span className="muted">Goal: {c.goal ?? '—'} · Max: {c.max_score ?? '—'}</span></div>):<p className="muted">No metric configuration returned.</p>}</section></>}</section></WorkspaceShell>;
}
