import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Brain,Clock3,Gamepad2,RotateCcw,Trophy,Zap,Grid3X3,Target,Shuffle,Users,Send,CheckCircle2,ShieldCheck,Star} from 'lucide-react';
import {Link} from 'react-router-dom';
import WorkspaceShell from './WorkspaceShell.jsx';
import {useAppContext} from '../AppContext.jsx';
import './GamesPage.css';

const GAMES=[
{id:'clean_sweep',title:'Clean Sweep',tag:'Quick tap',icon:Zap,mechanic:'tap',description:'Sweep for the strongest cleanliness evidence.'},
{id:'bathroom_memory',title:'Bathroom Memory',tag:'Match pairs',icon:Brain,mechanic:'memory',description:'Match restroom amenities and evidence signals.'},
{id:'trust_or_bust',title:'Trust or Bust',tag:'Trust quiz',icon:ShieldCheck,mechanic:'quiz',description:'Separate verified restroom evidence from weak signals.'},
{id:'flush_the_facts',title:'Flush the Facts',tag:'Rapid fire',icon:Target,mechanic:'quiz',description:'Make fast decisions about useful bathroom reviews.'},
{id:'restroom_relay',title:'Restroom Relay',tag:'Evidence relay',icon:Star,mechanic:'quiz',description:'Race through cleanliness, accessibility, and amenity decisions.'},
{id:'stall_strategy',title:'Stall Strategy',tag:'Evidence strategy',icon:Grid3X3,mechanic:'grid',description:'Build the strongest evidence path before the clock wins.'},
{id:'sink_sprint',title:'Sink Sprint',tag:'Amenity sprint',icon:Zap,mechanic:'tap',description:'Spot soap, drying, sink, and accessibility signals at speed.'},
{id:'route_to_relief',title:'Route to Relief',tag:'Route puzzle',icon:Target,mechanic:'quiz',description:'Choose the most trustworthy restroom stop on a route.'},
{id:'review_rater',title:'Review Rater',tag:'Review quality',icon:Trophy,mechanic:'quiz',description:'Rank the evidence a traveler actually needs.'},
{id:'evidence_detective',title:'Evidence Detective',tag:'Find the clue',icon:ShieldCheck,mechanic:'quiz',description:'Spot the clues that make a restroom rating trustworthy.'},
{id:'amenity_architect',title:'Amenity Architect',tag:'Build the profile',icon:Grid3X3,mechanic:'memory',description:'Assemble the most complete restroom profile from facts.'},
{id:'cleanliness_clash',title:'Cleanliness Clash',tag:'Head-to-head',icon:Users,mechanic:'quiz',description:'Challenge a follower or friend to identify the stronger evidence set.'}
];
const SYMBOLS=['WC','SOAP','SINK','DRY','ADA','BABY'];
const WORDS=['RESTROOM','KLEENEST','CHECKIN','CLEAN','TRUST','FRESH','AMENITY','EVIDENCE'];
const QUESTIONS=[
['Which signal is strongest for a trustworthy restroom review?',['Verified check-in plus useful observation','A random rating with no visit','A copied description'],0],
['Which detail helps the next visitor most?',['Specific cleanliness and amenity facts','Only a star number','Only a joke'],0],
['What makes a review more useful over time?',['Recent, visit-linked evidence','An old unsupported claim','No location context'],0],
['Which restroom fact is most actionable?',['Soap unavailable at the sink','It felt weird','Nice place'],0],
['What should a trust-focused game reward?',['Accurate evidence and useful contribution','Spammy ratings','Repeated taps with no context'],0],
['What is the best accessibility signal?',['Observed accessible entrance/fixture details','A guess from the building name','No information'],0],
['Which combination is strongest?',['Check-in + observation + review','Review only','Photo caption only'],0],
['What should a route recommendation prioritize?',['Trustworthy nearby evidence and usable amenities','Popularity alone','Random selection'],0]
];
const shuffle=a=>[...a].sort(()=>Math.random()-.5);

export default function GamesPage(){
 const{services,user}=useAppContext();
 const authenticated=Boolean(user);
 const[active,setActive]=useState(null),[score,setScore]=useState(0),[round,setRound]=useState(0),[message,setMessage]=useState('Pick a game.'),[targets,setTargets]=useState([]),[matched,setMatched]=useState([]),[choice,setChoice]=useState([]),[questionIndex,setQuestionIndex]=useState(0),[grid,setGrid]=useState([]),[gridGuess,setGridGuess]=useState([]),[gridSolution,setGridSolution]=useState([]),[saved,setSaved]=useState(false),[startedAt,setStartedAt]=useState(0),[gameChallenges,setGameChallenges]=useState([]),[gameTargets,setGameTargets]=useState([]),[opponent,setOpponent]=useState(''),[challengeGame,setChallengeGame]=useState('cleanliness_clash'),[challengeBusy,setChallengeBusy]=useState(false),[challengeMessage,setChallengeMessage]=useState('');
 const tapTargets=useMemo(()=>shuffle(Array.from({length:12},(_,i)=>i)).slice(0,5),[active]);
 const currentGame=GAMES.find(g=>g.id===active);
 const currentQuestion=QUESTIONS[questionIndex%QUESTIONS.length];
 const refreshChallenges=async()=>{if(!authenticated)return;try{const[cs,ts]=await Promise.all([services.progression.gameChallenges(),services.progression.gameTargets()]);setGameChallenges(cs??[]);setGameTargets(ts??[])}catch(e){setChallengeMessage(e.message||'Unable to load game challenges.')}};
 useEffect(()=>{void refreshChallenges()},[authenticated]);
 useEffect(()=>{setSaved(false);setScore(0);setRound(0);setQuestionIndex(Math.floor(Math.random()*QUESTIONS.length));setMessage('Ready!');setStartedAt(active?Date.now():0);if(active==='bathroom_memory'||active==='amenity_architect'){setTargets(shuffle([...SYMBOLS,...SYMBOLS]));setMatched([]);setChoice([])}if(active==='stall_strategy'){const s=shuffle(Array.from({length:9},(_,i)=>i)).slice(0,4);setGrid(s);setGridSolution(s);setGridGuess([]);const timer=setTimeout(()=>setGrid([]),1100);return()=>clearTimeout(timer)}},[active]);
 const saveScore=async()=>{if(saved||!active||round===0)return;if(!authenticated){setMessage('Sign in to save your score.');return}setSaved(true);try{await services.progression.recordGameResult(active,score,startedAt?Date.now()-startedAt:0,{rounds:round,focus:'bathroom_trust'});setMessage('Score saved to progression.');await refreshChallenges()}catch(e){setSaved(false);setMessage(e.message||'Score could not be saved.')}};
 const playChallenge=async challenge=>{if(challenge.status!=='accepted')return;setActive(challenge.game_code);setChallengeMessage(`Playing challenge against ${challenge.creator_id===user?.id?challenge.invitee_name:challenge.creator_name}.`);};
 const saveChallengeScore=async challenge=>{if(!active||round===0)return;setChallengeBusy(true);try{const result=await services.progression.recordGameChallengeScore(challenge.id,score,{rounds:round,focus:'bathroom_trust'});setChallengeMessage(result?.status==='completed'?'Challenge complete — check the winner!':'Your score is recorded. Waiting for the other player.');setSaved(true);await refreshChallenges()}catch(e){setChallengeMessage(e.message||'Challenge score could not be saved.')}finally{setChallengeBusy(false)}};
 const createChallenge=async()=>{if(!opponent||!challengeGame)return;setChallengeBusy(true);setChallengeMessage('');try{await services.progression.createGameChallenge(challengeGame,opponent,{focus:'bathroom_trust'});setChallengeMessage('Challenge sent. Your friend or follower will see it in their challenges.');setOpponent('');await refreshChallenges()}catch(e){setChallengeMessage(e.message||'Unable to send challenge.')}finally{setChallengeBusy(false)}};
 const respond=async(id,accept)=>{setChallengeBusy(true);try{await services.progression.respondGameChallenge(id,accept);setChallengeMessage(accept?'Challenge accepted — play it now.':'Challenge declined.');await refreshChallenges()}catch(e){setChallengeMessage(e.message||'Unable to update challenge.')}finally{setChallengeBusy(false)}};
 const tap=i=>{setRound(r=>r+1);if(tapTargets.includes(i)){setScore(s=>s+10);setMessage('Strong evidence! +10')}else setMessage('Weak signal — keep looking.')};
 const chooseMemory=i=>{if(choice.length===2||matched.includes(i))return;const next=[...choice,i];setChoice(next);setRound(r=>r+1);if(next.length===2){if(targets[next[0]]===targets[next[1]]){setMatched(m=>[...m,...next]);setScore(s=>s+20);setMessage('Evidence pair matched! +20');setChoice([])}else{setMessage('No match — try again.');setTimeout(()=>setChoice([]),450)}}};
 const answer=i=>{setRound(r=>r+1);if(i===currentQuestion[2]){setScore(s=>s+15);setMessage('Trustworthy choice! +15')}else setMessage('Not the strongest evidence.');setQuestionIndex(v=>v+1)};
 const gridPick=i=>{if(gridGuess.includes(i)||gridGuess.length>=gridSolution.length)return;const next=[...gridGuess,i];setGridGuess(next);setRound(r=>r+1);if(next.length===gridSolution.length){const good=next.every(x=>gridSolution.includes(x));setScore(s=>s+(good?40:0));setMessage(good?'Evidence path matched! +40':'Path missed — try another round.')}};
 const activeChallenge=gameChallenges.find(c=>c.status==='accepted'&&c.game_code===active&&((c.creator_id===user?.id&&c.creator_score==null)||(c.invitee_id===user?.id&&c.invitee_score==null)));
 if(!authenticated)return <WorkspaceShell workspace="consumer"><section className="page"><div className="empty-state"><Gamepad2 size={30}/><h2>Sign in to play</h2><p>Your scores, progression, and challenges are tied to your Kleenest profile.</p><Link className="button primary" to="/auth">Sign in</Link></div></section></WorkspaceShell>;
 return <WorkspaceShell workspace="consumer"><section className="page games-page">
  <Link className="back-link" to="/rewards"><ArrowLeft size={16}/>Back to rewards</Link>
  <div className="page-header"><div><span className="eyebrow">KLEENEST PLAY</span><h1>Bathroom Trust Game Center</h1><p>Mini games turn trustworthy restroom knowledge, reviews, observations, amenities, and route decisions into progression.</p></div><div className="reward-stats"><div><Gamepad2/><strong>{score}</strong><span>score</span></div><div><Zap/><strong>{round}</strong><span>moves</span></div></div></div>
  <section className="detail-panel" style={{marginBottom:18}}><div className="panel-heading"><div><span className="eyebrow">CHALLENGE FRIENDS & FOLLOWERS</span><h2>Send a bathroom trust challenge</h2></div><Users size={22}/></div><div className="form-grid"><label>Game<select value={challengeGame} onChange={e=>setChallengeGame(e.target.value)}>{GAMES.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label><label>Opponent<select value={opponent} onChange={e=>setOpponent(e.target.value)}><option value="">Choose a follower</option>{gameTargets.map(t=><option key={t.user_id} value={t.user_id}>{t.display_name||t.username||'Kleenest member'} · {t.relationship}</option>)}</select></label></div><div className="hero-actions"><button className="button primary" disabled={!opponent||challengeBusy} onClick={createChallenge}><Send size={16}/>Send challenge</button>{challengeMessage&&<p className="form-note" role="status">{challengeMessage}</p>}</div></section>
  {gameChallenges.length>0&&<section className="detail-panel" style={{marginBottom:18}}><div className="panel-heading"><div><span className="eyebrow">YOUR CHALLENGES</span><h2>Friend matches</h2></div><Trophy size={22}/></div><div className="business-list">{gameChallenges.slice(0,12).map(c=>{const mine=c.creator_id===user?.id;const opponentName=mine?c.invitee_name:c.creator_name;return <div className="business-row" key={c.id}><div><strong>{GAMES.find(g=>g.id===c.game_code)?.title||c.game_code}</strong><span>{opponentName} · {c.status} · {mine?`You ${c.creator_score??'—'}`:`Them ${c.creator_score??'—'}`} / {mine?`Them ${c.invitee_score??'—'}`:`You ${c.invitee_score??'—'}`}</span></div><div className="hero-actions">{c.status==='pending'&&!mine&&<><button className="button primary" disabled={challengeBusy} onClick={()=>respond(c.id,true)}><CheckCircle2 size={14}/>Accept</button><button className="button secondary" disabled={challengeBusy} onClick={()=>respond(c.id,false)}>Decline</button></>}{c.status==='accepted'&&((mine&&c.creator_score==null)||(!mine&&c.invitee_score==null))&&<button className="button primary" onClick={()=>playChallenge(c)}>Play</button>}{c.status==='completed'&&<span className="form-note">{c.winner_id?`${c.winner_id===user?.id?'You won':'Opponent won'}`:'Tie game'}</span>}</div></div>})}</div></section>}
  <div className="game-grid">{GAMES.map(g=>{const Icon=g.icon;return <button className={`game-card ${active===g.id?'selected':''}`} key={g.id} onClick={()=>setActive(g.id)}><span className="game-icon"><Icon/></span><span><b>{g.title}</b><small>{g.tag}</small><em>{g.description}</em></span></button>})}</div>
  {active&&<section className="detail-panel game-board"><div className="panel-heading"><div><span className="eyebrow">NOW PLAYING {activeChallenge?'· HEAD-TO-HEAD':''}</span><h2>{currentGame?.title}</h2></div><Clock3 size={24}/></div><p className="game-message">{message}</p>
   {currentGame?.mechanic==='tap'&&<div className="tap-board">{Array.from({length:12},(_,i)=><button key={i} onClick={()=>tap(i)}>{tapTargets.includes(i)?'✦':'·'}</button>)}</div>}
   {currentGame?.mechanic==='memory'&&<div className="memory-board">{targets.map((symbol,i)=><button key={i} onClick={()=>chooseMemory(i)}>{matched.includes(i)||choice.includes(i)?symbol:'?'}</button>)}</div>}
   {currentGame?.mechanic==='quiz'&&<div className="quiz-board"><h3>{currentQuestion[0]}</h3>{currentQuestion[1].map((x,i)=><button key={x} onClick={()=>answer(i)}>{x}</button>)}</div>}
   {currentGame?.mechanic==='grid'&&<div className="tap-board">{Array.from({length:9},(_,i)=><button key={i} onClick={()=>gridPick(i)}>{grid.includes(i)&&gridGuess.length===0?'◆':gridGuess.includes(i)?'◆':'·'}</button>)}</div>}
   <div className="game-actions"><button className="button primary" onClick={activeChallenge?()=>saveChallengeScore(activeChallenge):saveScore} disabled={saved||round===0||challengeBusy}>{saved?'Score saved':activeChallenge?'Submit challenge score':'Save score'}</button><button className="button secondary" onClick={()=>{setActive(null);setSaved(false)}}><RotateCcw size={16}/>Choose another</button></div>
  </section>}
  <section className="detail-panel" style={{marginTop:18}}><div className="panel-heading"><div><span className="eyebrow">TRUST-FIRST PROGRESSION</span><h2>How games improve Kleenest</h2></div><ShieldCheck size={22}/></div><div className="dashboard-grid"><article className="result-card"><h3>Evidence literacy</h3><p>Games teach users to recognize verified visits, useful observations, current amenities, and actionable review details.</p></article><article className="result-card"><h3>Contribution motivation</h3><p>Completed games feed the existing authoritative progression path for points, levels, badges, streaks, and rewards.</p></article><article className="result-card"><h3>Social trust</h3><p>Follower challenges create friendly competition around the same evidence standards Kleenest uses for better restroom intelligence.</p></article></div></section>
 </section></WorkspaceShell>
}