import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Brain, Clock3, Gamepad2, RotateCcw, Trophy, Zap, Grid3X3, Target, Users, Send, CheckCircle2, ShieldCheck, Star } from 'lucide-react';
import { Link } from 'react-router-dom';
import WorkspaceShell from './WorkspaceShell.jsx';
import { useAppContext } from '../AppContext.jsx';
import './GamesPage.css';

const GAMES = [['clean_sweep','Clean Sweep','Quick tap',Zap,'tap','Find the strongest cleanliness signal.'],['bathroom_memory','Bathroom Memory','Match pairs',Brain,'memory','Match restroom amenities and evidence.'],['trust_or_bust','Trust or Bust','Trust quiz',ShieldCheck,'quiz','Separate strong evidence from weak signals.'],['flush_the_facts','Flush the Facts','Rapid fire',Target,'quiz','Make fast decisions about useful reviews.'],['restroom_relay','Restroom Relay','Evidence relay',Star,'quiz','Race through cleanliness and accessibility decisions.'],['stall_strategy','Stall Strategy','Evidence strategy',Grid3X3,'grid','Build the strongest evidence path.'],['sink_sprint','Sink Sprint','Amenity sprint',Zap,'tap','Spot soap, drying, sink, and accessibility signals.'],['route_to_relief','Route to Relief','Route puzzle',Target,'quiz','Choose the strongest restroom stop.'],['review_rater','Review Rater','Review quality',Trophy,'quiz','Rank what a traveler actually needs.'],['evidence_detective','Evidence Detective','Find the clue',ShieldCheck,'quiz','Spot clues that make a rating trustworthy.'],['amenity_architect','Amenity Architect','Build the profile',Grid3X3,'memory','Assemble the strongest restroom profile.'],['cleanliness_clash','Cleanliness Clash','Head-to-head',Users,'quiz','Challenge someone to identify stronger evidence.']];
const SYMBOLS = ['WC','SOAP','SINK','DRY','ADA','BABY'];
const QUESTIONS = [['Which signal is strongest for a trustworthy restroom review?',['Verified check-in plus useful observation','A random rating with no visit','A copied description'],0],['Which detail helps the next visitor most?',['Specific cleanliness and amenity facts','Only a star number','Only a joke'],0],['What makes a review more useful over time?',['Recent, visit-linked evidence','An old unsupported claim','No location context'],0],['Which restroom fact is most actionable?',['Soap unavailable at the sink','It felt weird','Nice place'],0],['What should a trust-focused game reward?',['Accurate evidence and useful contribution','Spammy ratings','Repeated taps with no context'],0],['What is the best accessibility signal?',['Observed accessible entrance/fixture details','A guess from the building name','No information'],0],['Which combination is strongest?',['Check-in + observation + review','Review only','Photo caption only'],0],['What should a route recommendation prioritize?',['Trustworthy nearby evidence and usable amenities','Popularity alone','Random selection'],0]];
const shuffle = (a) => [...a].sort(() => Math.random() - 0.5);

export default function GamesPage() {
  const { services, user } = useAppContext();
  const [active,setActive]=useState(null),[score,setScore]=useState(0),[round,setRound]=useState(0),[message,setMessage]=useState('Choose a game.'),[targets,setTargets]=useState([]),[matched,setMatched]=useState([]),[choice,setChoice]=useState([]),[questionIndex,setQuestionIndex]=useState(0),[questionRounds,setQuestionRounds]=useState(0),[grid,setGrid]=useState([]),[gridGuess,setGridGuess]=useState([]),[tapHits,setTapHits]=useState([]),[saved,setSaved]=useState(false),[startedAt,setStartedAt]=useState(0),[challenges,setChallenges]=useState([]),[targetsForChallenge,setTargetsForChallenge]=useState([]),[opponent,setOpponent]=useState(''),[challengeGame,setChallengeGame]=useState('cleanliness_clash'),[busy,setBusy]=useState(false),[challengeMessage,setChallengeMessage]=useState('');
  const authenticated=Boolean(user); const current=GAMES.find(g=>g[0]===active); const question=QUESTIONS[questionIndex%QUESTIONS.length];
  const refresh=async()=>{if(!authenticated)return;try{const[c,t]=await Promise.all([services.progression.gameChallenges(),services.progression.gameTargets()]);setChallenges(c??[]);setTargetsForChallenge(t??[])}catch(e){setChallengeMessage(e.message||'Unable to load challenges.')}};
  useEffect(()=>{void refresh()},[authenticated]);
  useEffect(()=>{setSaved(false);setScore(0);setRound(0);setQuestionRounds(0);setTapHits([]);setMessage('Ready!');setStartedAt(active?Date.now():0);if(active==='bathroom_memory'||active==='amenity_architect'){setTargets(shuffle([...SYMBOLS,...SYMBOLS]));setMatched([]);setChoice([])}if(active==='stall_strategy'){setGrid(shuffle(Array.from({length:9},(_,i)=>i)).slice(0,4));setGridGuess([])}},[active]);
  const save=async()=>{if(saved||!active||round===0)return;setBusy(true);try{await services.progression.recordGameResult(active,score,startedAt?Date.now()-startedAt:0,{rounds:round,focus:'bathroom_trust'});setSaved(true);setMessage('Score saved to progression.');await refresh()}catch(e){setMessage(e.message||'Score could not be saved.')}finally{setBusy(false)}};
  const send=async()=>{if(!opponent)return;setBusy(true);try{await services.progression.createGameChallenge(challengeGame,opponent,{focus:'bathroom_trust'});setChallengeMessage('Challenge sent.');setOpponent('');await refresh()}catch(e){setChallengeMessage(e.message||'Unable to send challenge.')}finally{setBusy(false)}};
  const respond=async(id,accept)=>{setBusy(true);try{await services.progression.respondGameChallenge(id,accept);setChallengeMessage(accept?'Challenge accepted.':'Challenge declined.');await refresh()}catch(e){setChallengeMessage(e.message||'Unable to update challenge.')}finally{setBusy(false)}};
  const play=c=>{setActive(c.game_code);setChallengeMessage(`Playing against ${c.creator_id===user?.id?c.invitee_name:c.creator_name||'your opponent'}.`)};
  const submitChallenge=async c=>{setBusy(true);try{await services.progression.recordGameChallengeScore(c.id,score,{rounds:round,focus:'bathroom_trust'});setSaved(true);setChallengeMessage('Challenge score recorded.');await refresh()}catch(e){setChallengeMessage(e.message||'Unable to submit challenge score.')}finally{setBusy(false)}};
  const tapTargets=useMemo(()=>shuffle(Array.from({length:12},(_,i)=>i)).slice(0,5),[active]);
  const tap=i=>{if(tapHits.includes(i)||saved)return;setTapHits(x=>[...x,i]);setRound(x=>x+1);if(tapTargets.includes(i)){setScore(x=>x+10);setMessage('Strong evidence! +10')}else setMessage('Weak signal — keep looking.');if(tapHits.length+1>=tapTargets.length)setMessage('Round complete. Save your score or choose another game.')};
  const memory=i=>{if(choice.length===2||matched.includes(i)||saved)return;const n=[...choice,i];setChoice(n);setRound(x=>x+1);if(n.length===2){if(targets[n[0]]===targets[n[1]]){setMatched(x=>[...x,...n]);setScore(x=>x+20);setMessage('Evidence pair matched! +20');setChoice([])}else{setMessage('No match.');setTimeout(()=>setChoice([]),450)}}};
  const answer=i=>{if(questionRounds>=8||saved)return;setRound(x=>x+1);setQuestionRounds(x=>x+1);if(i===question[2]){setScore(x=>x+15);setMessage(questionRounds+1>=8?'Quiz complete. Save your score!':'Trustworthy choice! +15')}else setMessage(questionRounds+1>=8?'Quiz complete. Save your score!':'Not the strongest evidence.');setQuestionIndex(x=>x+1)};
  const gridPick=i=>{if(gridGuess.includes(i)||gridGuess.length>=grid.length||saved)return;const n=[...gridGuess,i];setGridGuess(n);setRound(x=>x+1);if(n.length===grid.length){const good=n.every(x=>grid.includes(x));setScore(x=>x+(good?40:0));setMessage(good?'Evidence path matched! +40':'Path missed — try another round.')}};
  const challenge=challenges.find(c=>c.status==='accepted'&&c.game_code===active&&((c.creator_id===user?.id&&c.creator_score==null)||(c.invitee_id===user?.id&&c.invitee_score==null)));
  if(!authenticated)return <WorkspaceShell workspace="consumer"><section className="page"><div className="empty-state"><Gamepad2 size={30}/><h2>Sign in to play</h2><p>Your scores, progression, and challenges are tied to your profile.</p><Link className="button primary" to="/auth">Sign in</Link></div></section></WorkspaceShell>;
  return <WorkspaceShell workspace="consumer"><main className="page games-page"><Link className="back-link" to="/rewards"><ArrowLeft size={16}/>Back to rewards</Link><div className="page-header"><div><span className="eyebrow">KLEENEST PLAY</span><h1>Bathroom Trust Game Center</h1><p>Learn trustworthy restroom signals, earn progression, and challenge friends.</p></div><div className="reward-stats"><div><Gamepad2/><strong>{score}</strong><span>score</span></div><div><Zap/><strong>{round}</strong><span>moves</span></div></div></div>
    <section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">CHALLENGE FRIENDS</span><h2>Send a trust challenge</h2></div><Users size={22}/></div><div className="form-grid"><label>Game<select value={challengeGame} onChange={e=>setChallengeGame(e.target.value)}>{GAMES.map(g=><option value={g[0]} key={g[0]}>{g[1]}</option>)}</select></label><label>Opponent<select value={opponent} onChange={e=>setOpponent(e.target.value)}><option value="">Choose a follower</option>{targetsForChallenge.map(t=><option value={t.user_id} key={t.user_id}>{t.display_name||t.username||'Kleenest member'}</option>)}</select></label></div><button className="button primary" disabled={!opponent||busy} onClick={send}><Send size={15}/>Send challenge</button>{challengeMessage&&<p className="form-note" role="status">{challengeMessage}</p>}</section>
    {challenges.length>0&&<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">YOUR MATCHES</span><h2>Challenges</h2></div><Trophy size={22}/></div>{challenges.slice(0,12).map(c=><div className="business-row" key={c.id}><div><strong>{GAMES.find(g=>g[0]===c.game_code)?.[1]||c.game_code}</strong><span>{c.creator_id===user.id?c.invitee_name:c.creator_name} · {c.status}</span></div><div className="hero-actions">{c.status==='pending'&&c.invitee_id===user.id&&<><button className="button primary" disabled={busy} onClick={()=>respond(c.id,true)}><CheckCircle2 size={14}/>Accept</button><button className="button secondary" disabled={busy} onClick={()=>respond(c.id,false)}>Decline</button></>}{c.status==='accepted'&&((c.creator_id===user.id&&c.creator_score==null)||(c.invitee_id===user.id&&c.invitee_score==null))&&<button className="button primary" onClick={()=>play(c)}>Play</button>}{c.status==='completed'&&<span className="form-note">{c.winner_id===user.id?'You won':'Match complete'}</span>}</div></div>)}</section>}
    <div className="game-grid">{GAMES.map(g=>{const Icon=g[3];return <button className={`game-card ${active===g[0]?'selected':''}`} key={g[0]} onClick={()=>setActive(g[0])}><span className="game-icon"><Icon/></span><span><b>{g[1]}</b><small>{g[2]}</small><em>{g[5]}</em></span></button>})}</div>
    {active&&<section className="detail-panel game-board"><div className="panel-heading"><div><span className="eyebrow">NOW PLAYING{challenge?' · HEAD-TO-HEAD':''}</span><h2>{current?.[1]}</h2></div><Clock3 size={23}/></div><p className="game-message">{message}</p>{current?.[4]==='tap'&&<div className="tap-board">{Array.from({length:12},(_,i)=><button key={i} disabled={tapHits.includes(i)||saved} onClick={()=>tap(i)}>{tapHits.includes(i)?'✓':tapTargets.includes(i)?'✦':'·'}</button>)}</div>}{current?.[4]==='memory'&&<div className="memory-board">{targets.map((s,i)=><button key={i} disabled={matched.includes(i)||saved} onClick={()=>memory(i)}>{matched.includes(i)||choice.includes(i)?s:'?'}</button>)}</div>}{current?.[4]==='quiz'&&<div className="quiz-board"><h3>{question[0]}</h3>{question[1].map((x,i)=><button key={x} disabled={questionRounds>=8||saved} onClick={()=>answer(i)}>{x}</button>)}</div>}{current?.[4]==='grid'&&<div className="tap-board">{Array.from({length:9},(_,i)=><button key={i} disabled={gridGuess.includes(i)||gridGuess.length>=grid.length||saved} onClick={()=>gridPick(i)}>{gridGuess.includes(i)?'◆':'·'}</button>)}</div>}<div className="game-actions"><button className="button primary" disabled={saved||round===0||busy} onClick={challenge?()=>submitChallenge(challenge):save}>{saved?'Score saved':challenge?'Submit challenge score':'Save score'}</button><button className="button secondary" onClick={()=>{setActive(null);setSaved(false)}}><RotateCcw size={15}/>Choose another</button></div></section>}
    <section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">TRUST-FIRST PROGRESSION</span><h2>Play that makes the network better</h2></div><ShieldCheck size={22}/></div><div className="dashboard-grid"><article className="result-card"><h3>Learn evidence</h3><p>Games teach users to recognize verified visits, useful observations, current amenities, and actionable reviews.</p></article><article className="result-card"><h3>Earn progression</h3><p>Completed games feed the existing progression engine for points, levels, badges, streaks, and rewards.</p></article><article className="result-card"><h3>Compete socially</h3><p>Challenges turn the same evidence standards into friendly competition with followers and friends.</p></article></div></section>
  </main></WorkspaceShell>;
}
