import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Heart, MapPin, Navigation, ShieldCheck, Star, Sparkles, Camera, Route, Trophy } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import WorkspaceShell from './WorkspaceShell.jsx';
import { useAppContext } from '../AppContext.jsx';

const amenities = [
  ['accessible','Accessible'],['changing_table','Changing table'],['baby_changing','Family / baby changing'],['handwashing','Handwashing'],['drinking_water','Drinking water'],['shower','Shower'],['parking','Parking'],['wifi','Wi-Fi'],['pet_friendly','Pet friendly']
];
const truthy = v => v === true || v === 1 || v === 'true';
const placeAmenities = place => amenities.filter(([key]) => truthy(place[key]) || truthy(place[`has_${key}`]) || (Array.isArray(place.amenities) && place.amenities.map(String).map(x=>x.toLowerCase().replaceAll(' ','_')).includes(key)));
const scoreLabel = score => score == null ? 'Awaiting signal' : score >= 85 ? 'High confidence' : score >= 65 ? 'Good confidence' : score >= 45 ? 'Developing confidence' : 'Limited confidence';

export default function LocationDetailsPage(){
  const { id } = useParams(); const navigate = useNavigate();
  const { services, user } = useAppContext();
  const [place,setPlace]=useState(null),[reviews,setReviews]=useState([]),[interaction,setInteraction]=useState(null),[bathroomStatus,setBathroomStatus]=useState(null),[rating,setRating]=useState(5),[comment,setComment]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
  const load=async()=>{setError('');const next=await services.locations.getById(id);if(!next){setPlace(null);return}setPlace(next);const lid=next.location_id||next.id;const jobs=[services.locations.reviews(lid),services.locationEvidence.bathroomStatus(lid)];if(user)jobs.push(services.locations.interactionState(lid));const r=await Promise.all(jobs);setReviews(r[0]||[]);setBathroomStatus(r[1]||null);setInteraction(user?r[2]||null:null);void services.locations.recordView(lid)};
  useEffect(()=>{void load().catch(e=>setError(e.message||'Unable to load this location.'))},[id,user?.id]);
  useEffect(()=>{const refresh=()=>void load();['kleenest:checkin-completed','kleenest:rewards-updated','kleenest:location-activity'].forEach(e=>window.addEventListener(e,refresh));return()=>['kleenest:checkin-completed','kleenest:rewards-updated','kleenest:location-activity'].forEach(e=>window.removeEventListener(e,refresh))},[id,user?.id]);
  const requireLogin=()=>{if(!user){navigate(`/auth?returnTo=${encodeURIComponent(`/place/${id}`)}`);return false}return true};
  const lid=place?.location_id||place?.id;
  const checkIn=async()=>{if(!requireLogin()||!place?.latitude||!place?.longitude)return;setBusy('checkin');setError('');try{const d=await services.checkins.fromMap({locationId:lid,latitude:place.latitude,longitude:place.longitude});const row=Array.isArray(d)?d[0]:d;setInteraction(v=>({...v,checkedIn:true,latestCheckIn:row||null}));setMessage(`Visit verified${row?.points_awarded!=null?` · +${row.points_awarded} points`:''}. Your trust contribution is now part of the location story.`);window.dispatchEvent(new CustomEvent('kleenest:checkin-completed',{detail:{locationId:lid,checkInId:row?.id||row?.check_in_id}}))}catch(e){setError(e.message||'Unable to verify this visit.')}finally{setBusy('')}};
  const toggleFavorite=async()=>{if(!requireLogin())return;setBusy('favorite');try{const r=await services.favorites.toggle(lid);setInteraction(v=>({...v,favorited:Boolean(r?.favorite??r?.favorited)}));setMessage(Boolean(r?.favorite??r?.favorited)?'Saved. We’ll keep this location close.':'Removed from saved locations.')}catch(e){setError(e.message||'Unable to update saved locations.')}finally{setBusy('')}};
  const directions=async()=>{if(!requireLogin())return;setBusy('directions');try{await services.analytics.directionsRequested(lid,{source:'place-details',mode:'driving'});window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${place.latitude},${place.longitude}`)}`,'_blank','noopener,noreferrer');setMessage('Directions opened.')}catch(e){setError(e.message||'Unable to open directions.')}finally{setBusy('')}};
  const arrival=async()=>{if(!requireLogin())return;setBusy('arrival');try{await services.analytics.arrival(lid,{source:'place-details'});setMessage('Arrival recorded.')}catch(e){setError(e.message||'Unable to record arrival.')}finally{setBusy('')}};
  const verifyBathroom=async value=>{if(!requireLogin())return;setBusy('verify');try{const d=await services.locationEvidence.trustedBathroomVerification({locationId:lid,hasPublicBathroom:value,latitude:place.latitude,longitude:place.longitude,distanceMeters:0});setBathroomStatus(Array.isArray(d)?d[0]:d);setMessage(value?'Bathroom signal submitted. Thanks for strengthening this location.':'No-public-bathroom signal submitted.');window.dispatchEvent(new CustomEvent('kleenest:location-activity',{detail:{locationId:lid}}))}catch(e){setError(e.message||'Unable to submit this signal.')}finally{setBusy('')}};
  const submitReview=async e=>{e.preventDefault();if(!requireLogin()||!comment.trim())return;setBusy('review');try{const d=await services.reviews.create({locationId:lid,checkInId:interaction?.latestCheckIn?.id||interaction?.latestCheckIn?.check_in_id,stars:rating,comment:comment.trim()});const reviewId=Array.isArray(d)?d[0]?.id:d?.id;setComment('');setReviews(await services.locations.reviews(lid));if(reviewId)void services.progression.reviewRewards(reviewId).catch(()=>null);window.dispatchEvent(new CustomEvent('kleenest:rewards-updated',{detail:{reviewId,locationId:lid}}));setMessage('Review published. Your experience can help the next visitor.')}catch(e){setError(e.message||'Unable to publish review.')}finally{setBusy('')}};
  if(error&&!place)return <WorkspaceShell workspace="consumer"><section className="empty-state"><h2>We couldn't load that place</h2><p>{error}</p><Link className="primary" to="/map">Back to map</Link></section></WorkspaceShell>;
  if(!place)return <WorkspaceShell workspace="consumer"><section className="empty-state"><Sparkles size={22}/><h2>Gathering location intelligence…</h2><p>Checking the live Kleenest network.</p></section></WorkspaceShell>;
  const restroom=place.category==='restroom',score=place.intelligence_score??place.location_confidence_score,verified=truthy(place.is_verified)||truthy(place.verified), amenityList=placeAmenities(place);
  return <WorkspaceShell workspace="consumer"><main className="page location-page">
    <button className="back-link" onClick={()=>navigate(-1)}><ArrowLeft size={16}/>Back to map</button>
    <section className="location-hero"><div className="location-hero-art"><MapPin size={42}/><span>{restroom?'RESTROOM':'PLACE'}</span></div><div className="location-hero-content"><span className="eyebrow">{restroom?'KLEENEST RESTROOM':'KLEENEST LOCATION'}</span><h1>{place.name}</h1><p className="location-address">{place.address||[place.city,place.state].filter(Boolean).join(', ')||'Address unavailable'}</p><div className="hero-tags">{verified&&<span className="tag"><ShieldCheck size={14}/>Verified</span>}<span className="tag">{scoreLabel(score)}</span>{place.review_count!=null&&<span className="tag"><Star size={14}/> {place.review_count} reviews</span>}</div><p className="location-description">{place.description||'A real-world location in the Kleenest network. Community contributions help keep this information useful and current.'}</p><div className="hero-actions"><button className="primary" onClick={checkIn} disabled={busy!==''}><CheckCircle2 size={16}/>{busy==='checkin'?'Verifying…':'Verify my visit'}</button><button className="secondary" onClick={directions} disabled={busy!==''}><Navigation size={16}/>Directions</button><button className="secondary" onClick={()=>navigate(`/route?destination=${encodeURIComponent(place.name)}&locationId=${encodeURIComponent(lid)}`)}><Route size={16}/>Add to route</button><button className="secondary" onClick={toggleFavorite} disabled={busy!==''}><Heart size={16} fill={interaction?.favorited?'currentColor':'none'}/>{interaction?.favorited?'Saved':'Save'}</button></div></div></section>
    {(error||message)&&<div className={`state ${error?'error':'success'}`} role="status">{error||message}</div>}
    <section className="location-intelligence-grid">
      <article className="detail-panel score-panel"><span className="eyebrow">TRUST SIGNAL</span><strong className="big-score">{score==null?'—':Math.round(score)}</strong><h3>{scoreLabel(score)}</h3><p>Confidence grows from verified visits, evidence, reviews, and fresh community signals.</p></article>
      <article className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">VERIFICATION</span><h2>Can you trust the basics?</h2></div><ShieldCheck size={21}/></div><div className="stat-row"><span>Verification signals</span><strong>{place.bathroom_verification_count??place.verification_observation_count??0}</strong></div><div className="stat-row"><span>Positive signals</span><strong>{place.bathroom_positive_count??place.verification_positive_count??0}</strong></div>{restroom&&<div className="button-row"><button className="secondary" disabled={busy!==''} onClick={()=>verifyBathroom(true)}>✓ Yes, public bathroom</button><button className="secondary" disabled={busy!==''} onClick={()=>verifyBathroom(false)}>Report no bathroom</button></div>}{bathroomStatus?.status&&<span className="tag">Current signal: {String(bathroomStatus.status).replaceAll('_',' ')}</span>}</article>
    </section>
    <section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">AMENITIES</span><h2>What you can expect</h2></div><Sparkles size={21}/></div>{amenityList.length?<div className="amenity-grid">{amenityList.map(([key,label])=><span className="amenity-pill" key={key}><CheckCircle2 size={15}/>{label}</span>)}</div>:<p className="muted">No structured amenity signals yet. <Link className="text-link" to={`/evidence?locationId=${encodeURIComponent(lid)}`}>Add evidence</Link> to help the next visitor.</p>}</section>
    <section className="detail-panel contribution-panel"><div className="panel-heading"><div><span className="eyebrow">MAKE IT BETTER</span><h2>One visit can improve the network</h2></div><Trophy size={21}/></div><div className="contribution-grid"><Link to={`/evidence?locationId=${encodeURIComponent(lid)}`} className="contribution-card"><Camera size={20}/><strong>Add evidence</strong><span>Show the next visitor what is actually here.</span></Link><Link to="/play/quest" className="contribution-card"><Trophy size={20}/><strong>Trust Quests</strong><span>Turn useful activity into progression and rewards.</span></Link><Link to="/activity" className="contribution-card"><Sparkles size={20}/><strong>Your progress</strong><span>See how your contributions are building trust.</span></Link></div></section>
    <section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">COMMUNITY</span><h2>Reviews</h2></div><Star size={22}/></div>{reviews.length?reviews.map(r=><article className="business-row" key={r.id}><div><strong>{'★'.repeat(Number(r.rating||r.stars||0))}{'☆'.repeat(Math.max(0,5-Number(r.rating||r.stars||0)))}</strong><span>{r.body||r.comment||'No written comment.'}</span><small>{r.profiles?.display_name||'Kleenest member'} · {r.created_at?new Date(r.created_at).toLocaleDateString():'Recent'}</small></div></article>):<p>No reviews yet. Be the first verified visitor to contribute.</p>}
      <form className="review-form" onSubmit={submitReview}><h3>Share your verified experience</h3><label>Rating<select value={rating} onChange={e=>setRating(Number(e.target.value))}><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Okay</option><option value="2">2 — Poor</option><option value="1">1 — Bad</option></select></label><label>Your review<textarea rows="4" value={comment} onChange={e=>setComment(e.target.value)} placeholder="What should the next visitor know?" required/></label><button className="primary" disabled={busy!==''||!interaction?.checkedIn}>{busy==='review'?'Publishing…':'Publish verified review'}</button>{!interaction?.checkedIn&&<p className="muted">Verify a visit first so reviews remain grounded in real-world experience.</p>}</form>
    </section>
  </main></WorkspaceShell>;
}
