import { useEffect, useState } from 'react';
import { ArrowLeft, Camera, CheckCircle2, Globe2, Heart, MapPin, Navigation, Route, ShieldCheck, Sparkles, Star, Trophy, Phone, X } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import WorkspaceShell from './WorkspaceShell.jsx';
import { useAppContext } from '../AppContext.jsx';
import { bathroomIntelligence, bathroomSignalLabel } from './MapMarkerSystem.jsx';
import { amenityLabels, osmTags, placeAddress, placeBrand, placeContact, placeFreshness, placeHours, placeLogoCandidates, placeName, sourceLabel } from './osmPlaceData.js';
import { publishConsumerActivity } from './consumerEngagementBridge.js';

const truthy = v => v === true || v === 1 || v === 'true';
const scoreLabel = score => score == null ? 'Awaiting signal' : score >= 85 ? 'High confidence' : score >= 65 ? 'Good confidence' : score >= 45 ? 'Developing confidence' : 'Limited confidence';
const amenityText = amenity => `${amenity.name || 'Amenity'}${amenity.quantity != null ? ` × ${amenity.quantity}` : ''}${amenity.sentiment === 'needs_attention' ? ' · needs attention' : ''}`;
const occupancyHeadline = occupancy => !occupancy?.sample_count ? 'No recent occupancy signal' : occupancy.fresh ? 'Fresh occupancy signal' : 'Recent occupancy history';
const freshnessLabel=f=>f?.score!=null?`${Math.round(Number(f.score))}% freshness`:f?.staleness?String(f.staleness).replaceAll('_',' '):'Freshness pending';

export default function LocationDetailsPageFixed() {
  const { id } = useParams(), navigate = useNavigate();
  const { services, user, loading: authLoading } = useAppContext();
  const [place, setPlace] = useState(null), [reviews, setReviews] = useState([]), [interaction, setInteraction] = useState(null), [bathroomStatus, setBathroomStatus] = useState(null), [occupancy, setOccupancy] = useState(null), [busy, setBusy] = useState(''), [message, setMessage] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(true), [rating, setRating] = useState(0), [comment, setComment] = useState(''), [logoIndex, setLogoIndex] = useState(0);
  const load = async () => { if (authLoading || !id || !services?.locations?.getById) return; setLoading(true); setError(''); try { const next = await services.locations.getById(id); if (!next) { setPlace(null); return; } setPlace(next); setLogoIndex(0); const lid = next.location_id || next.id; const jobs = [services.locations.reviews(lid), services.locationEvidence.bathroomStatus(lid), services.locationEvidence.occupancySummary(lid)]; if (user) jobs.push(services.locations.interactionState(lid)); const results = await Promise.allSettled(jobs); setReviews(results[0].status === 'fulfilled' ? results[0].value || [] : []); setBathroomStatus(results[1].status === 'fulfilled' ? results[1].value || null : null); setOccupancy(results[2].status === 'fulfilled' ? results[2].value || null : null); setInteraction(user && results[3]?.status === 'fulfilled' ? results[3].value || null : null); void services.locations.recordView(lid).catch(() => null); } catch (e) { setError(e?.message || 'Unable to load this location.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [id, user?.id, authLoading]);
  useEffect(() => { const refresh = event => { const eventLocationId=event?.detail?.locationId||event?.detail?.location_id; if(!eventLocationId||String(eventLocationId)===String(place?.location_id||place?.id||'')) void load(); }; window.addEventListener('kleenest:evidence-created',refresh); return()=>window.removeEventListener('kleenest:evidence-created',refresh); }, [id,user?.id,place?.id,place?.location_id]);
  const requireLogin = () => { if (!user) { navigate(`/auth?returnTo=${encodeURIComponent(`/locations/${id}`)}`); return false; } return true; };
  const lid = place?.location_id || place?.id;
  const position = () => new Promise((resolve, reject) => { if (!navigator.geolocation) return reject(new Error('Location services are unavailable.')); navigator.geolocation.getCurrentPosition(resolve, reject, { enableHighAccuracy: true, timeout: 12000, maximumAge: 30000 }); });
  const checkIn = async () => { if (!requireLogin() || !place) return; setBusy('checkin'); setError(''); try { const pos = await position(); const data = await services.checkins.byGps({ locationId: lid, latitude: pos.coords.latitude, longitude: pos.coords.longitude }); const row = Array.isArray(data) ? data[0] : data; setInteraction(v => ({ ...v, checkedIn: true, latestCheckIn: row || null })); setMessage('Visit verified.'); publishConsumerActivity('checkin', { checkInId: row?.id || row?.check_in_id || null, locationId: lid, source: 'location-details' }); } catch (e) { setError(e?.message || 'Unable to verify this visit.'); } finally { setBusy(''); } };
  const directions = async () => { if (!place) return; const url = `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${place.latitude},${place.longitude}`)}`; try { if (user) await services.analytics.directionsRequested(lid, { source: 'place-details', mode: 'driving' }); } catch {} window.location.assign(url); };
  const toggleFavorite = async () => { if (!requireLogin()) return; setBusy('favorite'); try { const r = await services.favorites.toggle(lid); const favorited = Boolean(r?.favorite ?? r?.favorited); setInteraction(v => ({ ...v, favorited })); setMessage(favorited ? 'Saved.' : 'Removed from saved locations.'); } catch (e) { setError(e?.message || 'Unable to update saved location.'); } finally { setBusy(''); } };
  const verifyBathroom = async value => { if (!requireLogin()) return; setBusy('verify'); try { const d = await services.locationEvidence.trustedBathroomVerification({ locationId: lid, hasPublicBathroom: value, latitude: place.latitude, longitude: place.longitude, distanceMeters: 0 }); setBathroomStatus(Array.isArray(d) ? d[0] : d); setMessage(value ? 'Bathroom signal submitted.' : 'No-public-bathroom signal submitted.'); publishConsumerActivity('evidence', { locationId: lid, kind: 'bathroom-verification', hasPublicBathroom: value }); } catch (e) { setError(e?.message || 'Unable to submit this signal.'); } finally { setBusy(''); } };
  const submitReview = async () => { if (!requireLogin() || !rating || !comment.trim() || !services?.reviews?.create) return; const checkInId = interaction?.latestCheckIn?.id || interaction?.latestCheckIn?.check_in_id || null; if (!checkInId) { setError('Verify your visit before publishing a customer review.'); return; } setBusy('review'); setError(''); try { const created = await services.reviews.create({ locationId: lid, checkInId, rating, body: comment.trim() }); const row = Array.isArray(created) ? created[0] : created; const reviewId = row?.id || row?.review_id || null; if (reviewId) await services.progression.reviewRewards(reviewId); setRating(0); setComment(''); setMessage('Verified review submitted.'); publishConsumerActivity('review', { reviewId, locationId: lid, source: 'location-details' }); await load(); } catch (e) { setError(e?.message || 'Unable to submit review.'); } finally { setBusy(''); } };
  if (authLoading || loading) return <WorkspaceShell workspace="consumer"><section className="empty-state"><Sparkles size={22}/><h2>Gathering location intelligence…</h2><p>Loading the canonical place record and source evidence.</p></section></WorkspaceShell>;
  if (!place) return <WorkspaceShell workspace="consumer"><section className="empty-state"><h2>We couldn't load that place</h2><p>{error || 'The location is no longer available.'}</p><Link className="primary" to="/map">Back to map</Link></section></WorkspaceShell>;
  const tags = osmTags(place), contact = placeContact(place), hours=placeHours(place), freshness=placeFreshness(place), candidates = placeLogoCandidates(place), logo = candidates[logoIndex] || '', address = placeAddress(place), name = placeName(place), brand = placeBrand(place), amenities = amenityLabels(place), bathroom = bathroomIntelligence({ ...place, ...(bathroomStatus || {}) }), score = place.intelligence_score ?? place.location_confidence_score, verified = truthy(place.is_verified) || truthy(place.verified), restroom = String(place.place_type || place.category || '').toLowerCase() === 'restroom';
  return <WorkspaceShell workspace="consumer"><main className="page location-page"><button className="back-link" onClick={() => navigate(-1)}><ArrowLeft size={16}/>Back</button>
    <section className="location-hero"><div className="location-hero-art">{logo ? <img className="place-featured-photo" src={logo} alt={`${name} logo`} onError={() => setLogoIndex(v => v + 1)}/> : <><MapPin size={42}/><span>{restroom ? 'RESTROOM' : 'PLACE'}</span></>}</div><div className="location-hero-content"><span className="eyebrow">{restroom ? 'KLEENEST RESTROOM' : 'KLEENEST LOCATION'}</span><h1>{name}</h1>{brand && brand !== name && <p className="location-address"><BuildingLabel/> {brand}</p>}<p className="location-address"><MapPin size={15}/>{address}</p><div className="hero-tags">{bathroom.hasSignal && <span className={`tag ${bathroom.status}`}>{bathroomSignalLabel({ ...place, ...bathroomStatus })}</span>}{verified && <span className="tag"><ShieldCheck size={14}/>Verified</span>}<span className="tag">{scoreLabel(score)}</span><span className="tag">{freshnessLabel(freshness)}</span>{occupancy?.fresh && <span className="tag">Occupancy updated</span>}{place.review_count != null && <span className="tag"><Star size={14}/>{place.review_count} reviews</span>}<span className="tag">{sourceLabel(place)}</span></div><div className="hero-actions"><button className="primary" onClick={checkIn} disabled={busy !== ''}><CheckCircle2 size={16}/>{busy === 'checkin' ? 'Verifying…' : interaction?.checkedIn ? 'Visit verified' : 'Verify my visit'}</button><button className="secondary" onClick={directions} disabled={busy !== ''}><Navigation size={16}/>Directions</button><button className="secondary" onClick={() => navigate(`/route?add=${encodeURIComponent(lid)}`)}><Route size={16}/>Add to route</button><button className="secondary" onClick={toggleFavorite} disabled={busy !== ''}><Heart size={16} fill={interaction?.favorited ? 'currentColor' : 'none'}/>{interaction?.favorited ? 'Saved' : 'Save'}</button></div></div></section>
    {(error || message) && <div className={`state ${error ? 'error' : 'success'}`} role="status">{error || message}</div>}
    <section className="location-intelligence-grid"><article className="detail-panel score-panel"><span className="eyebrow">TRUST SIGNAL</span><strong className="big-score">{score == null ? '—' : Math.round(score)}</strong><h3>{scoreLabel(score)}</h3><p>Confidence combines verification, evidence, reviews and freshness.</p></article><article className="detail-panel bathroom-intelligence-panel"><div className="panel-heading"><div><span className="eyebrow">BATHROOM INTELLIGENCE</span><h2>{bathroom.hasSignal ? bathroomSignalLabel({ ...place, ...bathroomStatus }) : 'No bathroom signal yet'}</h2></div><span className="bathroom-detail-icon">🚻</span></div><div className="bathroom-detail-grid"><div><span>Access</span><strong>{bathroom.accessLabel}</strong></div><div><span>Confidence</span><strong>{bathroom.confidence == null ? '—' : `${Math.round(bathroom.confidence)}%`}</strong></div><div><span>Evidence</span><strong>{bathroom.evidenceCount}</strong></div></div></article><article className="detail-panel occupancy-intelligence-panel"><div className="panel-heading"><div><span className="eyebrow">OCCUPANCY</span><h2>{occupancyHeadline(occupancy)}</h2></div><span className="bathroom-detail-icon">👥</span></div>{occupancy?.sample_count ? <><div className="bathroom-detail-grid"><div><span>People present</span><strong>{occupancy.occupancy_count ?? '—'}</strong></div><div><span>Utilization</span><strong>{occupancy.utilization_pct == null ? '—' : `${occupancy.utilization_pct}%`}</strong></div><div><span>Queue</span><strong>{occupancy.queue_count ?? '—'}</strong></div><div><span>Wait</span><strong>{occupancy.wait_minutes == null ? '—' : `${occupancy.wait_minutes} min`}</strong></div><div><span>Samples</span><strong>{occupancy.sample_count}</strong></div><div><span>Confidence</span><strong>{occupancy.confidence == null ? '—' : `${Math.round(Number(occupancy.confidence)*100)}%`}</strong></div></div><p className="muted">Privacy-safe aggregate from recent occupancy measurements. {occupancy.freshest_observed_at ? `Latest sample ${new Date(occupancy.freshest_observed_at).toLocaleTimeString()}.` : ''}</p></> : <p className="muted">No occupancy observations were recorded in the last two hours.</p>}</article></section>
    <section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">ADDRESS, HOURS & CONTACT</span><h2>Source-backed location identity</h2></div><MapPin size={21}/></div><div className="detail-grid"><div><span>Address</span><strong>{address}</strong></div>{hours&&<div><span>Hours</span><strong>{hours}</strong></div>}{contact.phone && <div><span>Phone</span><strong><a href={`tel:${encodeURIComponent(contact.phone)}`}><Phone size={14}/>{contact.phone}</a></strong></div>}{contact.website && <div><span>Website</span><strong><a href={contact.website.match(/^https?:\/\//) ? contact.website : `https://${contact.website}`}><Globe2 size={14}/> {contact.website}</a></strong></div>}<div><span>Source</span><strong>{sourceLabel(place)}</strong></div><div><span>Freshness</span><strong>{freshnessLabel(freshness)}</strong></div>{freshness.observedAt&&<div><span>Source observed</span><strong>{new Date(freshness.observedAt).toLocaleString()}</strong></div>}</div><details className="osm-source-details"><summary>Show persisted OSM source tags</summary><pre>{JSON.stringify(tags, null, 2)}</pre></details></section>
    <section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">AMENITIES</span><h2>What you can expect</h2></div><Sparkles size={21}/></div>{amenities.length ? <div className="amenity-grid">{amenities.map(a => <span className="amenity-pill" key={a}><CheckCircle2 size={15}/>{a}</span>)} </div> : <p className="muted">No structured amenity signals yet.</p>}{restroom && <div className="button-row"><button className="secondary" disabled={busy !== ''} onClick={() => verifyBathroom(true)}>✓ Yes, public bathroom</button><button className="secondary" disabled={busy !== ''} onClick={() => verifyBathroom(false)}>Report no bathroom</button></div>}</section>
    <section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">COMMUNITY</span><h2>Verified customer reviews</h2></div><Star size={22}/></div><div className="review-composer"><div className="review-stars">{[1,2,3,4,5].map(n => <button type="button" key={n} className={n <= rating ? 'selected' : ''} onClick={() => setRating(n)} aria-label={`${n} stars`}>★</button>)}</div><textarea value={comment} onChange={e => setComment(e.target.value)} placeholder={interaction?.latestCheckIn ? 'What should the next visitor know?' : 'Verify your visit before writing a review.'} rows={3}/><button className="primary" onClick={submitReview} disabled={busy !== '' || !comment.trim() || !rating || !interaction?.latestCheckIn}><Star size={16}/>Submit verified review</button></div>{!interaction?.latestCheckIn && user && <p className="muted">Customer reviews require a verified visit. Use “Verify my visit” above first.</p>}{reviews.length ? reviews.map(r => <article className="business-row" key={r.id}><div><strong>{'★'.repeat(Number(r.rating || r.stars || 0))}{'☆'.repeat(Math.max(0, 5 - Number(r.rating || r.stars || 0)))}</strong><span>{r.body || r.comment || 'No written comment.'}</span>{Array.isArray(r.amenities) && r.amenities.length > 0 && <div className="amenity-grid review-amenity-inventory">{r.amenities.map(a => <span className={`amenity-pill ${a.sentiment === 'needs_attention' ? 'needs-attention' : ''}`} key={`${r.id}-${a.id}`}>{amenityText(a)}</span>)}</div>}<small>{r.profiles?.display_name || 'Kleenest member'} · Verified visit · {r.created_at ? new Date(r.created_at).toLocaleDateString() : 'Recent'}</small></div></article>) : <p>No reviews yet.</p>}</section>
    <section className="detail-panel contribution-panel"><div className="panel-heading"><div><span className="eyebrow">MAKE IT BETTER</span><h2>Keep this place current</h2></div><Camera size={21}/></div><div className="contribution-grid"><Link to={`/evidence?locationId=${encodeURIComponent(lid)}`} className="contribution-card"><Camera size={20}/><strong>Add evidence</strong><span>Show the next visitor what is actually here.</span></Link><Link to="/games" className="contribution-card"><Trophy size={20}/><strong>Trust Quests</strong><span>Turn useful activity into progression and rewards.</span></Link></div></section>
  </main></WorkspaceShell>;
}
function BuildingLabel(){ return <span aria-hidden="true">🏢</span>; }