import L from 'leaflet';

const ICONS={auto:'<circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/>',restroom:'<path d="M8 4v7m0-3h8m0-4v7M6 20l2-6 2 6m4 0-2-6 2 6M7 4h2m6 0h2"/>',restaurant:'<path d="M6 3v8m3-8v8M4 3v5a3 3 0 0 0 6 0V3m7 0v18m7-12c2-2 3-4 0-6"/>',cafe:'<path d="M5 8h11v7a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V8Zm11 2h2a3 3 0 0 1 0 6h-2M8 4c0 1 1 1 1 2m3-2c0 1 1 1 1 2"/>',hotel:'<path d="M4 18V6m0 8h16v4M8 14v-3h4a3 3 0 0 1 3 3M8 18v2m12-2v2"/>',retail:'<path d="M4 9h16l-1 11H5L4 9Zm3 0V7a5 5 0 0 1 10 0v2M9 13h6"/>',gas_station:'<path d="M5 20V5h9v15M5 8h9m3 12V9l3 3v8a2 2 0 0 0 0 4-2 2 0 0 1-4 0m-8-9h5"/>',health:'<path d="M12 20s-7-4.3-7-10a4 4 0 0 1 7-2.5A4 4 0 0 1 19 10c0 5.7-7 10-7 10Zm0-12v6m-3-3h6"/>',government:'<path d="m3 9 9-5 9 5M5 10v8m4-8v8m6-8v8m4-8v8M3 20h18"/>',park:'<path d="M12 20V8m0 3-4-3m4 0 4-3M5 20h14M7 15c-2-1-2-4 1-5 0-3 4-4 5-1 1-3 5-2 5 1 3 1 3 4 1 5H7Z"/>',service:'<path d="m14 6 4 4-9 9H5v-4l9-9Zm-2-2 2-2 4 4-2 2"/>',brand:'<path d="M4 7h16l-2 13H6L4 7Zm4 0a4 4 0 0 1 8 0M9 12h6"/>'};
export const MAP_ICON_OPTIONS=[{id:'auto',label:'Automatic',glyph:'•'},{id:'restroom',label:'Restroom',glyph:'♙'},{id:'restaurant',label:'Restaurant',glyph:'♜'},{id:'cafe',label:'Cafe',glyph:'☕'},{id:'hotel',label:'Hotel',glyph:'⌂'},{id:'retail',label:'Retail',glyph:'▣'},{id:'gas_station',label:'Gas station',glyph:'⛽'},{id:'health',label:'Health',glyph:'✚'},{id:'government',label:'Government',glyph:'⌂'},{id:'park',label:'Park',glyph:'♧'},{id:'service',label:'Service',glyph:'⚒'},{id:'brand',label:'Brand',glyph:'◆'}];
export const CATEGORY_GLYPHS=Object.fromEntries(MAP_ICON_OPTIONS.map(item=>[item.id,item.id]));
export function safeText(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function placeBrand(place){return place?.brand||place?.brand_name||place?.operator_name||place?.business_name||place?.name||'';}
const BRAND_DOMAINS={starbucks:'starbucks.com',mcdonalds:'mcdonalds.com','mcdonald’s':'mcdonalds.com',target:'target.com',walmart:'walmart.com',walgreens:'walgreens.com',cvs:'cvs.com',costco:'costco.com','whole foods':'wholefoodsmarket.com',kroger:'kroger.com',shell:'shell.com',bp:'bp.com',exxon:'exxon.com',exxonmobil:'exxonmobil.com',chevron:'chevron.com','7-eleven':'7-eleven.com','chick-fil-a':'chick-fil-a.com',subway:'subway.com','taco bell':'tacobell.com',dunkin:'dunkindonuts.com',panera:'panerabread.com',publix:'publix.com',aldi:'aldi.us','sam’s club':'samsclub.com',"sam's club":'samsclub.com','home depot':'homedepot.com',"lowe's":'lowes.com'};
const BRAND_SLUGS={starbucks:'starbucks',mcdonalds:'mcdonalds',target:'target',walmart:'walmart',walgreens:'walgreens',cvs:'cvs-health',costco:'costco','whole foods':'whole-foods-market',kroger:'kroger',shell:'shell',bp:'bp',exxon:'exxonmobil',exxonmobil:'exxonmobil',chevron:'chevron','7-eleven':'7--eleven','chick-fil-a':'chick-fil-a',subway:'subway','taco bell':'taco-bell',dunkin:'dunkin',panera:'panera-bread',publix:'publix',aldi:'aldi',"sam’s club":'sams-club',"sam's club":'sams-club','home depot':'the-home-depot',"lowe's":'lowes'};
const normalizeBrand=v=>String(v??'').trim().toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const canonicalBrand=v=>normalizeBrand(v).replace(/ /g,'');
function businessIdentity(place){const id=place?.business_id||place?.businessId;if(!id||typeof window==='undefined')return null;try{const raw=window.localStorage.getItem(`kleenest.map.identity.${id}`);return raw?JSON.parse(raw):null;}catch{return null;}}
function brandKey(place){const text=canonicalBrand(`${place?.brand||''} ${place?.brand_name||''} ${place?.operator_name||''} ${place?.business_name||''} ${place?.name||''}`);return Object.keys(BRAND_SLUGS).find(key=>{const candidate=canonicalBrand(key);return text===candidate||text.includes(candidate);})||null;}
function domainFromPlace(place){const raw=place?.website_url||place?.websiteUrl||place?.website||place?.url||place?.domain;if(raw){try{const url=String(raw).match(/^https?:\/\//)?String(raw):`https://${raw}`;return new URL(url).hostname.replace(/^www\./,'');}catch{}}const key=brandKey(place);if(!key)return null;return BRAND_DOMAINS[key]||Object.entries(BRAND_DOMAINS).find(([name])=>canonicalBrand(name)===canonicalBrand(key))?.[1]||null;}
export function placeLogo(place){const identity=businessIdentity(place);return identity?.logoUrl||place?.logo_url||place?.logoUrl||place?.business_logo_url||place?.businessLogoUrl||place?.brand_logo_url||place?.brandLogoUrl||'';}
export function brandIconCandidates(place){const identity=businessIdentity(place),direct=identity?.logoUrl||placeLogo(place),key=brandKey(place),domain=domainFromPlace(place),urls=[];if(direct)urls.push(direct);if(key&&BRAND_SLUGS[key])urls.push(`https://cdn.simpleicons.org/${BRAND_SLUGS[key]}/111827`);if(domain)urls.push(`https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=128`);if(domain)urls.push(`https://${domain}/favicon.ico`);return [...new Set(urls)];}
export function brandIconUrl(place){return brandIconCandidates(place)[0]||'';}
export function placeIconKey(place){const identity=businessIdentity(place),explicit=identity?.iconKey||place?.map_icon||place?.map_icon_key||place?.business_icon||place?.icon_key;if(explicit&&ICONS[explicit])return explicit;if(brandKey(place))return'brand';if(place?.category&&ICONS[place.category])return place.category;if(place?.category==='shopping')return'retail';if(place?.category==='gas')return'gas_station';return'auto';}
/** Verification on the map means physical-location verification only. Bathroom verification is a separate evidence signal. */
export function placeStatus(place){const locationStatus=String(place?.location_verification_status||place?.verification_status||'').toLowerCase();const bathroomStatus=String(place?.bathroom_verification_status||place?.bathroom_status||'').toLowerCase();if(place?.is_verified===true||locationStatus==='verified')return{key:'verified',label:'Verified',glyph:'✓'};if(place?.sponsored===true||place?.is_sponsored===true||place?.premium===true)return{key:'premium',label:'Premium',glyph:'◆'};if(place?.open_now===true||place?.is_open===true)return{key:'open',label:'Open',glyph:'●'};if(place?.bathroom_reported===true||place?.category==='restroom'||bathroomStatus)return{key:'reported',label:'Community reported',glyph:'•'};return{key:'unknown',label:'Location signal',glyph:'•'};}

const BATHROOM_STATUS_LABELS={confirmed:'Confirmed',likely:'Likely',uncertain:'Uncertain',no_bathroom:'No bathroom',unknown:'Unknown'};
const BATHROOM_ACCESS_LABELS={public:'Public access',customers:'Customer access',permissive:'Permissive access',none:'No access',unknown:'Access unknown'};
export function bathroomIntelligence(place){const rawStatus=String(place?.bathroom_status||place?.bathroomStatus||'unknown').toLowerCase();const status=BATHROOM_STATUS_LABELS[rawStatus]?rawStatus:'unknown';const confidence=Number(place?.bathroom_confidence??place?.bathroomConfidence);const evidence=Number(place?.bathroom_evidence_count??place?.bathroomEvidenceCount);const rawAccess=String(place?.bathroom_access||place?.bathroomAccess||'unknown').toLowerCase();const access=BATHROOM_ACCESS_LABELS[rawAccess]?rawAccess:'unknown';return{status,statusLabel:BATHROOM_STATUS_LABELS[status],access,accessLabel:BATHROOM_ACCESS_LABELS[access],confidence:Number.isFinite(confidence)?Math.max(0,Math.min(100,confidence)):null,evidenceCount:Number.isFinite(evidence)?Math.max(0,evidence):0,hasSignal:Boolean(place?.bathroom_status||place?.bathroom_access||place?.bathroom_confidence!=null||place?.bathroom_evidence_count!=null)};}
export function bathroomSignalLabel(place,{includeAccess=true}={}){const b=bathroomIntelligence(place);if(!b.hasSignal)return'';const confidence=b.confidence!=null&&b.status!=='confirmed'&&b.status!=='no_bathroom'?` · ${Math.round(b.confidence)}%`:'';const access=includeAccess&&b.access!=='unknown'?` · ${b.accessLabel}`:'';return`🚻 ${b.statusLabel}${confidence}${access}`;}
const svgIcon=key=>`<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${ICONS[key]||ICONS.auto}</svg>`;
function logoMarkup(place){const candidates=brandIconCandidates(place),fallback=placeIconKey(place),first=candidates[0];if(!first)return`<span class="marker-fallback">${svgIcon(fallback)}</span>`;const encoded=safeText(JSON.stringify(candidates));return`<img class="marker-logo" src="${safeText(first)}" alt="" data-brand-candidates='${encoded}' referrerpolicy="no-referrer" onerror="const a=JSON.parse(this.dataset.brandCandidates||'[]');a.shift();if(a.length){this.src=a[0];}else{this.style.display='none';this.nextElementSibling.style.display='inline-flex';}"/><span class="marker-fallback" style="display:none">${svgIcon(fallback)}</span>`;}
export function markerIcon(place,{selected=false,favorite=false}={}){const iconKey=placeIconKey(place),status=placeStatus(place),brand=placeBrand(place),identity=logoMarkup(place),bathroom=bathroomIntelligence(place);return L.divIcon({className:'kleenest-marker-wrapper',html:`<div class="map-marker ${status.key} ${selected?'selected':''} ${favorite?'favorite':''} ${iconKey==='brand'?'brand-marker':''}"><span class="marker-identity">${identity}</span><span class="marker-status" title="${safeText(status.label)}">${status.glyph}</span>${bathroom.hasSignal?`<span class="marker-bathroom ${safeText(bathroom.status)}" title="${safeText(bathroomSignalLabel(place))}">🚻</span>`:''}${brand?`<small>${safeText(brand)}</small>`:''}</div>`,iconSize:[58,54],iconAnchor:[29,50],popupAnchor:[0,-46]});}
export function clusterIcon(count,category='all'){const key=ICONS[category]?category:'auto';return L.divIcon({className:'kleenest-cluster-wrapper',html:`<div class="map-cluster"><span class="cluster-symbol">${svgIcon(key)}</span><strong>${count}</strong></div>`,iconSize:[52,52],iconAnchor:[26,26]});}
const placeIdentityKey=place=>{const id=place?.location_id||place?.id;if(id)return`id:${String(id)}`;const lat=Number(place?.latitude),lng=Number(place?.longitude);const name=normalizeBrand(place?.brand||place?.brand_name||place?.operator_name||place?.business_name||place?.name);const address=normalizeBrand(place?.address||place?.formatted_address||'');if(Number.isFinite(lat)&&Number.isFinite(lng)&&name)return`geo:${lat.toFixed(5)}:${lng.toFixed(5)}:${name}`;if(name&&address)return`address:${name}:${address}`;return`fallback:${name}:${address}`;};
export function clusterPlaces(places){const seen=new Map();for(const place of places||[]){const key=placeIdentityKey(place);if(!seen.has(key))seen.set(key,place);}return[...seen.values()].map(place=>({type:'place',place}));}
export function spiderfyPosition(lat,lng,index,count){if(count<=1)return[lat,lng];const radiusMeters=Math.min(28,9+count*1.5),angle=(Math.PI*2*index/count)-(Math.PI/2),latOffset=(radiusMeters/111320)*Math.sin(angle),lngOffset=(radiusMeters/(111320*Math.max(0.2,Math.cos(lat*Math.PI/180))))*Math.cos(angle);return[lat+latOffset,lng+lngOffset];}
