export const MAP_ICON_OPTIONS=[{id:'auto',label:'Automatic',glyph:'•'},{id:'restroom',label:'Restroom',glyph:'♙'},{id:'restaurant',label:'Restaurant',glyph:'♜'},{id:'cafe',label:'Cafe',glyph:'☕'},{id:'hotel',label:'Hotel',glyph:'⌂'},{id:'retail',label:'Retail',glyph:'▣'},{id:'gas_station',label:'Gas station',glyph:'⛽'},{id:'health',label:'Health',glyph:'✚'},{id:'government',label:'Government',glyph:'⌂'},{id:'park',label:'Park',glyph:'♧'},{id:'service',label:'Service',glyph:'⚒'},{id:'brand',label:'Brand',glyph:'◆'}];
export const CATEGORY_GLYPHS=Object.fromEntries(MAP_ICON_OPTIONS.map(item=>[item.id,item.glyph]));
export function safeText(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));}
const normalizeIdentity=v=>String(v??'').trim().toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
/** Verification on the map means physical-location verification only. Bathroom verification is a separate evidence signal. */
export function placeStatus(place){const locationStatus=String(place?.location_verification_status||place?.verification_status||'').toLowerCase();const bathroomStatus=String(place?.bathroom_verification_status||place?.bathroom_status||'').toLowerCase();if(place?.is_verified===true||locationStatus==='verified')return{key:'verified',label:'Verified',glyph:'✓'};if(place?.sponsored===true||place?.is_sponsored===true||place?.premium===true)return{key:'premium',label:'Premium',glyph:'◆'};if(place?.open_now===true||place?.is_open===true)return{key:'open',label:'Open',glyph:'●'};if(place?.bathroom_reported===true||place?.category==='restroom'||bathroomStatus)return{key:'reported',label:'Community reported',glyph:'•'};return{key:'unknown',label:'Location signal',glyph:'•'};}
const BATHROOM_STATUS_LABELS={confirmed:'Confirmed',likely:'Likely',uncertain:'Uncertain',no_bathroom:'No bathroom',unknown:'Unknown'};
const BATHROOM_ACCESS_LABELS={public:'Public access',customers:'Customer access',permissive:'Permissive access',none:'No access',unknown:'Access unknown'};
export function bathroomIntelligence(place){const rawStatus=String(place?.bathroom_status||place?.bathroomStatus||'unknown').toLowerCase();const status=BATHROOM_STATUS_LABELS[rawStatus]?rawStatus:'unknown';const confidence=Number(place?.bathroom_confidence??place?.bathroomConfidence);const evidence=Number(place?.bathroom_evidence_count??place?.bathroomEvidenceCount);const rawAccess=String(place?.bathroom_access||place?.bathroomAccess||'unknown').toLowerCase();const access=BATHROOM_ACCESS_LABELS[rawAccess]?rawAccess:'unknown';return{status,statusLabel:BATHROOM_STATUS_LABELS[status],access,accessLabel:BATHROOM_ACCESS_LABELS[access],confidence:Number.isFinite(confidence)?Math.max(0,Math.min(100,confidence)):null,evidenceCount:Number.isFinite(evidence)?Math.max(0,evidence):0,hasSignal:Boolean(place?.bathroom_status||place?.bathroom_access||place?.bathroom_confidence!=null||place?.bathroom_evidence_count!=null)};}
export function bathroomSignalLabel(place,{includeAccess=true}={}){const b=bathroomIntelligence(place);if(!b.hasSignal)return'';const confidence=b.confidence!=null&&b.status!=='confirmed'&&b.status!=='no_bathroom'?` · ${Math.round(b.confidence)}%`:'';const access=includeAccess&&b.access!=='unknown'?` · ${b.accessLabel}`:'';return`🚻 ${b.statusLabel}${confidence}${access}`;}
const placeIdentityKey=place=>{const id=place?.location_id||place?.id;if(id)return`id:${String(id)}`;const lat=Number(place?.latitude),lng=Number(place?.longitude);const name=normalizeIdentity(place?.brand||place?.brand_name||place?.operator_name||place?.business_name||place?.name);const address=normalizeIdentity(place?.address||place?.formatted_address||'');if(Number.isFinite(lat)&&Number.isFinite(lng)&&name)return`geo:${lat.toFixed(5)}:${lng.toFixed(5)}:${name}`;if(name&&address)return`address:${name}:${address}`;return`fallback:${name}:${address}`;};
export function clusterPlaces(places){const seen=new Map();for(const place of places||[]){const key=placeIdentityKey(place);if(!seen.has(key))seen.set(key,place);}return[...seen.values()].map(place=>({type:'place',place}));}
export function spiderfyPosition(lat,lng,index,count){if(count<=1)return[lat,lng];const radiusMeters=Math.min(28,9+count*1.5),angle=(Math.PI*2*index/count)-(Math.PI/2),latOffset=(radiusMeters/111320)*Math.sin(angle),lngOffset=(radiusMeters/(111320*Math.max(0.2,Math.cos(lat*Math.PI/180))))*Math.cos(angle);return[lat+latOffset,lng+lngOffset];}
