import L from 'leaflet';
import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { LocateFixed, Search, ShieldCheck } from 'lucide-react';
import 'leaflet/dist/leaflet.css';
import WorkspaceShell from './WorkspaceShell.jsx';
import { useAppContext } from '../AppContext.jsx';
import { MAP_CATEGORIES } from '../domains/maps/network.js';
import { markerIcon, placeStatus, bathroomIntelligence, bathroomSignalLabel, safeText } from './MapMarkerSystem.jsx';
import './MapSurfaceV3.css';

const RADII=[1,2,5,10,25,50];
const KM_PER_MILE=1.609344;
const DEFAULT_CENTER=[20,0];
const lastLocation=()=>{try{const x=JSON.parse(localStorage.getItem('kleenest.lastLocation')||'null');return Number.isFinite(+x?.latitude)&&Number.isFinite(+x?.longitude)?[+x.latitude,+x.longitude]:null;}catch{return null;}};
const hav=(a,b,c,d)=>{const r=Math.PI/180,x=(c-a)*r,y=(d-b)*r,q=Math.sin(x/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin(y/2)**2;return 6371008.8*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));};
let originRef={current:null};
const normalize=v=>Array.isArray(v)?v.filter(Boolean):Array.isArray(v?.locations)?v.locations.filter(Boolean):Array.isArray(v?.results)?v.results.filter(Boolean):[];
const key=p=>String(p?.location_id||p?.id||'');
const label=p=>p?.name||p?.brand||p?.operator_name||'Kleenest location';

export default function MapSurfaceStable(){
 const {services,configured,loading,user}=useAppContext();
 const node=useRef(null),map=useRef(null),layer=useRef(null),seq=useRef(0),markerRefs=useRef(new Map());
 const [places,setPlaces]=useState([]),[origin,setOrigin]=useState(lastLocation),[radius,setRadius]=useState(5),[category,setCategory]=useState('all'),[search,setSearch]=useState(''),[status,setStatus]=useState('Getting your location…'),[busy,setBusy]=useState(false),[selectedId,setSelectedId]=useState('');
 const visible=useMemo(()=>places.filter(p=>{if(category!=='all'&&String(p.category||'')!==category)return false;const q=search.trim().toLowerCase();if(q&&!`${p.name||''} ${p.brand||''} ${p.operator_name||''} ${p.address||''} ${p.city||''} ${p.category||''}`.toLowerCase().includes(q))return false;const d=origin?hav(origin[0],origin[1],+p.latitude,+p.longitude):null;return d==null||d<=radius*1609.344;}),[places,origin,radius,category,search]);
 const selectPlace=p=>{const id=key(p);if(!id)return;setSelectedId(id);const marker=markerRefs.current.get(id);if(marker){const latLng=marker.getLatLng();map.current?.setView(latLng,Math.max(map.current.getZoom(),16),{animate:true});marker.openPopup();}};
 const load=async(lat,lng)=>{const id=++seq.current;originRef.current=[lat,lng];setOrigin([lat,lng]);setBusy(true);setStatus(`Searching within ${radius} mi…`);try{const rows=normalize(await services.maps.nearby({latitude:lat,longitude:lng,radiusKm:radius*KM_PER_MILE,category,search:search.trim(),discover:true,limit:500}));if(id!==seq.current)return;setPlaces(rows);setSelectedId(current=>rows.some(p=>key(p)===current)?current:'');setStatus(rows.length?`${rows.length} locations within ${radius} mi · canonical network.`:`No locations found within ${radius} mi.`);try{localStorage.setItem('kleenest.lastLocation',JSON.stringify({latitude:lat,longitude:lng,savedAt:Date.now()}));}catch{}}catch(e){if(id===seq.current){setPlaces([]);setSelectedId('');setStatus(e?.message?`Unable to refresh nearby locations: ${e.message}`:'Unable to refresh nearby locations.');}}finally{if(id===seq.current)setBusy(false);}};
 const locate=()=>{if(!navigator.geolocation){setStatus('GPS is unavailable in this browser.');return;}setBusy(true);setStatus('Getting your current location…');navigator.geolocation.getCurrentPosition(({coords})=>void load(coords.latitude,coords.longitude),()=>{const saved=lastLocation();if(saved)void load(saved[0],saved[1]);else{setBusy(false);setStatus('Location permission was unavailable. Use your browser location setting or search manually.');}},{enableHighAccuracy:true,timeout:10000,maximumAge:30000});};
 useEffect(()=>{if(configured&&!loading&&user&&!origin)locate();},[configured,loading,user?.id]);
 useEffect(()=>{if(!origin)return;const t=setTimeout(()=>void load(origin[0],origin[1]),350);return()=>clearTimeout(t);},[radius,category,search]);
 useLayoutEffect(()=>{const el=node.current;if(!el)return;let cancelled=false;let retryTimer=0;let mapInstance=null;const recover=()=>{if(mapInstance)mapInstance.invalidateSize({pan:false});};const start=()=>{if(cancelled||map.current)return;const rect=el.getBoundingClientRect();if(rect.width<20||rect.height<20){retryTimer=window.setTimeout(start,100);return;}try{if(el._leaflet_id){el._leaflet_id=null;el.replaceChildren();}const saved=lastLocation();const initial=saved||DEFAULT_CENTER;const initialZoom=saved?13:2;mapInstance=L.map(el,{zoomControl:true,preferCanvas:true,zoomAnimation:true,fadeAnimation:true}).setView(initial,initialZoom);const tiles=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,subdomains:['a','b','c'],attribution:'&copy; OpenStreetMap contributors'});tiles.on('tileerror',()=>{if(!cancelled)setStatus('Map tiles are unavailable right now; retrying map display.');});tiles.addTo(mapInstance);layer.current=L.layerGroup().addTo(mapInstance);map.current=mapInstance;const ro='ResizeObserver' in window?new ResizeObserver(recover):null;if(ro)ro.observe(el);window.addEventListener('resize',recover);window.addEventListener('pageshow',recover);window.addEventListener('visibilitychange',recover);window.setTimeout(recover,0);window.setTimeout(recover,100);window.setTimeout(recover,300);return()=>{if(ro)ro.disconnect();window.removeEventListener('resize',recover);window.removeEventListener('pageshow',recover);window.removeEventListener('visibilitychange',recover);if(mapInstance)mapInstance.remove();map.current=null;layer.current=null;markerRefs.current.clear();mapInstance=null;};}catch(e){map.current=null;layer.current=null;mapInstance=null;if(!cancelled)setStatus(e?.message?`Map initialization failed: ${e.message}`:'Map initialization failed; retrying.');retryTimer=window.setTimeout(start,500);}};const cleanup=start();return()=>{cancelled=true;window.clearTimeout(retryTimer);if(typeof cleanup==='function')cleanup();};},[]);
 useEffect(()=>{const m=map.current,l=layer.current;if(!m||!l)return;l.clearLayers();markerRefs.current.clear();if(origin)L.circleMarker(origin,{radius:7,color:'#111827',fillColor:'#fff',fillOpacity:1,weight:3}).addTo(l).bindTooltip('You are here');const points=[];visible.forEach((p,i)=>{if(!Number.isFinite(+p.latitude)||!Number.isFinite(+p.longitude))return;const id=key(p),isSelected=id===selectedId;const marker=L.marker([+p.latitude,+p.longitude],{icon:markerIcon(p,{selected:isSelected,favorite:false}),zIndexOffset:isSelected?1000:i}).addTo(l);markerRefs.current.set(id,marker);const s=placeStatus(p),b=bathroomIntelligence(p);marker.bindPopup(`<div class="map-popup"><strong>${safeText(label(p))}</strong><div class="popup-status"><span class="status-pill ${safeText(s.key)}">${safeText(s.glyph)} ${safeText(s.label)}</span>${b.hasSignal?`<span class="bathroom-pill ${safeText(b.status)}">${safeText(bathroomSignalLabel(p))}</span>`:''}</div><div>${safeText([p.address,p.city,p.state].filter(Boolean).join(', '))}</div></div>`);marker.on('click',()=>setSelectedId(id));points.push([+p.latitude,+p.longitude]);});if(points.length>1&&!selectedId)m.fitBounds(L.latLngBounds(points),{padding:[35,35],maxZoom:16});else if(points.length===1&&!selectedId)m.setView(points[0],16);else if(!points.length&&origin)m.setView(origin,radius>=25?10:13);m.invalidateSize({pan:false});},[visible,origin,radius,selectedId]);
 const statusCounts=useMemo(()=>{const x={verified:0,open:0,premium:0,reported:0,unknown:0,bathroom:0};visible.forEach(p=>{const s=placeStatus(p).key;x[s]=(x[s]||0)+1;if(bathroomIntelligence(p).hasSignal)x.bathroom++;});return x;},[visible]);
 return <WorkspaceShell><section className="page map-v3"><div className="map-heading"><div><span className="eyebrow">LOCATION INTELLIGENCE</span><h1>Find cleaner places.</h1><p>Discover canonical locations around your current position. Select a business from the results to focus its individual map icon.</p></div><button className="button primary" onClick={locate} disabled={busy}><LocateFixed size={16}/>{busy?'Locating…':'Use my location'}</button></div><div className="map-toolbar"><label><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search locations…" aria-label="Search locations"/></label><select value={radius} onChange={e=>setRadius(+e.target.value)} aria-label="Search radius">{RADII.map(x=><option key={x} value={x}>{x} miles</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Location category"><option value="all">All locations</option>{Object.entries(MAP_CATEGORIES||{}).map(([id,v])=><option key={id} value={id}>{v?.label||id}</option>)}</select><span className="map-status">{status}</span></div><section className="map-legend-panel"><div><div className="map-legend-title">Visible markers</div><div className="map-legend-group"><span>✓ Verified {statusCounts.verified}</span><span>● Open {statusCounts.open}</span><span>★ Premium {statusCounts.premium}</span><span>! Reported {statusCounts.reported}</span><span>• Other {statusCounts.unknown}</span></div></div><div><div className="map-legend-title">Bathroom signal</div><div className="map-legend-group"><span>♿/🚻 {statusCounts.bathroom} locations with bathroom intelligence</span></div></div><div className="map-legend-note"><ShieldCheck size={15}/> {selectedId?'Selected business is highlighted on the map.':'Select a business below to highlight its individual map icon.'}</div></section><div className="map-grid"><div className="map-canvas leaflet-host" ref={node} aria-label="Kleenest location map"/><aside className="map-results">{visible.map(p=>{const id=key(p);return <button type="button" className={`map-card${id===selectedId?' selected':''}`} key={id} onClick={()=>selectPlace(p)} aria-pressed={id===selectedId}><div className="map-card-head"><strong>{label(p)}</strong><span className={`status-pill ${safeText(placeStatus(p).key)}`}>{safeText(placeStatus(p).label)}</span></div><div className="map-card-meta"><span>{p.city||p.state||'Location'}</span>{bathroomIntelligence(p).hasSignal&&<span className={`bathroom-pill ${safeText(bathroomIntelligence(p).status)}`}>{safeText(bathroomSignalLabel(p))}</span>}</div></button>;})}{!visible.length&&!busy&&<div className="map-empty"><h3>No matching locations</h3><p>Try a larger radius, another category, or a different search.</p></div>}</aside></div></section></WorkspaceShell>;
}
