import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, Download, MapPin, QrCode, ShieldCheck, Star } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { supabase } from '../infrastructure/supabase/client.js';
import { useAppContext } from '../AppContext.jsx';
import WorkspaceShell from './WorkspaceShell.jsx';
import './qr-studio.css';
import './qr-landing.css';

export default function QrLandingPage({ code: codeProp = '' }){
  const params = useParams(); const code = codeProp || params.code || ''; const { user } = useAppContext(); const [data,setData]=useState(null); const [error,setError]=useState('');
  useEffect(()=>{let alive=true;(async()=>{try{const {data:row,error:e}=await supabase.rpc('get_public_qr_landing',{p_qr_code:code});if(e)throw e;if(alive)setData(row)}catch(e){if(alive)setError(e?.message||'This QR code is unavailable.')}})();return()=>{alive=false}},[code]);
  const c=data?.customization||{}; const logo=c.logo_url||data?.business_logo_url||null; const appUrl=c.app_download_url||`${window.location.origin}${import.meta.env.BASE_URL||'/'}`; const reviewUrl=c.review_url||''; const visitUrl=useMemo(()=>`/check-in?locationId=${encodeURIComponent(data?.location_id||'')}&qr=${encodeURIComponent(data?.code||code||'')}`,[data,code]);
  if(error)return <WorkspaceShell workspace="consumer"><main className="page"><section className="detail-panel qr-empty"><QrCode size={42}/><h1>QR unavailable</h1><p>{error}</p><Link className="primary" to="/map">Explore Kleenest <ArrowRight size={15}/></Link></section></main></WorkspaceShell>;
  if(!data)return <WorkspaceShell workspace="consumer"><main className="page"><section className="detail-panel qr-empty"><QrCode size={42}/><strong>Loading Kleenest experience…</strong></section></main></WorkspaceShell>;
  return <WorkspaceShell workspace="consumer"><main className="page qr-landing-page"><section className="hero qr-landing-hero"><div className="qr-landing-brand">{logo?<img src={logo} alt=""/>:<div className="qr-logo-placeholder"><QrCode size={30}/></div>}<span>{data.business_name}</span></div><span className="eyebrow">KLEENEST VERIFIED EXPERIENCE</span><h1>{data.label||'You found a Kleenest location.'}</h1><p>{data.location_name}{data.address?` · ${data.address}`:''}</p></section><section className="detail-panel qr-landing-card"><div className="panel-heading"><div><span className="eyebrow">WHAT'S NEXT</span><h2>{c.cta_label||'Use Kleenest to rate & review'}</h2></div><ShieldCheck size={22}/></div><p className="lead">Help the next visitor by verifying your visit, sharing what you found, and leaving a trusted review.</p><div className="qr-landing-actions"><Link className="primary" to={visitUrl}><CheckCircle2 size={16}/>Verify visit</Link><a className="secondary" href={appUrl}><Download size={16}/>Get the Kleenest app</a>{reviewUrl&&<a className="secondary" href={reviewUrl} target="_blank" rel="noreferrer"><Star size={16}/>Rate & review</a>}</div><div className="qr-linked-location"><MapPin size={16}/><span><strong>{data.location_name}</strong><small>{data.address||'Canonical Kleenest location'}</small></span></div></section>{!user&&<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">TRUSTED REVIEWS</span><h2>Sign in to contribute</h2></div><Star size={21}/></div><p>Sign in to complete a verified visit and publish a trusted review tied to this QR and location.</p><Link className="primary" to={`/auth?returnTo=${encodeURIComponent(visitUrl)}`}>Sign in <ArrowRight size={15}/></Link></section>}</main></WorkspaceShell>;
}
