import { Building2, ChevronDown, ChevronUp, Edit3, Plus, Save, Trash2, Power, Truck, Users, Route as RouteIcon, Wrench, Network, Megaphone, Handshake, Lock } from 'lucide-react';
import { useAppContext } from '../AppContext.jsx';
import { fleetAccessState } from '../domains/fleet/access.js';
const arr=v=>Array.isArray(v)?v:[]; const idOf=v=>v?.id||v?.business_id||v?.vehicle_id||v?.driver_id||v?.route_id||v?.maintenance_id; const labelOf=v=>v?.name||v?.title||v?.business_name||v?.unit_code||v?.email||idOf(v)||'Record';
const Field=({label,...props})=><label className="form-field"><span>{label}</span><input {...props}/></label>;
const Select=({label,children,...props})=><label className="form-field"><span>{label}</span><select {...props}>{children}</select></label>;
function Panel({title,icon:Icon,children,open,onToggle}){return <section className="detail-panel business-card"><button type="button" className="panel-heading panel-heading-button" onClick={onToggle} aria-expanded={open}><div><span className="eyebrow">OWNER CRUD</span><h2>{title}</h2></div><span className="crud-panel-icon"><Icon size={20}/>{open?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</span></button>{open&&<div className="crud-panel-body">{children}</div>}</section>}
function RecordRow({row,children}){return <div className="business-row crud-record-row"><div><strong>{labelOf(row)}</strong><span>{row?.status||row?.business_tier||row?.role||row?.vehicle_type||'Managed record'}</span></div><div className="hero-actions compact-actions">{children}</div></div>}
export default function RoleScopedCrudPanel({role='business',businessId,readOnly=false}){
 const{services,loading:authLoading,user,profile,isPlatformOwner}=useAppContext(); const fleetReadOnly=role==='fleet'&&fleetAccessState({isPlatformOwner,role:profile?.role||profile?.business_role||profile?.membership_role,businessTier:profile?.business_tier||profile?.tier}).operate===false; const locked=Boolean(readOnly||fleetReadOnly); const ready=!authLoading&&!!user&&!!profile&&!!businessId; const[open,setOpen]=useState(''); const[busy,setBusy]=useState(''); const[error,setError]=useState(''); const[message,setMessage]=useState(''); const[edit,setEdit]=useState(null); const[form,setForm]=useState({});
 const[rows,setRows]=useState({locations:[],campaigns:[],promotions:[],events:[],contests:[],qrs:[],vehicles:[],drivers:[],routes:[],maintenance:[],networks:[],networkCampaigns:[]});
 const load=async()=>{if(!ready)return;setError('');try{if(role==='business'){const rs=await Promise.allSettled([services.business.listLocations(businessId),services.business.listCampaigns(businessId),services.business.listPromotions(businessId),services.business.listEvents(businessId),services.business.listContests(businessId),services.business.listQrs(businessId)]);const val=i=>rs[i]?.status==='fulfilled'?rs[i].value:[];setRows(r=>({...r,locations:arr(val(0)),campaigns:arr(val(1)),promotions:arr(val(2)),events:arr(val(3)),contests:arr(val(4)),qrs:arr(val(5))}));if(rs.some(r=>r.status==='rejected'))setError('Some business records could not be loaded.')}else if(role==='fleet'){try{const d=await services.fleet.dashboard(businessId);setRows(r=>({...r,vehicles:arr(d?.vehicle_records??d?.vehicles),drivers:arr(d?.driver_records??d?.drivers),routes:arr(d?.route_records??d?.routes),maintenance:arr(d?.maintenance_records??d?.maintenance)}))}catch(e){setError(e.message||'Unable to load Fleet records.')}}else{try{const ns=arr(await services.enterprise.listOwnedNetworks(businessId));let cs=[];if(ns[0])try{cs=arr(await services.enterprise.listCampaigns(ns[0].id))}catch(e){setError(e.message||'Unable to load network campaigns.')}setRows(r=>({...r,networks:ns,networkCampaigns:cs}))}catch(e){setError(e.message||'Unable to load enterprise records.')}}}catch(e){setError(e.message||'Unable to load CRUD records.')}};
 useEffect(()=>{if(authLoading)return;if(ready)void load()},[authLoading,ready,role,businessId]);
 const run=async(key,fn)=>{if(!ready||locked){setError(locked?'Fleet controller access is required for this operation.':'Unable to perform operation.');return}setBusy(key);setError('');setMessage('');try{await fn();setMessage('Saved successfully.');setEdit(null);setForm({});await load();window.dispatchEvent(new CustomEvent(`kleenest:${role}-updated`));}catch(e){setError(e.message||'Operation failed.')}finally{setBusy('')}};
 const toggle=name=>{setOpen(v=>v===name?'':name);setEdit(null);setForm({})}; const start=(kind,row=null)=>{if(locked)return;setEdit({kind,id:idOf(row)});setForm(row?{...row}:{});}; const value=(k,d='')=>form[k]??d;
 const actionButton=(label,icon,onClick,kind='secondary')=><button className={kind} disabled={locked||busy!==''} onClick={onClick} title={locked?'Fleet controller access required':label}>{icon}{label}</button>;
 const fleetPanels=role==='fleet'&&<><Panel title="Vehicles" icon={Truck} open={open==='vehicles'} onToggle={()=>toggle('vehicles')}><div className="hero-actions">{locked?<span className="form-note"><Lock size={14}/> Fleet User: view-only vehicle records</span>:actionButton('Add vehicle',<Plus size={15}/>,()=>start('vehicle'),'primary')}</div>{rows.vehicles.map(r=><RecordRow key={idOf(r)} row={r}>{actionButton('Edit',<Edit3 size={15}/>,()=>start('vehicle',r))}{actionButton('Delete',<Trash2 size={15}/>,()=>run(`vehicle-delete-${idOf(r)}`,()=>services.fleet.deleteVehicle(businessId,idOf(r)))}</RecordRow>)}</Panel><Panel title="Drivers" icon={Users} open={open==='drivers'} onToggle={()=>toggle('drivers')}>{locked&&<p className="form-note"><Lock size={14}/> Fleet User: driver records are view-only.</p>}{rows.drivers.map(r=><RecordRow key={idOf(r)} row={r}>{actionButton('Edit',<Edit3 size={15}/>,()=>start('driver',r))}</RecordRow>)}</Panel><Panel title="Routes" icon={RouteIcon} open={open==='routes'} onToggle={()=>toggle('routes')}><>{locked&&<p className="form-note"><Lock size={14}/> Fleet User: route records are view-only.</p>}{rows.routes.map(r=><RecordRow key={idOf(r)} row={r}>{actionButton('Edit',<Edit3 size={15}/>,()=>start('route',r))}</RecordRow>)}</></Panel><Panel title="Maintenance" icon={Wrench} open={open==='maintenance'} onToggle={()=>toggle('maintenance')}><>{locked&&<p className="form-note"><Lock size={14}/> Fleet User: maintenance actions are view-only.</p>}{rows.maintenance.map(r=><RecordRow key={idOf(r)} row={r}>{actionButton('Complete',<Power size={15}/>,()=>run(`maintenance-${idOf(r)}`,()=>services.fleet.maintenanceComplete(businessId,idOf(r),'')))}</RecordRow>)}</></Panel></>;
 return <div>{fleetPanels}{role!=='fleet'&&<>{businessPanels}</>}{role==='enterprise'&&enterprisePanels}{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success" role="status">{message}</p>}</div>;
}