import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, CheckCircle2, Clock3, ExternalLink, LocateFixed, MapPin, Navigation, Play, Route as RouteIcon, Sparkles, Trash2, Trophy } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import WorkspaceShell from './WorkspaceShell.jsx';
import AiAssistPanel from './AiAssistPanel.jsx';
import { useAppContext } from '../AppContext.jsx';
import { locationAuthorityRoutePoint, projectLocationAuthority } from '../domains/locations/authority.js';
import './RouteSurface.css';

const DRAFT_KEY='kleenest.routeDraft.v2';
const readDraft=()=>{try{const x=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');return x&&typeof x==='object'?x:null;}catch{return null;}};
const writeDraft=x=>{try{localStorage.setItem(DRAFT_KEY,JSON.stringify(x));}catch{}};
const hasCoords=x=>Number.isFinite(+x?.latitude)&&Number.isFinite(+x?.longitude);
const asStop=(value,fallbackId='')=>{if(!value)return null;if(typeof value==='string')return{locationId:value,validation:'pending'};const projected=projectLocationAuthority({...value,location_id:value.locationId||value.location_id||fallbackId});return locationAuthorityRoutePoint(projected)||{locationId:String(value.locationId||value.id||fallbackId),name:value.name||value.brand||'Restroom stop',address:value.address||'',latitude:value.latitude,longitude:value.longitude,bathroomStatus:value.bathroomStatus||value.bathroom_status,bathroomAccess:value.bathroomAccess||value.bathroom_access,bathroomConfidence:value.bathroomConfidence??value.bathroom_confidence,bathroomEvidenceCount:value.bathroomEvidenceCount??value.bathroom_evidence_count,validation:value.validation||(hasCoords(value)?'valid':'pending')};};
const formatDistance=r=>r?.distanceKm!=null?`${Number(r.distanceKm).toFixed(1)} km`:r?.distanceMeters!=null?`${(Number(r.distanceMeters)/1609.344).toFixed(1)} mi`:'—';
const formatDuration=r=>r?.durationMinutes!=null?`${Math.round(r.durationMinutes)} min`:r?.durationSeconds!=null?`${Math.max(1,Math.round(r.durationSeconds/60))} min`:'—';
const coordinate=p=>Array.isArray(p)&&p.length>=2&&Number.isFinite(+p[0])&&Number.isFinite(+p[1])?`${+p[1]},${+p[0]}`:'';
const navigationUrl=r=>{const origin=coordinate(r?.originCoordinates),destination=coordinate(r?.destinationCoordinates);if(!origin||!destination)return '';const stops=Array.isArray(r?.stopCoordinates)?r.stopCoordinates.slice(0,-1).map(coordinate).filter(Boolean):[];const params=new URLSearchParams({api:'1',origin,destination});if(stops.length)params.set('waypoints',stops.join('|'));return`https://www.google.com/maps/dir/?${params.toString()}`;};
const startLabel=(origin,startMode)=>startMode==='gps'?'My Location':origin||'Starting location';

export default function RouteSurface(){
 const{services,configured,user}=useAppContext();const[params]=useSearchParams();const incomingStopId=params.get('add')||params.get('locationId')||params.get('destinationLocationId')||'';const fleetLocked=params.get('workspace')==='fleet'||params.get('mode')==='fleet'||params.get('locked')==='1';const draft=useMemo(readDraft,[]);const routeCache=services?.routing?.cache;
 const[origin,setOrigin]=useState(draft?.origin||'');const[startMode,setStartMode]=useState(draft?.startMode||'manual');
 const[stops,setStops]=useState(()=>{const raw=Array.isArray(draft?.stops)?draft.stops:[];const next=raw.map((s,i)=>asStop(s,draft?.stopLocationIds?.[i])).filter(s=>s?.locationId);if(incomingStopId&&!next.some(s=>s.locationId===incomingStopId))next.push(asStop(incomingStopId));return next;});
 const[route,setRoute]=useState(null),[status,setStatus]=useState('Choose where to start, then add and arrange your stops.'),[busy,setBusy]=useState('');const generation=useRef(0);
 const invalidateRoute=()=>{setRoute(null);routeCache?.clearActive?.();};
 useEffect(()=>{const active=routeCache?.getActive?.();if(active?.origin&&active?.geometry){setRoute(active);setOrigin(active.origin||'');setStartMode(active.originLabel==='My Location'?'gps':'manual');setStops(Array.isArray(active.stopLocations)?active.stopLocations:Array.isArray(active.stopLocationIds)?active.stopLocationIds.map(asStop):[]);setStatus(active.routeId?'Active route recovered.':'Built route recovered.');}},[routeCache]);
 useEffect(()=>{writeDraft({origin,startMode,stops,stopLocationIds:stops.map(s=>s.locationId),updatedAt:Date.now()});},[origin,startMode,stops]);
 useEffect(()=>{const id=incomingStopId;if(!id||!services?.locations?.getById)return;let cancelled=false;void services.locations.getById(id).then(place=>{if(cancelled||!place)return;const authority=projectLocationAuthority(place);const next=asStop({...authority,locationId:id,validation:hasCoords(authority)?'valid':'pending'},id);setStops(v=>v.some(s=>s.locationId===id)?v:[...v,next]);invalidateRoute();setStatus(`${next.name||'Stop'} added to the route.`);}).catch(()=>{});return()=>{cancelled=true;};},[incomingStopId,services?.locations?.getById]);
 const useGps=()=>{if(!navigator.geolocation)return setStatus('GPS is unavailable on this device.');setBusy('gps');navigator.geolocation.getCurrentPosition(p=>{setOrigin(`${p.coords.latitude},${p.coords.longitude}`);setStartMode('gps');invalidateRoute();setStatus('Starting point set to My Location.');setBusy('');},()=>{setStatus('Location permission was unavailable. Enter or choose a starting location instead.');setBusy('');},{enableHighAccuracy:true,timeout:12000,maximumAge:120000});};
 const removeStop=id=>{setStops(v=>v.filter(s=>s.locationId!==id));invalidateRoute();setStatus('Stop removed.');};
 const moveStop=(index,direction)=>{if(fleetLocked)return;setStops(v=>{const next=[...v],to=index+direction;if(to<0||to>=next.length)return v;[next[index],next[to]]=[next[to],next[index]];return next;});invalidateRoute();setStatus('Stop order changed. Rebuild the route to apply it.');};
 const clearStops=()=>{if(fleetLocked)return;setStops([]);invalidateRoute();setStatus('Stops cleared.');};
 const build=async()=>{if(!origin.trim())return setStatus('Choose a starting location before building the route.');if(!stops.length)return setStatus('Add at least one stop before building the route.');const invalid=stops.filter(s=>!hasCoords(s));if(invalid.length)return setStatus('A selected stop is still resolving. Wait a moment or remove and re-add it.');if(!services?.routing?.request)return setStatus('Routing service is not configured.');const gen=++generation.current;setBusy('route');setStatus(`Building the route through ${stops.length} stop${stops.length===1?'':'s'}…`);try{const data=await services.routing.request({origin:origin.trim(),stopLocationIds:stops.map(s=>s.locationId)});if(gen!==generation.current)return;if(!Array.isArray(data?.destinationCoordinates)||!hasCoords({latitude:data.destinationCoordinates[1],longitude:data.destinationCoordinates[0]}))throw new Error('The final stop could not be resolved.');const next={...data,originLabel:startLabel(origin,startMode),stopLocationIds:stops.map(s=>s.locationId),stopLocations:stops};const active=routeCache?.setActive?.(next)||next;setRoute(active);setStatus('Route ready.');}catch(e){if(gen===generation.current){setRoute(null);routeCache?.clearActive?.();setStatus(e?.message||'We could not build that route.');}}finally{if(gen===generation.current)setBusy('');}};
 const lifecycle=async action=>{if(!user)return setStatus('Sign in to share route progress.');const url=navigationUrl(route);if(action==='start'&&!url)return setStatus('This route is not ready for navigation. Rebuild it first.');if(!services?.routing?.[action])return setStatus(`Route action ${action} is not configured.`);const gen=++generation.current;setBusy(action);try{const activeStopId=stops.at(-1)?.locationId||route?.locationId||null;const result=await services.routing[action]({locationId:activeStopId,route:route?{...route,stopLocationIds:stops.map(s=>s.locationId)}:null});if(gen!==generation.current)return;const active=action==='start'?(routeCache?.getActive?.()||result?.route||route):(result?.route||route);if(active){if(action!=='start')routeCache?.setActive?.(active);setRoute(active);}setStatus(action==='start'?'Route started. Opening navigation…':action==='approaching'?'Approaching status recorded.':'Arrival recorded.');if(action==='start')window.location.assign(navigationUrl(active||route));}catch(e){if(gen===generation.current)setStatus(e?.message||`Unable to ${action} route.`);}finally{if(gen===generation.current)setBusy('');}};
 const openNavigation=()=>{const url=navigationUrl(route);if(!url)return setStatus('Build the route before opening navigation.');window.location.assign(url);};
 const aiContext=useMemo(()=>({start:startLabel(origin,startMode),stops:stops.map((s,index)=>({order:index+1,name:s.name||'Stop',address:s.address||'',bathroomStatus:s.bathroomStatus||null,bathroomAccess:s.bathroomAccess||null,confidence:s.bathroomConfidence??null,evidenceCount:s.bathroomEvidenceCount??null})),route:route?{distanceKm:route.distanceKm??null,durationMinutes:route.durationMinutes??null}:null}),[origin,startMode,stops,route]);
 return <WorkspaceShell workspace="consumer"><main className="page route-page">
  <header className="route-hero page-header"><div className="route-hero-copy"><span className="eyebrow">SMART ROUTES</span><h1>Build a route from the stops you need.</h1><p>Start from My Location or another starting place. Add stops, rearrange them, then go.</p></div><button className="button secondary route-gps" onClick={useGps} disabled={busy!==''}><LocateFixed size={17}/>{startMode==='gps'?'My Location':'Use my location'}</button></header>
  <section className="detail-panel route-planner"><div className="panel-heading route-panel-heading"><div><span className="eyebrow">PLAN</span><h2>Start + ordered stops</h2></div><Navigation size={20}/></div>
   <div className="route-fields"><label>Starting location<input value={startMode==='gps'?'My Location':origin} onChange={e=>{setStartMode('manual');setOrigin(e.target.value);invalidateRoute();}} onFocus={()=>{if(startMode==='gps'){setStartMode('manual');setOrigin('');invalidateRoute();}}} placeholder="My Location or enter a starting place"/></label></div>
   <div className="route-stop-picker"><div className="route-stop-picker-heading"><div><span className="route-field-title">Stops · {stops.length}</span><span className="route-field-help">Every place is a stop. The last stop simply ends navigation; it is not a separate destination.</span></div><div className="route-actions"><Link className="button secondary" to="/map?routeMode=stop"><MapPin size={15}/>Add stop</Link>{stops.length>0&&<button className="button secondary" onClick={clearStops} disabled={fleetLocked}><Trash2 size={15}/>Clear stops</button>}</div></div>
    {stops.length===0?<div className="stop-empty"><MapPin size={18}/><span>No stops selected yet.</span></div>:<div className="route-stop-list">{stops.map((s,i)=><div className="route-stop" key={s.locationId}><span className="route-stop-number">{i+1}</span><div className="route-stop-main"><strong>{s.name||'Stop'}</strong>{s.address&&<small>{s.address}</small>}</div><div className="route-stop-order" aria-label={`Reorder ${s.name||'stop'}`}><button className="icon-button" type="button" onClick={()=>moveStop(i,-1)} disabled={fleetLocked||busy!==''||i===0} aria-label="Move stop up"><ArrowUp size={15}/></button><button className="icon-button" type="button" onClick={()=>moveStop(i,1)} disabled={fleetLocked||busy!==''||i===stops.length-1} aria-label="Move stop down"><ArrowDown size={15}/></button><button className="icon-button" type="button" onClick={()=>removeStop(s.locationId)} disabled={busy!==''||fleetLocked} aria-label="Remove stop"><Trash2 size={15}/></button></div></div>)}</div>}
   </div>{stops.length>0&&user&&<AiAssistPanel task="route_plan" context={aiContext} title="Route recommendation" description="Only information that helps with these stops and their order." instruction="Answer only the route-planning question shown by the supplied start, ordered stops, restroom reliability facts, and route metrics. Be concise: 2 to 4 short sentences, maximum 80 words. Lead with the useful recommendation. Mention uncertainty only when it changes the recommendation. Do not explain your framework, repeat the full context, discuss unrelated data gaps, invent traffic or travel times, or propose changes outside stop order/reliability."/>}<div className="route-actions"><button className="button primary route-build" disabled={!configured||busy!==''||!origin.trim()||stops.length===0} onClick={()=>void build()}><Navigation size={16}/>{busy==='route'?'Building route…':'Build my route'}</button></div>{fleetLocked&&<div className="route-status"><RouteIcon size={16}/>Fleet dispatch order is locked and cannot be changed.</div>}<div className="route-status" role="status"><Sparkles size={16}/>{status}</div>
  </section>
  {route&&<><section className="detail-panel route-result"><div className="panel-heading"><div><span className="eyebrow">ROUTE READY</span><h2>{route.originLabel||startLabel(origin,startMode)} → {stops.at(-1)?.name||'Final stop'}</h2></div><RouteIcon size={22}/></div><div className="route-metrics"><div className="metric-card"><strong>{formatDistance(route)}</strong><span>distance</span></div><div className="metric-card"><strong>{formatDuration(route)}</strong><span>estimated time</span></div><div className="metric-card"><strong>{stops.length}</strong><span>stops</span></div></div><div className="route-actions route-result-actions"><Link className="button secondary" to="/map?routePreview=active"><MapPin size={15}/>View route map</Link><button className="button primary" onClick={()=>void lifecycle('start')} disabled={busy!==''}><Play size={15}/>{busy==='start'?'Starting…':'Start route'}</button><button className="button secondary" onClick={()=>void lifecycle('approaching')} disabled={busy!==''}><MapPin size={15}/>Approaching</button><button className="button secondary" onClick={()=>void lifecycle('arrived')} disabled={busy!==''}><CheckCircle2 size={15}/>Arrived</button><button className="button secondary" onClick={openNavigation}><ExternalLink size={15}/>Open navigation</button><Link className="button secondary" to="/games"><Trophy size={15}/>Trust Quests</Link></div></section>{Array.isArray(route.steps)&&route.steps.length>0&&<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">YOUR TRIP</span><h2>Turn-by-turn</h2></div><Clock3 size={21}/></div><ol className="route-steps">{route.steps.slice(0,30).map((s,i)=><li key={`${i}-${s.instruction}`}><strong>{i+1}</strong><div><span>{s.instruction}</span><small>{s.distanceMeters!=null?`${Math.round(s.distanceMeters)} m`:''}{s.durationSeconds!=null?` · ${Math.max(1,Math.round(s.durationSeconds/60))} min`:''}</small></div></li>)}</ol></section>}</>}
 </main></WorkspaceShell>;
}
