import { useEffect, useState } from 'react';
import { CheckCircle2, Navigation, Trophy } from 'lucide-react';
import { Link } from 'react-router-dom';
import WorkspaceShell from './WorkspaceShell.jsx';
import { useAppContext } from '../AppContext.jsx';

const DRAFT_KEY='kleenest.routeDraft.v1';
function draft(){try{return JSON.parse(localStorage.getItem(DRAFT_KEY)||'null')||{};}catch{return{};}}
export default function RouteOutcomePage(){const{services,user}=useAppContext();const[d,setD]=useState(()=>draft()),[route,setRoute]=useState(null),[routeId,setRouteId]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState('');useEffect(()=>setD(draft()),[]);
 const build=async()=>{if(!d.origin)throw new Error('Build a route first.');setBusy('build');setError('');try{const r=await services.routing.request({origin:d.origin,destination:d.destination||'',locationId:d.stopLocationIds?.at(-1)||null,stopLocationIds:d.stopLocationIds||[]});setRoute(r);return r}catch(e){setError(e?.message||'Unable to resolve the saved route.')}finally{setBusy('')}};
 const persist=async()=>{setBusy('persist');setError('');try{const r=route||await build();if(!r)return;const saved=await services.routing.persist({name:d.name||'My Kleenest route',route:r,stopsCount:d.stopLocationIds?.length||0});setRoute(saved);setRouteId(String(saved.routeId));}catch(e){setError(e?.message||'Unable to persist the route.')}finally{setBusy('')}};
 const complete=async()=>{setBusy('complete');setError('');try{if(!routeId)await persist();if(!routeId)return;const value=await services.routing.complete(routeId);setResult(value);}catch(e){setError(e?.message||'Unable to complete the route.')}finally{setBusy('')}};
 if(!user)return <WorkspaceShell workspace="consumer"><section className="empty-state"><h2>Sign in to complete a route</h2><Link className="primary" to="/auth">Sign in</Link></section></WorkspaceShell>;
 return <WorkspaceShell workspace="consumer"><main className="page"><div className="page-header"><div><span className="eyebrow">ROUTE OUTCOME</span><h1>Finish the route you planned.</h1><p>Turn the route draft into an authoritative route record, then complete it for progression credit.</p></div><Link className="secondary" to="/route"><Navigation size={16}/>Back to planner</Link></div>{error&&<p className="form-error" role="alert">{error}</p>}<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">SAVED DRAFT</span><h2>{d.name||'My Kleenest route'}</h2></div><Navigation size={22}/></div><div className="detail-grid"><div className="metric-card"><strong>{d.origin||'—'}</strong><span>Starting point</span></div><div className="metric-card"><strong>{d.destination||`${d.stopLocationIds?.length||0} selected stop(s)`}</strong><span>Destination</span></div><div className="metric-card"><strong>{d.stopLocationIds?.length||0}</strong><span>Restroom stops</span></div></div><div className="hero-actions"><button className="primary" disabled={busy!==''} onClick={build}>{busy==='build'?'Resolving…':'Resolve route'}</button><button className="secondary" disabled={busy!==''||!route} onClick={persist}>{busy==='persist'?'Saving…':'Save route'}</button><button className="secondary" disabled={busy!==''||!routeId} onClick={complete}><Trophy size={16}/>{busy==='complete'?'Completing…':'Complete route'}</button></div></section>{route&&<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">AUTHORITATIVE ROUTE</span><h2>Route resolved</h2></div><CheckCircle2 size={22}/></div><div className="detail-grid"><div className="metric-card"><strong>{route.distanceKm?.toFixed?.(1)||route.distanceKm||'—'} km</strong><span>Distance</span></div><div className="metric-card"><strong>{route.durationMinutes||'—'} min</strong><span>Estimated time</span></div><div className="metric-card"><strong>{routeId?'Saved':'Not saved'}</strong><span>{routeId?'Route ID '+routeId:'Save before completing'}</span></div></div></section>}{result&&<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">COMPLETE</span><h2>Route completed</h2></div><Trophy size={22}/></div><p>Progression received {result.points??0} points for this route.</p><Link className="primary" to="/play">View progression</Link></section>}</main></WorkspaceShell>}
