import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3, ExternalLink, LocateFixed, MapPin, Navigation, Play, Route as RouteIcon, Sparkles, Trash2, Trophy } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import WorkspaceShell from './WorkspaceShell.jsx';
import { useAppContext } from '../AppContext.jsx';
import { createRouteCache } from '../domains/routing/cache.js';
import './RouteSurface.css';

const DRAFT='kleenest.routeDraft.v1';
const read=()=>{try{return JSON.parse(localStorage.getItem(DRAFT)||'null')||{};}catch{return {};}};
const write=x=>{try{localStorage.setItem(DRAFT,JSON.stringify(x));}catch{}};
const coords=x=>Array.isArray(x)&&x.length>=2&&Number.isFinite(+x[0])&&Number.isFinite(+x[1])?`${+x[1]},${+x[0]}`:'';
const navUrl=r=>{const origin=coords(r?.originCoordinates),destination=coords(r?.destinationCoordinates);if(!origin||!destination)return '';const stops=Array.isArray(r?.stopCoordinates)?r.stopCoordinates.map(coords).filter(Boolean):[];const p=new URLSearchParams({api:'1',origin,destination});if(stops.length)p.set('waypoints',stops.join('|'));return `https://www.google.com/maps/dir/?${p.toString()}`;};
const valid=s=>Number.isFinite(+s?.latitude)&&Number.isFinite(+s?.longitude);
const snapshot=(p,id)=>({locationId:String(p?.location_id||p?.id||id),name:p?.name||'Restroom stop',address:p?.address||[p?.city,p?.state].filter(Boolean).join(', '),latitude:p?.latitude,longitude:p?.longitude,validation:valid(p)?'valid':'pending'});

export default function RouteSurfaceMobileFixed(){
 const {services,user,configured}=useAppContext(); const [params]=useSearchParams(); const locationId=params.get('locationId')||''; const draft=useMemo(read,[]); const [origin,setOrigin]=useState(params.get('origin')||draft.origin||''); const [destination,setDestination]=useState(params.get('destination')||draft.destination||''); const [stops,setStops]=useState(()=>{const s=Array.isArray(draft.stops)?draft.stops.map(x=>snapshot(x,x?.locationId)).filter(x=>x.locationId):[];return locationId&&!s.some(x=>x.locationId===locationId)?[...s,{locationId, name:'Restroom stop',validation:'pending'}]:s;}); const [route,setRoute]=useState(null); const [status,setStatus]=useState(locationId?'Restroom stop selected. Build your route when ready.':'Set a starting point and destination.'); const [busy,setBusy]=useState('');
 useEffect(()=>{write({...read(),origin,destination,stops,stopLocationIds:stops.map(x=>x.locationId),updatedAt:Date.now()});},[origin,destination,stops]);
 useEffect(()=>{if(!locationId||!services?.locations?.getById)return;let cancelled=false;services.locations.getById(locationId).then(p=>{if(!cancelled&&p)setStops(v=>v.map(s=>s.locationId===locationId?{...snapshot(p,locationId),validation:valid(p)?'valid':'stale'}:s));}).catch(()=>{});return()=>{cancelled=true;};},[locationId,services?.locations?.getById]);
 const gps=()=>{if(!navigator.geolocation)return setStatus('Location services are unavailable.');setBusy('gps');navigator.geolocation.getCurrentPosition(p=>{setOrigin(`${p.coords.latitude},${p.coords.longitude}`);setStatus('Starting point updated.');setBusy('');},()=>{setStatus('Location permission was unavailable.');setBusy('');},{enableHighAccuracy:true,timeout:12000,maximumAge:120000});};
 const remove=id=>{setStops(v=>v.filter(s=>s.locationId!==id));setRoute(null);};
 const build=async()=>{if(!origin.trim())return setStatus('Enter a starting point first.');if(!destination.trim()&&!stops.length)return setStatus('Add a destination or a restroom stop.');if(stops.some(s=>!valid(s)))return setStatus('A selected stop is still resolving.');if(!services?.routing?.request)return setStatus('Routing service is not configured.');setBusy('build');setStatus('Building your route…');try{const r=await services.routing.request({origin:origin.trim(),destination:destination.trim(),locationId:stops.at(-1)?.locationId||null,stopLocationIds:stops.map(s=>s.locationId)});setRoute(r);createRouteCache().setActive?.(r);setStatus('Route ready.');}catch(e){setRoute(null);setStatus(e?.message||'Unable to build the route.');}finally{setBusy('');}};
 const start=async()=>{if(!route)return setStatus('Build the route first.');const url=navUrl(route);if(!url)return setStatus('This route has no usable GPS destination.');if(!user)return setStatus('Sign in to start a saved route.');setBusy('start');try{if(services?.routing?.start)await services.routing.start({locationId:route.locationId||stops.at(-1)?.locationId||null,route});setStatus('Route started. Opening navigation…');window.location.assign(url);}catch(e){setBusy('');setStatus(e?.message||'Unable to start the route.');}};
 const mark=async action=>{if(!route||!user)return setStatus('Sign in to record route progress.');setBusy(action);try{const fn=services?.routing?.[action];if(typeof fn!=='function')throw new Error(`Route action ${action} is not configured.`);await fn({locationId:route.locationId||stops.at(-1)?.locationId||null,route});setStatus(action==='approaching'?'Approaching status recorded.':'Arrival recorded.');}catch(e){setStatus(e?.message||`Unable to ${action} route.`);}finally{setBusy('');}};
 return <WorkspaceShell workspace="consumer"><main className="page route-page"><header className="route-hero page-header"><div className="route-hero-copy"><span className="eyebrow">SMART ROUTES</span><h1>Plan the trip, not just the destination.</h1><p>Build a route around where you are going and the restroom stops that make the trip easier.</p></div><button className="button secondary route-gps" onClick={gps} disabled={!!busy}><LocateFixed size={17}/>Use my location</button></header>
 <section className="detail-panel route-planner"><div className="panel-heading"><div><span className="eyebrow">PLAN</span><h2>Where are you starting and going?</h2></div><Navigation size={20}/></div><div className="route-fields"><label>Starting point<input value={origin} onChange={e=>setOrigin(e.target.value)} placeholder="Current location or address"/></label><label>Destination <span className="muted">optional when stops are selected</span><input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Where are you going?"/></label></div><div className="route-stop-picker"><div className="route-stop-picker-heading"><div><span className="route-field-title">Restroom stops · {stops.length}</span><span className="route-field-help">Choose individual places from the map.</span></div><Link className="button secondary" to="/map"><MapPin size={15}/>Add from map</Link></div>{stops.length?<div className="route-stop-list">{stops.map((s,i)=><div className="route-stop" key={s.locationId}><span className="route-stop-number">{i+1}</span><div className="route-stop-main"><strong>{s.name}</strong>{s.address&&<small>{s.address}</small>}</div><button className="icon-button" onClick={()=>remove(s.locationId)} aria-label="Remove stop"><Trash2 size={15}/></button></div>)}</div>:<div className="stop-empty"><MapPin size={18}/><span>No restroom stops selected.</span></div>}</div><button className="button primary route-build" onClick={()=>void build()} disabled={!!busy||!configured}><Navigation size={16}/>{busy==='build'?'Building route…':'Build my route'}</button><div className="route-status" role="status"><Sparkles size={16}/>{status}</div></section>
 {route&&<section className="detail-panel route-result"><div className="panel-heading"><div><span className="eyebrow">ROUTE READY</span><h2>{route.origin||origin} → {route.destination||destination||stops.at(-1)?.name||'Selected destination'}</h2></div><RouteIcon size={22}/></div><div className="route-metrics"><div className="metric-card"><strong>{route.distanceKm!=null?`${Number(route.distanceKm).toFixed(1)} km`:'—'}</strong><span>distance</span></div><div className="metric-card"><strong>{route.durationMinutes!=null?`${Math.round(route.durationMinutes)} min`:'—'}</strong><span>estimated time</span></div><div className="metric-card"><strong>{stops.length}</strong><span>restroom stops</span></div></div><div className="route-actions route-result-actions"><button className="button primary" onClick={()=>void start()} disabled={!!busy}><Play size={15}/>Start route</button><button className="button secondary" onClick={()=>void mark('approaching')} disabled={!!busy}><MapPin size={15}/>Approaching</button><button className="button secondary" onClick={()=>void mark('arrived')} disabled={!!busy}><CheckCircle2 size={15}/>Arrived</button><button className="button secondary" onClick={()=>{const u=navUrl(route);if(u)window.location.assign(u);}}><ExternalLink size={15}/>Open navigation</button><Link className="button secondary" to="/games"><Trophy size={15}/>Trust Quests</Link></div></section>}
 {route?.steps?.length>0&&<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">YOUR TRIP</span><h2>Turn-by-turn</h2></div><Clock3 size={21}/></div><ol className="route-steps">{route.steps.slice(0,30).map((s,i)=><li key={`${i}-${s.instruction}`}><strong>{i+1}</strong><div><span>{s.instruction}</span><small>{s.distanceMeters!=null?`${Math.round(s.distanceMeters)} m`:''}</small></div></li>)}</ol></section>}</main></WorkspaceShell>;
}
