import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, CheckCircle2, Clock3, ExternalLink, LocateFixed, MapPin, Navigation, Play, Route as RouteIcon, Sparkles, Trash2, Trophy } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import WorkspaceShell from './WorkspaceShell.jsx';
import AiAssistPanel from './AiAssistPanel.jsx';
import { useAppContext } from '../AppContext.jsx';
import { locationAuthorityRoutePoint, projectLocationAuthority } from '../domains/locations/authority.js';
import './RouteSurface.css';

const DRAFT_KEY='kleenest.routeDraft.v1';
const readDraft=()=>{try{const x=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');return x&&typeof x==='object'?x:null;}catch{return null;}};
const writeDraft=x=>{try{localStorage.setItem(DRAFT_KEY,JSON.stringify(x));}catch{}};
const hasCoords=x=>Number.isFinite(+x?.latitude)&&Number.isFinite(+x?.longitude);
const asStop=(value,fallbackId='')=>{if(!value)return null;if(typeof value==='string')return{locationId:value,validation:'pending'};const projected=projectLocationAuthority({...value,location_id:value.locationId||value.location_id||fallbackId});return locationAuthorityRoutePoint(projected)||{locationId:String(value.locationId||value.id||fallbackId),name:value.name||value.brand||'Restroom stop',address:value.address||'',latitude:value.latitude,longitude:value.longitude,bathroomStatus:value.bathroomStatus||value.bathroom_status,bathroomAccess:value.bathroomAccess||value.bathroom_access,bathroomConfidence:value.bathroomConfidence??value.bathroom_confidence,bathroomEvidenceCount:value.bathroomEvidenceCount??value.bathroom_evidence_count,validation:value.validation||(hasCoords(value)?'valid':'pending')};};
const formatDistance=r=>r?.distanceKm!=null?`${Number(r.distanceKm).toFixed(1)} km`:r?.distanceMeters!=null?`${(Number(r.distanceMeters)/1609.344).toFixed(1)} mi`:'—';
const formatDuration=r=>r?.durationMinutes!=null?`${Math.round(r.durationMinutes)} min`:r?.durationSeconds!=null?`${Math.max(1,Math.round(r.durationSeconds/60))} min`:'—';
const coordinate=p=>Array.isArray(p)&&p.length>=2&&Number.isFinite(+p[0])&&Number.isFinite(+p[1])?`${+p[1]},${+p[0]}`:'';
const navigationUrl=r=>{const origin=coordinate(r?.originCoordinates),destination=coordinate(r?.destinationCoordinates);if(!origin||!destination)return '';const stops=Array.isArray(r?.stopCoordinates)?r.stopCoordinates.map(coordinate).filter(Boolean):[];const params=new URLSearchParams({api:'1',origin,destination});if(stops.length)params.set('waypoints',stops.join('|'));return`https://www.google.com/maps/dir/?${params.toString()}`;};

export default function RouteSurface(){
 const{services,configured,user}=useAppContext();const[params]=useSearchParams();const initialDestinationId=params.get('destinationLocationId')||params.get('locationId')||'';const addId=params.get('add')||'';const fleetLocked=params.get('workspace')==='fleet'||params.get('mode')==='fleet'||params.get('locked')==='1';const draft=useMemo(readDraft,[]);const routeCache=services?.routing?.cache;
 const[origin,setOrigin]=useState(params.get('origin')||draft?.origin||'');const[destination,setDestination]=useState(params.get('destination')||draft?.destination||'');const[destinationPlace,setDestinationPlace]=useState(null);
 const[stops,setStops]=useState(()=>{const raw=Array.isArray(draft?.stops)?draft.stops:[];const next=raw.map((s,i)=>asStop(s,draft?.stopLocationIds?.[i])).filter(s=>s?.locationId);if(addId&&!next.some(s=>s.locationId===addId))next.push(asStop(addId));return initialDestinationId?next.filter(s=>s.locationId!==initialDestinationId):next;});
 const[route,setRoute]=useState(null),[status,setStatus]=useState('Start with where you are going, then add restroom stops from the map.'),[busy,setBusy]=useState('');const generation=useRef(0);
 useEffect(()=>{const active=routeCache?.getActive?.();if(active?.routeId){setRoute(active);setOrigin(active.origin||'');setDestination(active.destination||'');setStatus('Active route recovered.');}},[routeCache]);
 useEffect(()=>{writeDraft({...readDraft(),origin,destination,stops,stopLocationIds:stops.map(s=>s.locationId),updatedAt:Date.now()});},[origin,destination,stops]);
 useEffect(()=>{const id=initialDestinationId||addId;if(!id||!services?.locations?.getById)return;let cancelled=false;void services.locations.getById(id).then(place=>{if(cancelled||!place)return;const authority=projectLocationAuthority(place);const next=asStop({...authority,locationId:id,validation:hasCoords(authority)?'valid':'pending'},id);if(initialDestinationId){setDestinationPlace(next);setDestination(next.name||next.address||'Selected destination');setStops(v=>v.filter(s=>s.locationId!==id));setStatus(`${next.name||'Location'} selected as the destination.`);}else if(addId){setStops(v=>v.some(s=>s.locationId===id)?v:[...v,next]);setStatus(`${next.name||'Restroom stop'} added to the route.`);}}).catch(()=>{});return()=>{cancelled=true;};},[initialDestinationId,addId,services?.locations?.getById]);
 const useGps=()=>{if(!navigator.geolocation)return setStatus('GPS is unavailable on this device.');setBusy('gps');navigator.geolocation.getCurrentPosition(p=>{setOrigin(`${p.coords.latitude},${p.coords.longitude}`);setRoute(null);setStatus('Starting point updated.');setBusy('');},()=>{setStatus('Location permission was unavailable. Enter a starting address instead.');setBusy('');},{enableHighAccuracy:true,timeout:12000,maximumAge:120000});};
 const removeStop=id=>{setStops(v=>v.filter(s=>s.locationId!==id));setRoute(null);setStatus('Restroom stop removed.');};
 const moveStop=(index,direction)=>{if(fleetLocked)return;setStops(v=>{const next=[...v],to=index+direction;if(to<0||to>=next.length)return v;[next[index],next[to]]=[next[to],next[index]];return next;});setRoute(null);setStatus('Stop order changed. Rebuild the route to apply the new order.');};
 const clearStops=()=>{if(fleetLocked)return;setStops([]);setRoute(null);setStatus('Restroom stops cleared.');};
 const build=async()=>{if(!origin.trim())return setStatus('Enter a starting point before building the route.');if(!destination.trim()&&!destinationPlace)return setStatus('Choose a destination before building the route. Restroom stops are waypoints, not the destination.');const invalid=stops.filter(s=>!hasCoords(s));if(invalid.length)return setStatus('A selected stop is still resolving. Wait a moment or remove and re-add it.');if(!services?.routing?.request)return setStatus('Routing service is not configured.');const gen=++generation.current;setBusy('route');setStatus(`Building the route${stops.length?` through ${stops.length} restroom stop${stops.length===1?'':'s'}`:''}…`);try{const data=await services.routing.request({origin:origin.trim(),destination:destination.trim(),locationId:destinationPlace?.locationId||initialDestinationId||null,stopLocationIds:stops.map(s=>s.locationId)});if(gen!==generation.current)return;if(!Array.isArray(data?.destinationCoordinates)||!hasCoords({latitude:data.destinationCoordinates[1],longitude:data.destinationCoordinates[0]}))throw new Error('The destination could not be resolved to GPS coordinates.');const next={...data,stopLocationIds:data.stopLocationIds||stops.map(s=>s.locationId),destinationLocationId:destinationPlace?.locationId||initialDestinationId||null,stopLocations:stops};setRoute(next);routeCache?.setActive?.(next);setStatus('Route ready.');}catch(e){if(gen===generation.current){setRoute(null);setStatus(e?.message||'We could not build that route.');}}finally{if(gen===generation.current)setBusy('');}};
 const lifecycle=async action=>{if(!user)return setStatus('Sign in to share route progress.');const url=navigationUrl(route);if(action==='start'&&!url)return setStatus('This route has no usable GPS destination. Rebuild the route first.');if(!services?.routing?.[action])return setStatus(`Route action ${action} is not configured.`);const gen=++generation.current;setBusy(action);try{const result=await services.routing[action]({locationId:destinationPlace?.locationId||route?.destinationLocationId||route?.locationId||null,route:route?{...route,stopLocationIds:stops.map(s=>s.locationId)}:null});if(gen!==generation.current)return;const active=result?.route||route;if(active){setRoute(active);routeCache?.setActive?.(active);}setStatus(action==='start'?'Route started. Opening navigation…':action==='approaching'?'Approaching status recorded.':'Arrival recorded.');if(action==='start')window.location.assign(navigationUrl(active||route));}catch(e){if(gen===generation.current)setStatus(e?.message||`Unable to ${action} route.`);}finally{if(gen===generation.current)setBusy('');}};
 const openNavigation=()=>{const url=navigationUrl(route);if(!url)return setStatus('Build a route with a resolved destination before opening navigation.');window.location.assign(url);};
 return <WorkspaceShell workspace="consumer"><main className="page route-page">
  <header className="route-hero page-header"><div className="route-hero-copy"><span className="eyebrow">SMART ROUTES</span><h1>Plan the trip, not just the destination.</h1><p>Choose one destination. Add restroom stops as waypoints, then arrange them in the order you want.</p></div><button className="button secondary route-gps" onClick={useGps} disabled={busy!==''}><LocateFixed size={17}/>Use my location</button></header>
  <section className="detail-panel route-planner"><div className="panel-heading route-panel-heading"><div><span className="eyebrow">PLAN</span><h2>Where are you starting and going?</h2></div><Navigation size={20}/></div>
   <div className="route-fields"><label>Starting point<input value={origin} onChange={e=>{setOrigin(e.target.value);setRoute(null);}} placeholder="Current location or address"/></label><label>Destination<input value={destination} onChange={e=>{setDestination(e.target.value);setDestinationPlace(null);setRoute(null);}} placeholder="Choose a destination"/><span className="muted">The chosen location is the destination. It is never duplicated as a restroom stop.</span></label></div>
   <div className="route-stop-picker"><div className="route-stop-picker-heading"><div><span className="route-field-title">Restroom stops · {stops.length}</span><span className="route-field-help">Stops are waypoints. Add them from the map and arrange them before building.</span></div><div className="route-actions"><Link className="button secondary" to="/map?routeMode=stop"><MapPin size={15}/>Add location / stop</Link>{stops.length>0&&<button className="button secondary" onClick={clearStops} disabled={fleetLocked}><Trash2 size={15}/>Clear stops</button>}</div></div>
    {stops.length===0?<div className="stop-empty"><MapPin size={18}/><span>No restroom stops selected yet.</span></div>:<div className="route-stop-list">{stops.map((s,i)=><div className="route-stop" key={s.locationId}><span className="route-stop-number">{i+1}</span><div className="route-stop-main"><strong>{s.name||'Restroom stop'}</strong>{s.address&&<small>{s.address}</small>}</div><div className="route-stop-order" aria-label={`Reorder ${s.name||'stop'}`}><button className="icon-button" type="button" onClick={()=>moveStop(i,-1)} disabled={fleetLocked||busy!==''||i===0} aria-label="Move stop up"><ArrowUp size={15}/></button><button className="icon-button" type="button" onClick={()=>moveStop(i,1)} disabled={fleetLocked||busy!==''||i===stops.length-1} aria-label="Move stop down"><ArrowDown size={15}/></button><button className="icon-button" type="button" onClick={()=>removeStop(s.locationId)} disabled={busy!==''||fleetLocked} aria-label="Remove stop"><Trash2 size={15}/></button></div></div>)}</div>}
   </div>{stops.length>0&&user&&<AiAssistPanel task="route_plan" context={{origin,destination:destinationPlace||destination,stops,route}} title="Route planning copilot" description="Explains the tradeoffs in your selected restroom stops using their Kleenest trust and route facts." instruction="Suggest how to think about stop order and reliability. Do not invent traffic or travel times, and do not change the route automatically."/>}<div className="route-actions"><button className="button primary route-build" disabled={!configured||busy!==''||!origin.trim()||(!destination.trim()&&!destinationPlace)} onClick={()=>void build()}><Navigation size={16}/>{busy==='route'?'Building route…':'Build my route'}</button></div>{fleetLocked&&<div className="route-status"><RouteIcon size={16}/>Fleet dispatch order is locked and cannot be changed.</div>}<div className="route-status" role="status"><Sparkles size={16}/>{status}</div>
  </section>
  {route&&<><section className="detail-panel route-result"><div className="panel-heading"><div><span className="eyebrow">ROUTE READY</span><h2>{route.origin||origin} → {route.destination||destination}</h2></div><RouteIcon size={22}/></div><div className="route-metrics"><div className="metric-card"><strong>{formatDistance(route)}</strong><span>distance</span></div><div className="metric-card"><strong>{formatDuration(route)}</strong><span>estimated time</span></div><div className="metric-card"><strong>{stops.length}</strong><span>restroom stops</span></div></div><div className="route-actions route-result-actions"><button className="button primary" onClick={()=>void lifecycle('start')} disabled={busy!==''}><Play size={15}/>{busy==='start'?'Starting…':'Start route'}</button><button className="button secondary" onClick={()=>void lifecycle('approaching')} disabled={busy!==''}><MapPin size={15}/>Approaching</button><button className="button secondary" onClick={()=>void lifecycle('arrived')} disabled={busy!==''}><CheckCircle2 size={15}/>Arrived</button><button className="button secondary" onClick={openNavigation}><ExternalLink size={15}/>Open navigation</button><Link className="button secondary" to="/games"><Trophy size={15}/>Trust Quests</Link></div></section>{Array.isArray(route.steps)&&route.steps.length>0&&<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">YOUR TRIP</span><h2>Turn-by-turn</h2></div><Clock3 size={21}/></div><ol className="route-steps">{route.steps.slice(0,30).map((s,i)=><li key={`${i}-${s.instruction}`}><strong>{i+1}</strong><div><span>{s.instruction}</span><small>{s.distanceMeters!=null?`${Math.round(s.distanceMeters)} m`:''}{s.durationSeconds!=null?` · ${Math.max(1,Math.round(s.durationSeconds/60))} min`:''}</small></div></li>)}</ol></section>}</>}
 </main></WorkspaceShell>;
}
