import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, MapPin, MessageCircle, RefreshCw, Search, Send, Share2, ShieldCheck, Trophy, UserCheck, UserPlus, UserRound, UserRoundPlus, Users } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useAppContext } from '../AppContext.jsx';
import WorkspaceShell from './WorkspaceShell.jsx';

const rows=value=>Array.isArray(value)?value:[];
const name=profile=>profile?.display_name||profile?.username||'Kleenest member';
const SOCIAL_REFRESH_EVENTS=['kleenest:social-updated','kleenest:community-updated'];
const emitSocialRefresh=type=>window.dispatchEvent(new CustomEvent(type,{detail:{at:Date.now()}}));

export default function SocialPage(){
  const{services,user}=useAppContext();
  const[params,setParams]=useSearchParams();
  const[reviews,setReviews]=useState([]),[followers,setFollowers]=useState([]),[following,setFollowing]=useState([]),[feed,setFeed]=useState([]),[messages,setMessages]=useState([]);
  const[loading,setLoading]=useState(true),[error,setError]=useState(''),[action,setAction]=useState(''),[post,setPost]=useState(''),[message,setMessage]=useState('');
  const[searchTerm,setSearchTerm]=useState(''),[searchResults,setSearchResults]=useState([]),[searching,setSearching]=useState(false),[selectedProfile,setSelectedProfile]=useState(null);
  const view=params.get('view')||'feed',profileId=params.get('profile');

  const load=async()=>{setLoading(true);setError('');try{const[reviewRows,social]=await Promise.all([services.community.listRecentReviews(20),user?services.community.socialFeed({limit:30}):Promise.resolve([])]);setReviews(rows(reviewRows));setFeed(rows(social));if(user){const[a,b,m]=await Promise.all([services.community.followers({limit:50}),services.community.following({limit:50}),services.community.messages({limit:50})]);setFollowers(rows(a));setFollowing(rows(b));setMessages(rows(m));}else{setFollowers([]);setFollowing([]);setMessages([]);}}catch(e){setError(e?.message||'Community activity is temporarily unavailable.');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[user?.id]);
  useEffect(()=>{const refresh=()=>void load();const names=['kleenest:checkin-completed','kleenest:location-activity','kleenest:rewards-updated','kleenest:progression-updated',...SOCIAL_REFRESH_EVENTS];names.forEach(n=>window.addEventListener(n,refresh));return()=>names.forEach(n=>window.removeEventListener(n,refresh));},[user?.id]);
  useEffect(()=>{let active=true;if(!profileId){setSelectedProfile(null);return()=>{active=false};}services.community.profile(profileId).then(profile=>{if(active)setSelectedProfile(profile);}).catch(e=>{if(active)setError(e?.message||'Unable to load contributor profile.');});return()=>{active=false};},[profileId,services]);

  const followingIds=useMemo(()=>new Set(following.map(x=>x.following_id)),[following]);
  const friends=useMemo(()=>{const ids=new Set(following.map(x=>x.following_id));return followers.filter(x=>ids.has(x.follower_id));},[followers,following]);
  const conversations=useMemo(()=>{const map=new Map();messages.forEach(item=>{const other=item.from_id===user?.id?item.to_id:item.from_id;if(other&&!map.has(other))map.set(other,item);});return[...map.values()];},[messages,user?.id]);

  const publish=async event=>{event.preventDefault();const content=post.trim();if(!user||!content)return;setAction('Publishing…');try{await services.community.publishPost({content});setPost('');setAction('Post published.');emitSocialRefresh('kleenest:social-updated');emitSocialRefresh('kleenest:community-updated');await load();}catch(e){setAction(e?.message||'Unable to publish post.');}};
  const follow=async id=>{if(!user||!id||id===user.id)return;setAction('Updating connection…');try{await services.community.followUser(id);setAction(followingIds.has(id)?'Unfollowed contributor.':'Following contributor.');emitSocialRefresh('kleenest:social-updated');emitSocialRefresh('kleenest:community-updated');await load();if(searchTerm.trim())await runSearch(searchTerm);}catch(e){setAction(e?.message||'Unable to update connection.');}};
  const runSearch=async raw=>{if(!user)return;const q=String(raw??searchTerm).trim();setSearching(true);setError('');try{setSearchResults(await services.community.searchUsers({query:q,limit:30}));}catch(e){setError(e?.message||'Unable to search contributors.');}finally{setSearching(false);}};
  const sendMessage=async event=>{event.preventDefault();const recipient=params.get('to');const content=message.trim();if(!user||!recipient||!content)return;setAction('Sending…');try{await services.community.sendMessage({toId:recipient,content});setMessage('');setAction('Message sent.');emitSocialRefresh('kleenest:social-updated');await load();}catch(e){setAction(e?.message||'Unable to send message.');}};
  const profileHref=id=>`/social?profile=${encodeURIComponent(id)}`;

  return <WorkspaceShell workspace="consumer"><main className="page community-page">
    <div className="page-header"><div><span className="eyebrow">KLEENEST COMMUNITY</span><h1>Social network</h1><p>Find contributors, follow trusted reviewers, share discoveries, and keep people connected to places.</p></div><div className="hero-actions"><button className="secondary" onClick={load} disabled={loading}><RefreshCw size={16}/>Refresh</button><Link className="secondary" to="/map"><MapPin size={16}/>Explore map</Link></div></div>
    {action&&<div className="state success" role="status">{action}</div>}{error&&<div className="state error" role="alert">{error}<button className="secondary" onClick={load}>Retry</button></div>}
    <section className="social-capability-grid"><button className="social-capability-card" onClick={()=>setParams({view:'followers'})}><Users size={20}/><strong>Followers</strong><b>{followers.length}</b><span>People following your activity.</span></button><button className="social-capability-card" onClick={()=>setParams({view:'following'})}><UserCheck size={20}/><strong>Following</strong><b>{following.length}</b><span>Contributors you follow.</span></button><button className="social-capability-card" onClick={()=>setParams({view:'friends'})}><UserRoundPlus size={20}/><strong>Friends</strong><b>{friends.length}</b><span>Mutual connections.</span></button><button className="social-capability-card" onClick={()=>setParams({view:'messages'})}><MessageCircle size={20}/><strong>Messages</strong><b>{conversations.length}</b><span>Private conversations.</span></button></section>

    {user&&<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">DISCOVER PEOPLE</span><h2>Find contributors</h2><p>Search by display name or username, then follow or open their profile.</p></div><Search size={22}/></div><form className="button-row" onSubmit={e=>{e.preventDefault();void runSearch();}}><input value={searchTerm} onChange={e=>setSearchTerm(e.target.value)} placeholder="Search contributors…"/><button className="primary" type="submit" disabled={searching}><Search size={15}/>{searching?'Searching…':'Search'}</button></form>{searchResults.length>0&&<div>{searchResults.map(profile=><div className="business-row" key={profile.id}><div><Link to={profileHref(profile.id)}><strong>{name(profile)}</strong></Link><span>{profile.username?`@${profile.username}`:'Kleenest contributor'}</span></div><div className="hero-actions"><Link className="secondary compact" to={profileHref(profile.id)}>Profile</Link><button className="primary compact" onClick={()=>void follow(profile.id)}>{profile.is_following?<UserCheck size={14}/>:<UserPlus size={14}/>} {profile.is_following?'Following':'Follow'}</button></div></div>)}</div>}</section>}

    {selectedProfile&&profileId!==user?.id&&<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">CONTRIBUTOR PROFILE</span><h2>{name(selectedProfile)}</h2><p>{selectedProfile.username?`@${selectedProfile.username}`:'Kleenest contributor'}</p></div><UserRound size={24}/></div><div className="hero-actions"><button className="primary" onClick={()=>void follow(selectedProfile.id)}>{followingIds.has(selectedProfile.id)?<UserCheck size={15}/>:<UserPlus size={15}/>} {followingIds.has(selectedProfile.id)?'Following':'Follow'}</button><Link className="secondary" to={`/social?view=messages&to=${encodeURIComponent(selectedProfile.id)}`}><MessageCircle size={15}/>Message</Link><button className="secondary" onClick={()=>setParams({view:'feed'})}>Close profile</button></div></section>}

    {user&&<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">CREATE</span><h2>Share with the network</h2></div><Share2 size={22}/></div><form className="button-row" onSubmit={publish}><input value={post} onChange={e=>setPost(e.target.value)} maxLength={1000} placeholder="Share a place, tip, verification, or community update…"/><button className="primary" type="submit" disabled={!post.trim()}><Send size={15}/>Post</button></form></section>}

    {view==='messages'&&user&&<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">MESSAGES</span><h2>Private conversations</h2></div><MessageCircle size={24}/></div>{params.get('to')&&<form className="button-row" onSubmit={sendMessage}><input value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000} placeholder="Write a message…"/><button className="primary" type="submit" disabled={!message.trim()}><Send size={15}/>Send</button></form>}{conversations.length?conversations.map(item=>{const profile=item.from_id===user.id?item.to_profile:item.from_profile;const id=item.from_id===user.id?item.to_id:item.from_id;return <article className="social-post" key={item.id}><div className="social-avatar"><UserRound size={18}/></div><div><Link to={profileHref(id)}><strong>{name(profile)}</strong></Link><span className="social-time">{item.created_at?new Date(item.created_at).toLocaleString():''}</span><p>{item.content}</p></div></article>}):<div className="empty-state"><MessageCircle size={30}/><h3>No messages yet</h3><p>Open a contributor profile to start a conversation.</p></div>}</section>}

    {view!=='messages'&&<div className="social-grid"><section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">NETWORK FEED</span><h2>Community activity</h2></div><Users size={24}/></div>{!loading&&feed.length?feed.map(item=>{const actorId=item.actor_user_id||item.user_id;return <article className="social-post" key={item.id}><div className="social-avatar"><UserRound size={18}/></div><div>{actorId?<Link to={profileHref(actorId)}><strong>{name(item.profiles)}</strong></Link>:<strong>{name(item.profiles)}</strong>}<span className="social-time">{item.created_at?new Date(item.created_at).toLocaleDateString():''}</span><p>{item.metadata?.content||item.metadata?.message||`${item.activity_type||'Community'} activity`}</p></div></article>}):<div className="empty-state"><Users size={30}/><h3>Your network feed is ready</h3><p>Verified activity and community interactions will appear here.</p></div>}</section><section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">TRUSTED REVIEWS</span><h2>Recent discoveries</h2></div><ShieldCheck size={24}/></div>{!loading&&reviews.length?reviews.slice(0,10).map(r=><article className="social-post" key={r.id}><div className="social-avatar"><span aria-label={`${r.rating??r.stars} star rating`}>★</span></div><div>{r.user_id?<Link to={profileHref(r.user_id)}><strong>{name(r.profiles)}</strong></Link>:<strong>{name(r.profiles)}</strong>}<p><b>{r.places?.name||'Kleenest location'}</b> · {r.rating??r.stars}/5</p><p>{r.body??r.comment}</p>{user&&r.user_id&&r.user_id!==user.id&&<button className="secondary compact" onClick={()=>void follow(r.user_id)}>{followingIds.has(r.user_id)?<UserCheck size={14}/>:<UserPlus size={14}/>} {followingIds.has(r.user_id)?'Following':'Follow reviewer'}</button>}</div></article>):<div className="empty-state">No trusted reviews yet.</div>}<div className="hero-actions"><Link className="primary" to="/rewards"><Trophy size={15}/>Earn rewards</Link><Link className="secondary" to="/leaderboard">Leaderboard</Link></div></section></div>}

    {(view==='followers'||view==='following'||view==='friends')&&<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">CONNECTIONS</span><h2>{view==='followers'?'Followers':view==='following'?'Following':'Friends'}</h2></div><Users size={24}/></div>{(view==='friends'?friends:view==='following'?following:followers).length?(view==='friends'?friends:view==='following'?following:followers).map(x=>{const id=x.follower_id||x.following_id,profile=x.profile||x.profiles;return <div className="business-row" key={id}><div><Link to={profileHref(id)}><strong>{name(profile)}</strong></Link><span>{view==='followers'?'Following you':'Contributor connection'}</span></div><div className="hero-actions"><Link className="secondary compact" to={profileHref(id)}>Profile</Link>{id!==user?.id&&<button className="primary compact" onClick={()=>void follow(id)}>{followingIds.has(id)?<UserCheck size={14}/>:<UserPlus size={14}/>} {followingIds.has(id)?'Following':'Follow'}</button>}</div></div>}):<div className="empty-state"><Users size={30}/><h3>Build your network</h3><p>Search contributors or follow reviewers as you discover trusted local knowledge.</p><button className="primary" onClick={()=>{setParams({view:'feed'});window.scrollTo({top:0,behavior:'smooth'});}}><ArrowRight size={15}/>Find contributors</button></div>}</section>}
  </main></WorkspaceShell>;
}
