import { useEffect, useState } from 'react';
import { useAppContext } from '../AppContext.jsx';
import WorkspaceShell from './WorkspaceShell.jsx';
import CapabilityPanel, { MetricGrid } from './CapabilityPanel.jsx';

function businessIdFrom(data) { const first = Array.isArray(data) ? data[0] : data?.businesses?.[0] || data?.data?.[0]; return first?.business_id || first?.id || null; }
function Page({ workspace, title, children }) { return <WorkspaceShell workspace={workspace}><section className="page-heading"><span className="eyebrow">Kleenest</span><h1>{title}</h1></section>{children}</WorkspaceShell>; }
export function ActivityPage() { const { services } = useAppContext(); return <Page title="Activity"><CapabilityPanel title="Your activity" description="A live view of the actions that power your Kleenest experience." load={() => services.notifications.list?.() ?? []} renderData={data => <MetricGrid items={data} />} /></Page>; }
export function PlayPage() { const { services } = useAppContext(); return <Page title="Play"><CapabilityPanel title="Progression" description="Rewards, streaks, challenges and game-ready progression capabilities." load={() => services.analytics.summary?.() ?? []} renderData={data => <MetricGrid items={data} />} /><CapabilityPanel title="Check-ins" description="Turn real-world contributions into verified progress." load={() => services.checkins.summary?.() ?? []} renderData={data => <MetricGrid items={data} />} /></Page>; }
export function CommunityPage() { const { services } = useAppContext(); return <Page title="Community"><CapabilityPanel title="Live community activity" load={() => services.live.list?.() ?? []} renderData={data => <pre className="data-preview">{JSON.stringify(data, null, 2)}</pre>} /></Page>; }
export function BusinessPage({ section = 'overview' }) { const { services } = useAppContext(); const [businesses, setBusinesses] = useState(null); useEffect(() => { void services.business.listBusinesses().then(setBusinesses).catch(() => setBusinesses([])); }, [services]); const id = businessIdFrom(businesses); const title = section === 'intelligence' ? 'Business Intelligence' : section === 'engage' ? 'Engage' : section === 'analytics' ? 'Business Analytics' : 'Business Overview'; const load = async () => { if (section === 'overview') return services.business.listBusinesses(); if (!id) return []; if (section === 'intelligence') return services.business.locationIntelligence(id); if (section === 'engage') return Promise.all([services.business.listCampaigns(id), services.business.listPromotions(id), services.business.listEvents(id)]); return Promise.all([services.business.analytics(id), services.business.reviewAnalytics(id)]); }; return <Page workspace="business" title={title}><CapabilityPanel title={title} description="Live data from the canonical Business service." load={load} renderData={data => <MetricGrid items={data} />} /></Page>; }
export function FleetPage({ section = 'operations' }) { const { services } = useAppContext(); const [businesses, setBusinesses] = useState(null); useEffect(() => { void services.business.listBusinesses().then(setBusinesses).catch(() => setBusinesses([])); }, [services]); const id = businessIdFrom(businesses); const title = ({ performance: 'Performance', opportunities: 'Opportunities', goals: 'Goals', routes: 'Routes' })[section] || 'Fleet Operations'; const load = async () => { if (!id) return []; if (section === 'opportunities') return services.fleet.opportunities(id); return services.fleet.dashboard(id); }; return <Page workspace="fleet" title={title}><CapabilityPanel title={title} description="Fleet data and actions are authorized through the audited Fleet RPC boundary." load={load} renderData={data => <MetricGrid items={data} />} /></Page>; }
export function EnterprisePage({ section = 'command' }) { const { services } = useAppContext(); const title = section === 'partners' ? 'Partners' : section === 'campaigns' ? 'Campaigns' : section === 'performance' ? 'Performance' : section === 'fleet' ? 'Fleet' : 'Enterprise Command'; return <Page workspace="enterprise" title={title}><CapabilityPanel title="Enterprise partner network" description="Existing partner-program capability exposed through the canonical service." load={() => services.partners.list()} renderData={data => <MetricGrid items={data} />} /></Page>; }
