import { createLiveNetworkService, LIVE_EVENT_TYPES } from '../live/network.js';
import { createRouteCache } from './cache.js';

const DEFAULT_ROUTER='https://router.project-osrm.org';
const GEOCODERS=[{name:'photon',url:q=>`https://photon.komoot.io/api/?limit=1&q=${encodeURIComponent(q)}`,parse:p=>p?.features?.[0]?.geometry?.coordinates},{name:'nominatim',url:q=>`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=us&q=${encodeURIComponent(q)}`,parse:p=>p?.[0]?[Number(p[0].lon),Number(p[0].lat)]:null}];
const geocodeCache=new Map();
const validCoordinates=p=>Array.isArray(p)&&p.length>=2&&Number.isFinite(+p[0])&&Number.isFinite(+p[1])&&+p[0]>=-180&&+p[0]<=180&&+p[1]>=-90&&+p[1]<=90;
const coordinates=v=>{if(Array.isArray(v)&&v.length>=2){const p=[+v[0],+v[1]];return validCoordinates(p)?p:null;}const m=String(v||'').trim().match(/^\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*$/);return m&&validCoordinates([+m[2],+m[1]])?[+m[2],+m[1]]:null;};
async function geocode(v){const direct=coordinates(v);if(direct)return direct;const q=String(v||'').trim();if(!q)return null;const key=q.toLowerCase(),cached=geocodeCache.get(key);if(cached&&Date.now()-cached.ts<86400000)return cached.point;for(const provider of GEOCODERS){try{const r=await fetch(provider.url(q),{headers:{Accept:'application/json'}});if(!r.ok)continue;const p=provider.parse(await r.json());if(validCoordinates(p)){const point=[+p[0],+p[1]];geocodeCache.set(key,{point,ts:Date.now()});return point;}}catch{}}throw new Error(`Unable to locate “${q}”. Try a fuller address, city/state, or ZIP code.`);}
async function canonicalCoordinatesMany(client,ids=[]){const unique=[...new Set(ids.filter(Boolean).map(String))];if(!unique.length)return new Map();const{data,error}=await client.from('locations').select('id,latitude,longitude').in('id',unique);if(error)throw error;const map=new Map((data||[]).map(r=>[String(r.id),validCoordinates([+r.longitude,+r.latitude])?[+r.longitude,+r.latitude]:null]));const missing=unique.filter(id=>!map.get(id));if(missing.length)throw new Error(`One or more route stops are no longer valid canonical locations: ${missing.join(', ')}.`);return map;}
async function buildGeometry(client,{origin,stopLocationIds=[],waypoints=[],legacyDestination='',legacyLocationId=null}){const start=coordinates(origin)||await geocode(origin);const ids=[...new Set(stopLocationIds.filter(Boolean).map(String))];const stopMap=await canonicalCoordinatesMany(client,ids);const stopPoints=ids.map(id=>stopMap.get(id));let ordered=[...stopPoints];if(!ordered.length&&(legacyDestination||legacyLocationId)){let legacyEnd=coordinates(legacyDestination);if(!legacyEnd&&legacyLocationId)legacyEnd=(await canonicalCoordinatesMany(client,[legacyLocationId])).get(String(legacyLocationId));if(!legacyEnd&&legacyDestination)legacyEnd=await geocode(legacyDestination);if(legacyEnd)ordered=[legacyEnd];}
 if(!ordered.length)throw new Error('Add at least one stop before building the route.');const end=ordered.at(-1),middle=ordered.slice(0,-1);const points=[start,...middle,...waypoints.map(coordinates).filter(Boolean),end];const provider=String(import.meta.env.VITE_ROUTING_PROVIDER_URL||DEFAULT_ROUTER).replace(/\/$/,'');const response=await fetch(`${provider}/route/v1/driving/${points.map(([lon,lat])=>`${lon},${lat}`).join(';')}?overview=full&geometries=geojson&steps=true`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Routing provider could not build this route.');const payload=await response.json(),r=payload?.routes?.[0];if(!r)throw new Error('No drivable route was found through those stops.');return{geometry:r.geometry,distanceMeters:r.distance,durationSeconds:r.duration,distanceKm:+(r.distance/1000).toFixed(2),durationMinutes:Math.max(1,Math.round(r.duration/60)),steps:r.legs?.flatMap(l=>l.steps||[]).map(s=>({instruction:s.maneuver?.instruction||s.name||'Continue',distanceMeters:s.distance,durationSeconds:s.duration,location:s.maneuver?.location}))||[],provider:'osrm',originCoordinates:start,destinationCoordinates:end,stopCoordinates:ordered,waypointCount:Math.max(0,points.length-2)};}
export function createRoutingService(client,{live=null,cache=null}={}){if(!client)throw new Error('Supabase client is required.');const liveService=live||createLiveNetworkService(client),routeCache=cache||createRouteCache();const resolveLocationId=(id,route)=>id||route?.locationId||route?.finalStopLocationId||route?.stopLocationIds?.at(-1)||null;const withLocation=(route,id)=>route?{...route,locationId:id}:route;const service={
async request({origin,stopLocationIds=[],waypoints=[],routeGeometry=null,offlinePackId=null,destination='',locationId=null}={}){if(!origin||(!stopLocationIds.length&&!waypoints.length&&!destination&&!locationId))throw new Error('A starting location and at least one stop are required.');const ids=[...new Set(stopLocationIds.filter(Boolean).map(String))];const g=routeGeometry||await buildGeometry(client,{origin,stopLocationIds:ids,waypoints,legacyDestination:destination,legacyLocationId:locationId});const finalStopLocationId=ids.at(-1)||locationId||null;const route={origin,originCoordinates:g.originCoordinates,destinationCoordinates:g.destinationCoordinates,stopCoordinates:g.stopCoordinates,waypoints,stopLocationIds:ids,finalStopLocationId,locationId:finalStopLocationId,geometry:g.geometry,distanceMeters:g.distanceMeters,distanceKm:g.distanceKm,durationSeconds:g.durationSeconds,durationMinutes:g.durationMinutes,steps:g.steps,waypointCount:g.waypointCount,routingProvider:g.provider,offlinePackId};routeCache.put(route);return route;},
async persist({name='My route',route,stopsCount=null}={}){const ids=[...new Set((route?.stopLocationIds||[]).filter(Boolean).map(String))];if(!validCoordinates(route?.originCoordinates)||!validCoordinates(route?.destinationCoordinates))throw new Error('A route with valid coordinates is required.');if(!ids.length)throw new Error('A route must contain at least one stop.');await canonicalCoordinatesMany(client,ids);const{data,error}=await client.rpc('create_route_plan',{p_name:name,p_start_lat:+route.originCoordinates[1],p_start_lng:+route.originCoordinates[0],p_end_lat:+route.destinationCoordinates[1],p_end_lng:+route.destinationCoordinates[0],p_distance_miles:+route.distanceMeters/1609.344,p_estimated_minutes:Math.max(0,Math.round((route.durationSeconds||0)/60)),p_stop_location_ids:ids});if(error)throw error;const id=data?.route_id||data?.id||data;if(!id)throw new Error('Route persistence returned no route ID.');const{data:stops,error:stopError}=await client.from('route_stops').select('id,route_id,location_id,stop_order,points_value,checked_in_at').eq('route_id',id).order('stop_order');if(stopError)throw stopError;if((stops||[]).length!==ids.length)throw new Error(`Persisted route stop count mismatch: expected ${ids.length}, received ${(stops||[]).length}.`);const next={...route,routeId:id,stopsCount:stopsCount??ids.length,routeStops:stops||[],routeStopIds:(stops||[]).map(s=>String(s.id))};routeCache.put(next);routeCache.setActive(next);return next;},
async recoverActive(){return routeCache.getActive?.()||null;},
async arriveStop({routeId,routeStopId,checkInId}={}){if(!routeId||!routeStopId||!checkInId)throw new Error('Route, route stop, and qualifying check-in are required.');const{data,error}=await client.rpc('arrive_route_stop',{p_route_id:routeId,p_route_stop_id:routeStopId,p_check_in_id:checkInId});if(error)throw error;if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('kleenest:route-stop-arrived',{detail:{routeId,routeStopId,checkInId,result:data}}));return data;},
async complete(routeId){if(!routeId)throw new Error('A persisted route is required.');const{data,error}=await client.rpc('complete_route',{p_route_id:routeId});if(error)throw error;routeCache.clearActive();return data;},
async start({locationId=null,route}={}){if(!route)throw new Error('A valid route is required.');const active=route.routeId?route:await this.persist({route,stopsCount:(route.stopLocationIds||[]).length});const id=resolveLocationId(locationId,active);const next=withLocation(active,id);routeCache.setActive(next);return liveService.publish({type:LIVE_EVENT_TYPES.USER_ROUTE_STARTED,locationId:id,payload:{route:next,routeId:active.routeId,routeStopIds:active.routeStopIds||[]}});},
async approaching({locationId=null,route}={}){const id=resolveLocationId(locationId,route);return liveService.publish({type:LIVE_EVENT_TYPES.USER_APPROACHING_LOCATION,locationId:id,payload:{route:withLocation(route,id)}});},
async arrived({locationId=null,route}={}){const id=resolveLocationId(locationId,route);return liveService.publish({type:LIVE_EVENT_TYPES.USER_ARRIVED,locationId:id,payload:{route:withLocation(route,id)}});},
async departed({locationId=null,route}={}){const id=resolveLocationId(locationId,route);return liveService.publish({type:LIVE_EVENT_TYPES.USER_DEPARTED,locationId:id,payload:{route:withLocation(route,id)}});}
};
service.cache=routeCache;
return Object.freeze(service);}
