import {CAPABILITIES,hasCapability} from'../domains/entitlements/access.js';
import {getProductTier,PRODUCT_TIERS} from'../architecture/productModel.js';
import {WORKSPACE_ORDER,WORKSPACES,WORKSPACE_NAVIGATION,getWorkspace,getNavigationForWorkspace} from'./workspaceNavigation.js';
import {CAPABILITY_REGISTRY} from'../architecture/capabilityRegistry.js';
export {WORKSPACE_ORDER,WORKSPACES,WORKSPACE_NAVIGATION,getWorkspace,getNavigationForWorkspace} from'./workspaceNavigation.js';
export const CAPABILITY_FOR_WORKSPACE=Object.freeze({business:CAPABILITIES.BUSINESS,fleet:CAPABILITIES.FLEET,enterprise:CAPABILITIES.ENTERPRISE,admin:'owner'});
export function canUseWorkspace(capabilities=[],workspace='consumer'){if(workspace==='consumer')return true;if(workspace==='admin')return hasCapability(capabilities,'owner');const required=CAPABILITY_FOR_WORKSPACE[workspace];return Boolean(required&&hasCapability(capabilities,required));}
export function getAvailableWorkspaces(capabilities=[]){return WORKSPACE_ORDER.filter(workspace=>canUseWorkspace(capabilities,workspace));}
export function normalizeMembership(raw={}){const source=raw?.data||raw?.entitlement||raw?.entitlements||raw;const tier=String(source?.membership_tier||source?.product_tier||source?.tier||source?.service_tier||source?.plan||'free').toLowerCase().replace(/[-\s]/g,'_');if(tier.includes('business')&&tier.includes('enterprise'))return'business_enterprise';if(tier.includes('business')&&tier.includes('fleet'))return'business_fleet';if(tier.includes('business')&&tier.includes('growth'))return'business_growth';if(tier.includes('business'))return'business_standard';if(tier.includes('admin'))return'admin';if(tier.includes('fleet'))return'fleet';if(tier.includes('enterprise'))return'enterprise';if(tier.includes('family'))return'family';if(tier.includes('premium')||tier.includes('pro'))return'premium';return'free';}
export const MEMBERSHIP_UI=Object.freeze({free:Object.freeze({label:'Free',ads:true,workspace:'consumer'}),premium:Object.freeze({label:'Premium',ads:false,workspace:'consumer'}),family:Object.freeze({label:'Family',ads:false,workspace:'consumer'}),business_standard:Object.freeze({label:'Business Standard',ads:false,workspace:'business'}),business_growth:Object.freeze({label:'Business Growth',ads:false,workspace:'business'}),business_fleet:Object.freeze({label:'Business Fleet',ads:false,workspace:'fleet'}),business_enterprise:Object.freeze({label:'Business Enterprise',ads:false,workspace:'enterprise'}),enterprise:Object.freeze({label:'Enterprise User',ads:false,workspace:'enterprise'}),fleet:Object.freeze({label:'Fleet User',ads:false,workspace:'fleet'}),admin:Object.freeze({label:'Owner Control',ads:false,workspace:'admin'})});
export function getWorkspaceForMembership(membership){return MEMBERSHIP_UI[membership]?.workspace||'consumer';}
export function resolveWorkspace(pathname='/',capabilities=[]){const path=String(pathname||'/');const candidate=path.startsWith('/admin')||path.startsWith('/owner')?'admin':path.startsWith('/enterprise')?'enterprise':path.startsWith('/fleet')?'fleet':path.startsWith('/business')?'business':'consumer';return canUseWorkspace(capabilities,candidate)?candidate:'consumer';}
export function resolveMembership(rawMembership,capabilities=[]){const parsed=normalizeMembership({tier:rawMembership});if(parsed!=='free')return parsed;if(hasCapability(capabilities,'owner'))return'admin';if(hasCapability(capabilities,CAPABILITIES.ENTERPRISE))return'enterprise';if(hasCapability(capabilities,CAPABILITIES.FLEET))return'fleet';if(hasCapability(capabilities,CAPABILITIES.BUSINESS))return'business_standard';return parsed;}
export function getWorkspaceModel({membership='free',workspace,businessId=null,capabilities=[],isPlatformOwner=false}={}){const resolvedMembership=isPlatformOwner?'admin':resolveMembership(membership,capabilities);const productTier=isPlatformOwner?{...PRODUCT_TIERS.business.enterprise,id:'owner',label:'Owner Control'}:getProductTier(resolvedMembership);const requestedWorkspace=workspace||(isPlatformOwner?'admin':getWorkspaceForMembership(resolvedMembership));const resolvedWorkspace=isPlatformOwner?'admin':(canUseWorkspace(capabilities,requestedWorkspace)?requestedWorkspace:'consumer');const effectiveCapabilities=isPlatformOwner?Array.from(new Set([...capabilities,'owner','business','fleet','enterprise'])):Array.from(new Set([...(productTier.capabilities||[]),...capabilities]));return Object.freeze({membership:resolvedMembership,membershipLabel:productTier.label||MEMBERSHIP_UI[resolvedMembership]?.label||'Free',productTier,adsEnabled:productTier.ads!==false,businessId,workspace:getWorkspace(resolvedWorkspace),availableWorkspaces:getAvailableWorkspaces(effectiveCapabilities)});}
export function getCapabilityDomainsForWorkspace(workspace){return Object.keys(CAPABILITY_REGISTRY).filter(domain=>CAPABILITY_REGISTRY[domain]?.ui?.includes(workspace)||CAPABILITY_REGISTRY[domain]?.ui?.includes('all'));}
