import{CAPABILITIES,hasCapability}from'../domains/entitlements/access.js';import{CAPABILITY_REGISTRY}from'../architecture/capabilityRegistry.js';import{getProductTier,PRODUCT_TIERS}from'../architecture/productModel.js';
export const WORKSPACE_ORDER=Object.freeze(['consumer','business','fleet','enterprise','admin']);
export const WORKSPACES=Object.freeze({consumer:Object.freeze({id:'consumer',label:'Kleenest',shortLabel:'You'}),business:Object.freeze({id:'business',label:'Business',shortLabel:'Business'}),fleet:Object.freeze({id:'fleet',label:'Fleet',shortLabel:'Fleet'}),enterprise:Object.freeze({id:'enterprise',label:'Enterprise',shortLabel:'Enterprise'}),admin:Object.freeze({id:'admin',label:'Owner Control',shortLabel:'Owner'})});
export const WORKSPACE_NAVIGATION=Object.freeze({consumer:Object.freeze([{id:'home',label:'Home',path:'/'},{id:'explore',label:'Explore',path:'/map'},{id:'routes',label:'Routes',path:'/route'},{id:'saved',label:'Saved',path:'/saved'},{id:'activity',label:'Activity',path:'/activity'},{id:'play',label:'Rewards & Play',path:'/play'},{id:'community',label:'Community',path:'/community'},{id:'notifications',label:'Notifications',path:'/notifications'},{id:'profile',label:'Profile',path:'/profile'}]),business:Object.freeze([{id:'overview',label:'Overview',path:'/business'},{id:'locations',label:'Locations',path:'/business/assets'},{id:'customers',label:'Customers',path:'/business/analytics'},{id:'promotions',label:'Promotions',path:'/business/promotions'},{id:'campaigns',label:'Campaigns',path:'/business/campaigns'},{id:'events',label:'Events',path:'/business/events'},{id:'contests',label:'Contests',path:'/business/contests'},{id:'qr',label:'QR',path:'/business/qr'},{id:'reviews',label:'Reviews',path:'/business/reviews'},{id:'analytics',label:'Analytics',path:'/business/analytics'},{id:'plan',label:'Plan & Access',path:'/business/entitlements'}]),fleet:Object.freeze([{id:'command',label:'Command',path:'/fleet'},{id:'routes',label:'Routes',path:'/fleet/routes'},{id:'operations',label:'Operations',path:'/fleet'},{id:'people',label:'People',path:'/fleet'},{id:'intelligence',label:'Intelligence',path:'/fleet/intelligence'},{id:'notifications',label:'Notifications',path:'/notifications'}]),enterprise:Object.freeze([{id:'command',label:'Command',path:'/enterprise'},{id:'networks',label:'Networks',path:'/enterprise/partners'},{id:'partners',label:'Partners',path:'/enterprise/partners'},{id:'campaigns',label:'Campaigns',path:'/enterprise/campaigns'},{id:'fleet',label:'Fleet',path:'/enterprise/fleet'},{id:'analytics',label:'Analytics',path:'/enterprise/performance'},{id:'governance',label:'Governance',path:'/enterprise/performance'}]),admin:Object.freeze([{id:'overview',label:'Overview',path:'/admin'},{id:'crud',label:'CRUD',path:'/owner/data'},{id:'capabilities',label:'Capabilities',path:'/admin/capabilities'},{id:'data',label:'Data',path:'/owner/data'},{id:'security',label:'Security',path:'/admin/maintenance'},{id:'audit',label:'Audit',path:'/owner/audit'}])});
const CAPABILITY_FOR_WORKSPACE=Object.freeze({business:CAPABILITIES.BUSINESS,fleet:CAPABILITIES.FLEET,enterprise:CAPABILITIES.ENTERPRISE,admin:'owner'});
export function canUseWorkspace(capabilities=[],workspace='consumer'){if(workspace==='consumer')return true;if(workspace==='admin')return hasCapability(capabilities,'owner');const required=CAPABILITY_FOR_WORKSPACE[workspace];return Boolean(required&&hasCapability(capabilities,required));}
export function getAvailableWorkspaces(capabilities=[]){return WORKSPACE_ORDER.filter(workspace=>canUseWorkspace(capabilities,workspace));}
export function normalizeMembership(raw={}){const source=raw?.data||raw?.entitlement||raw?.entitlements||raw;const tier=String(source?.membership_tier||source?.product_tier||source?.tier||source?.service_tier||source?.plan||'free').toLowerCase().replace(/[-\s]/g,'_');if(tier.includes('business')&&tier.includes('enterprise'))return'business_enterprise';if(tier.includes('business')&&tier.includes('fleet'))return'business_fleet';if(tier.includes('business')&&tier.includes('growth'))return'business_growth';if(tier.includes('business'))return'business_standard';if(tier.includes('admin'))return'admin';if(tier.includes('fleet'))return'fleet';if(tier.includes('enterprise'))return'enterprise';if(tier.includes('family'))return'family';if(tier.includes('premium')||tier.includes('pro'))return'premium';return'free';}
export const MEMBERSHIP_UI=Object.freeze({free:Object.freeze({label:'Free',ads:true,workspace:'consumer'}),premium:Object.freeze({label:'Premium',ads:false,workspace:'consumer'}),family:Object.freeze({label:'Family',ads:false,workspace:'consumer'}),business_standard:Object.freeze({label:'Business Standard',ads:false,workspace:'business'}),business_growth:Object.freeze({label:'Business Growth',ads:false,workspace:'business'}),business_fleet:Object.freeze({label:'Business Fleet',ads:false,workspace:'fleet'}),business_enterprise:Object.freeze({label:'Business Enterprise',ads:false,workspace:'enterprise'}),enterprise:Object.freeze({label:'Enterprise User',ads:false,workspace:'enterprise'}),fleet:Object.freeze({label:'Fleet User',ads:false,workspace:'fleet'}),admin:Object.freeze({label:'Owner Control',ads:false,workspace:'admin'})});
export function getWorkspaceForMembership(membership){return MEMBERSHIP_UI[membership]?.workspace||'consumer';}
export function getWorkspace(id='consumer'){return WORKSPACES[id]||WORKSPACES.consumer;}
export function resolveWorkspace(pathname='/',capabilities=[]){const path=String(pathname||'/');const candidate=path.startsWith('/admin')||path.startsWith('/owner')?'admin':path.startsWith('/enterprise')?'enterprise':path.startsWith('/fleet')?'fleet':path.startsWith('/business')?'business':'consumer';return canUseWorkspace(capabilities,candidate)?candidate:'consumer';}
export function resolveMembership(rawMembership,capabilities=[]){const parsed=normalizeMembership({tier:rawMembership});if(parsed!=='free')return parsed;if(hasCapability(capabilities,'owner'))return'admin';if(hasCapability(capabilities,CAPABILITIES.ENTERPRISE))return'enterprise';if(hasCapability(capabilities,CAPABILITIES.FLEET))return'fleet';if(hasCapability(capabilities,CAPABILITIES.BUSINESS))return'business_standard';return parsed;}
export function getWorkspaceModel({membership='free',workspace,businessId=null,capabilities=[],isPlatformOwner=false}={}){const resolvedMembership=isPlatformOwner?'admin':resolveMembership(membership,capabilities);const productTier=isPlatformOwner?{...PRODUCT_TIERS.business.enterprise,id:'owner',label:'Owner Control'}:getProductTier(resolvedMembership);const requestedWorkspace=workspace||(isPlatformOwner?'admin':getWorkspaceForMembership(resolvedMembership));const resolvedWorkspace=isPlatformOwner?'admin':(canUseWorkspace(capabilities,requestedWorkspace)?requestedWorkspace:'consumer');const effectiveCapabilities=isPlatformOwner?Array.from(new Set([...capabilities,'owner','business','fleet','enterprise'])):Array.from(new Set([...(productTier.capabilities||[]),...capabilities]));return Object.freeze({membership:resolvedMembership,membershipLabel:productTier.label||MEMBERSHIP_UI[resolvedMembership]?.label||'Free',productTier,adsEnabled:productTier.ads!==false,businessId,workspace:getWorkspace(resolvedWorkspace),availableWorkspaces:getAvailableWorkspaces(effectiveCapabilities)});}
export function getNavigationForWorkspace(workspace,capabilities=[]){return canUseWorkspace(capabilities,workspace)?(WORKSPACE_NAVIGATION[workspace]||[]):[];}
export function getCapabilityDomainsForWorkspace(workspace){return Object.keys(CAPABILITY_REGISTRY).filter(domain=>CAPABILITY_REGISTRY[domain]?.ui?.includes(workspace)||CAPABILITY_REGISTRY[domain]?.ui?.includes('all'));}