export const CAPABILITIES=Object.freeze({CONSUMER:'consumer',PREMIUM:'premium',FAMILY:'family',BUSINESS:'business',FLEET:'fleet',ENTERPRISE:'enterprise'});
export const USER_TIERS=Object.freeze({FREE:'free',PREMIUM:'premium',FAMILY:'family',FLEET:'fleet',ENTERPRISE:'enterprise'});
export const BUSINESS_TIERS=Object.freeze({STANDARD:'business_standard',GROWTH:'business_growth',FLEET:'business_fleet',ENTERPRISE:'business_enterprise'});
const LEGACY_ROLE_MAP=Object.freeze({user:CAPABILITIES.CONSUMER,owner:'owner',platform_admin:'owner',super_admin:'owner',admin:'owner'});
export function normalizeCapability(value){const normalized=String(value??'').trim().toLowerCase();return LEGACY_ROLE_MAP[normalized]??normalized;}
export function hasCapability(capabilities,capability){return Array.isArray(capabilities)&&capabilities.includes(normalizeCapability(capability));}
export function hasAnyCapability(capabilities,required=[]){return required.length===0||required.some(value=>hasCapability(capabilities,value));}
export function hasAllCapabilities(capabilities,required=[]){return required.every(value=>hasCapability(capabilities,value));}
export function isPlatformOwner(profile){const role=String(profile?.role??'').trim().toLowerCase();return Boolean(profile?.is_admin)||['owner','platform_admin','super_admin','admin'].includes(role);}
function normalizeTier(value){return String(value??'').trim().toLowerCase().replaceAll(' ','_').replaceAll('-','_');}
export function normalizeUserTier(value){const tier=normalizeTier(value);if(tier.includes('enterprise'))return USER_TIERS.ENTERPRISE;if(tier.includes('fleet'))return USER_TIERS.FLEET;if(tier.includes('family'))return USER_TIERS.FAMILY;if(tier.includes('premium')||tier.includes('pro'))return USER_TIERS.PREMIUM;return USER_TIERS.FREE;}
export function normalizeBusinessTier(value){const tier=normalizeTier(value);if(tier.includes('enterprise'))return BUSINESS_TIERS.ENTERPRISE;if(tier.includes('fleet'))return BUSINESS_TIERS.FLEET;if(tier.includes('growth'))return BUSINESS_TIERS.GROWTH;return BUSINESS_TIERS.STANDARD;}
function entitlementCapability(entitlement){const tier=normalizeTier(entitlement?.service_tier??entitlement?.tier??entitlement?.subscription_tier??entitlement?.tier_code);if(tier.includes('enterprise'))return CAPABILITIES.ENTERPRISE;if(tier.includes('fleet')||entitlement?.fleet_enabled||entitlement?.enterprise_fleet_enabled)return CAPABILITIES.FLEET;if(tier.includes('business'))return CAPABILITIES.BUSINESS;if(tier.includes('family'))return CAPABILITIES.FAMILY;if(tier.includes('premium')||tier.includes('pro'))return CAPABILITIES.PREMIUM;return null;}
export function evaluateProfileCapabilities(profile,entitlements=[]){const role=normalizeTier(profile?.role),tier=normalizeTier(profile?.subscription_tier);const capabilities=new Set([CAPABILITIES.CONSUMER]);if(['premium','pro'].includes(tier)||Boolean(profile?.is_premium_user))capabilities.add(CAPABILITIES.PREMIUM);if(tier.includes('family')||profile?.is_family_user)capabilities.add(CAPABILITIES.FAMILY);if(['business','owner','enterprise'].includes(role)||profile?.is_business_user||tier.includes('business'))capabilities.add(CAPABILITIES.BUSINESS);if(['fleet','owner'].includes(role)||tier.includes('fleet'))capabilities.add(CAPABILITIES.FLEET);if(['enterprise','owner'].includes(role)||tier.includes('enterprise'))capabilities.add(CAPABILITIES.ENTERPRISE);for(const entitlement of entitlements){const capability=entitlementCapability(entitlement);if(capability)capabilities.add(capability);}if(isPlatformOwner(profile)){capabilities.add('owner');capabilities.add(CAPABILITIES.BUSINESS);capabilities.add(CAPABILITIES.FLEET);capabilities.add(CAPABILITIES.ENTERPRISE);}return Object.freeze([...capabilities]);}
export function getMembershipTier(profile,entitlements=[],effectiveCapabilities=[]){if(isPlatformOwner(profile))return'admin';const capabilities=new Set([...evaluateProfileCapabilities(profile,entitlements),...(Array.isArray(effectiveCapabilities)?effectiveCapabilities:[]).map(normalizeCapability)]);if(capabilities.has(CAPABILITIES.ENTERPRISE))return USER_TIERS.ENTERPRISE;if(capabilities.has(CAPABILITIES.FLEET))return USER_TIERS.FLEET;if(capabilities.has(CAPABILITIES.BUSINESS))return'business';if(capabilities.has(CAPABILITIES.FAMILY))return USER_TIERS.FAMILY;if(capabilities.has(CAPABILITIES.PREMIUM))return USER_TIERS.PREMIUM;return USER_TIERS.FREE;}
export function shouldShowAds(profile,entitlements=[],effectiveCapabilities=[]){return getMembershipTier(profile,entitlements,effectiveCapabilities)==='free';}
export function canAccess(capabilities,required){return hasCapability(capabilities,required);}
export function canAccessWorkspace(capabilities,workspace){const map={business:CAPABILITIES.BUSINESS,fleet:CAPABILITIES.FLEET,enterprise:CAPABILITIES.ENTERPRISE};return workspace==='consumer'||workspace==='owner'||hasCapability(capabilities,map[workspace]);}
export function createEntitlementService(client){if(!client)throw new Error('Supabase client is required.');return Object.freeze({getCurrentUserEntitlements:async()=>{const{data,error}=await client.rpc('get_current_user_product_entitlements');if(error)throw error;return data??[];},recordFeatureAccess:async({featureCode,outcome,tierCode=null,destination=null,metadata={}}={})=>{if(!featureCode)throw new Error('featureCode is required.');const normalized=String(outcome??'').toLowerCase()==='blocked'?'denied':outcome;if(!['allowed','locked','denied'].includes(normalized))throw new Error('Invalid feature access outcome.');const{data,error}=await client.rpc('record_feature_access',{p_feature_code:featureCode,p_outcome:normalized,p_tier_code:tierCode,p_destination:destination,p_metadata:{...(metadata??{}),...(String(outcome)==='blocked'?{original_outcome:'blocked'}:{})}});if(error)throw error;return data;}});}
