export const CAPABILITIES=Object.freeze({CONSUMER:'consumer',PREMIUM:'premium',BUSINESS:'business',FLEET:'fleet',ENTERPRISE:'enterprise'});
const LEGACY_ROLE_MAP=Object.freeze({user:CAPABILITIES.CONSUMER,owner:'owner',platform_admin:'owner',super_admin:'owner',admin:'owner'});
export function normalizeCapability(value){const normalized=String(value??'').trim().toLowerCase();return LEGACY_ROLE_MAP[normalized]??normalized;}
export function hasCapability(capabilities,capability){return Array.isArray(capabilities)&&capabilities.includes(normalizeCapability(capability));}
export function hasAnyCapability(capabilities,required=[]){return required.length===0||required.some(value=>hasCapability(capabilities,value));}
export function hasAllCapabilities(capabilities,required=[]){return required.every(value=>hasCapability(capabilities,value));}
export function isPlatformOwner(profile){const role=String(profile?.role??'').trim().toLowerCase();return Boolean(profile?.is_admin)||['owner','platform_admin','super_admin','admin'].includes(role);}
function entitlementCapability(entitlement){const tier=String(entitlement?.service_tier??entitlement?.tier??'').trim().toLowerCase();if(tier==='enterprise')return CAPABILITIES.ENTERPRISE;if(tier==='fleet'||entitlement?.fleet_enabled||entitlement?.enterprise_fleet_enabled)return CAPABILITIES.FLEET;if(tier==='business')return CAPABILITIES.BUSINESS;if(tier==='premium')return CAPABILITIES.PREMIUM;return null;}
export function evaluateProfileCapabilities(profile,entitlements=[]){const role=String(profile?.role??'').trim().toLowerCase();const capabilities=new Set([CAPABILITIES.CONSUMER]);if(role==='premium'||(profile?.subscription_tier&&String(profile.subscription_tier).toLowerCase()!=='free'))capabilities.add(CAPABILITIES.PREMIUM);if(['business','owner','enterprise'].includes(role)||profile?.is_business_user)capabilities.add(CAPABILITIES.BUSINESS);if(['fleet','owner'].includes(role))capabilities.add(CAPABILITIES.FLEET);if(['enterprise','owner'].includes(role))capabilities.add(CAPABILITIES.ENTERPRISE);for(const entitlement of entitlements){const capability=entitlementCapability(entitlement);if(capability)capabilities.add(capability);}if(isPlatformOwner(profile))capabilities.add('owner');return Object.freeze([...capabilities]);}
export function getMembershipTier(profile,entitlements=[]){const capabilities=evaluateProfileCapabilities(profile,entitlements);if(hasCapability(capabilities,CAPABILITIES.ENTERPRISE))return 'enterprise';if(hasCapability(capabilities,CAPABILITIES.FLEET))return 'fleet';if(hasCapability(capabilities,CAPABILITIES.BUSINESS))return 'business';if(hasCapability(capabilities,CAPABILITIES.PREMIUM))return 'premium';return 'free';}
export function shouldShowAds(profile,entitlements=[]){return getMembershipTier(profile,entitlements)==='free';}
export function canAccess(capabilities,required){return hasCapability(capabilities,required);}
export function canAccessWorkspace(capabilities,workspace){const map={business:CAPABILITIES.BUSINESS,fleet:CAPABILITIES.FLEET,enterprise:CAPABILITIES.ENTERPRISE};return workspace==='consumer'||workspace==='owner'||hasCapability(capabilities,map[workspace]);}
export function createEntitlementService(client){if(!client)throw new Error('Supabase client is required.');return Object.freeze({getCurrentUserEntitlements:async()=>{const{data,error}=await client.rpc('get_current_user_product_entitlements');if(error)throw error;return data??[];}});}
