const DEFAULT_METRICS={business:['growth','visitors','engagement','reviews','campaigns','roi','intelligence','actions'],fleet:['routes','vehicles','drivers','alerts','maintenance','performance','intelligence','actions'],enterprise:['networks','partners','campaigns','outcomes','metrics','roi','intelligence','actions'],admin:['capabilities','analytics','notifications','data_quality','system_health','intelligence','actions']};
const normalize=rows=>Array.isArray(rows)?rows:rows&&typeof rows==='object'?[rows]:[];
const validScope=s=>['business','fleet','enterprise','admin'].includes(String(s||''));
export function createReportingService(client,{businessIntelligence=null,fleetIntelligence=null,enterpriseIntelligence=null}={}){if(!client)throw new Error('Supabase client is required.');
 const list=async(scopeType,scopeId)=>{if(scopeType&&!validScope(scopeType))throw new Error('Invalid report scope.');if(scopeType==='business'&&!scopeId)throw new Error('Business is required for business reports.');let q=client.from('reporting_schedules').select('*').order('created_at',{ascending:false});if(scopeType)q=q.eq('scope_type',scopeType);if(scopeId)q=q.eq('scope_id',scopeId);const{data,error}=await q;if(error)throw error;return data||[]};
 const create=async input=>{if(!input?.scope_type||!validScope(input.scope_type))throw new Error('Valid report scope is required.');if(input.scope_type==='business'&&!input.scope_id)throw new Error('Business is required for business reports.');const payload={...input,scope_type:input.scope_type,scope_id:input.scope_id||null,metrics:input.metrics?.length?input.metrics:(DEFAULT_METRICS[input.scope_type]||[])};const{data,error}=await client.from('reporting_schedules').insert(payload).select().single();if(error)throw error;if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('kleenest:reporting-updated',{detail:{scheduleId:data?.id,scopeType:data?.scope_type,scopeId:data?.scope_id}}));return data};
 const update=async(id,patch)=>{if(!id)throw new Error('Report schedule is required.');if(patch?.scope_type&&!validScope(patch.scope_type))throw new Error('Invalid report scope.');if(patch?.scope_type==='business'&&!patch.scope_id)throw new Error('Business is required for business reports.');const{data,error}=await client.from('reporting_schedules').update({...patch,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('kleenest:reporting-updated',{detail:{scheduleId:id}}));return data};
 const remove=async id=>{if(!id)throw new Error('Report schedule is required.');const{error}=await client.from('reporting_schedules').delete().eq('id',id);if(error)throw error;if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('kleenest:reporting-updated',{detail:{scheduleId:id,deleted:true}}))};
 const runs=async scheduleId=>{if(!scheduleId)throw new Error('Report schedule is required.');const{data,error}=await client.from('reporting_runs').select('*').eq('schedule_id',scheduleId).order('created_at',{ascending:false}).limit(20);if(error)throw error;return data||[]};
 const actionHistory=async(scopeId,{limit=50}={})=>{let q=client.from('intelligence_action_links').select('id,location_id,business_id,surface,signal_type,action_type,status,metadata,created_at,updated_at').order('created_at',{ascending:false}).limit(Math.min(Math.max(Number(limit)||50,1),100));if(scopeId)q=q.eq('business_id',scopeId);const{data,error}=await q;if(error)throw error;return data||[]};
 const buildPayload=async({scopeType,scopeId,metrics=[],start,end}={})=>{if(!validScope(scopeType))throw new Error('Valid report scope is required.');if(scopeType==='business'&&!scopeId)throw new Error('Business is required for business reports.');const selected=metrics.length?metrics:(DEFAULT_METRICS[scopeType]||[]);const payload={scope:scopeType,scopeId:scopeId||null,period:{start,end},generatedAt:new Date().toISOString(),metrics:{},intelligence:{signals:[],actions:[]}};if(scopeType==='business'&&businessIntelligence){const jobs=[];for(const metric of selected){const fn=businessIntelligence[metric];if(typeof fn==='function')jobs.push(Promise.resolve(fn(scopeId,start,end)).then(value=>{payload.metrics[metric]=value}).catch(()=>{}));}payload.intelligence.actions=await actionHistory(scopeId).catch(()=>[]);if(typeof businessIntelligence.locationIntelligence==='function')jobs.push(Promise.resolve(businessIntelligence.locationIntelligence(scopeId,start,end)).then(value=>{payload.intelligence.signals=normalize(value)}).catch(()=>{}));await Promise.all(jobs)}else if(scopeType==='fleet'&&fleetIntelligence){const fn=fleetIntelligence.dashboard||fleetIntelligence.summary||fleetIntelligence.analytics;if(typeof fn==='function')payload.intelligence.signals=normalize(await fn(scopeId,start,end).catch(()=>[]))}else if(scopeType==='enterprise'&&enterpriseIntelligence){const fn=enterpriseIntelligence.dashboard||enterpriseIntelligence.summary||enterpriseIntelligence.analytics;if(typeof fn==='function')payload.intelligence.signals=normalize(await fn(scopeId,start,end).catch(()=>[]))}return payload};
 return Object.freeze({list,create,update,remove,runs,actionHistory,buildPayload,defaults:DEFAULT_METRICS});
}