// Cross-source parity contract: Kleenest_Architecture is the forward runtime; Kleenest_App/KleenestApp are donor/reference sources.
// Statuses describe actual runtime reachability, not merely existence of a backend contract.
export const REFERENCE_SNAPSHOTS=Object.freeze({architecture:'main',donor:'a426c61348c5210b175ad9d62fcc0cf468cc6bfd'});
export const consumerParity=Object.freeze({mapDiscovery:'wired',gpsNearby:'wired',placeDetails:'wired',categories:'wired',checkIns:'wired',rewards:'wired',favorites:'partial-authority-review',notifications:'wired',following:'partial',amenities:'partial',bathroomVerification:'partial',routes:'wired',routeDiscovery:'partial',locationEvidence:'partial',locationObservations:'partial',locationPhotos:'partial',offlinePacks:'partial',preferredLocations:'wired',singleUseAccess:'wired'});
export const gamificationParity=Object.freeze({progression:'partial',rewardHistory:'wired',badges:'partial',streaks:'partial',challenges:'wired',games:'wired',contests:'partial',quests:'wired',leaderboards:'wired',contributorReputation:'wired',milestones:'wired',networkLeaderboard:'wired'});
export const businessParity=Object.freeze({locations:'partial',reviews:'wired',replies:'wired',media:'partial',analytics:'wired',qr:'partial',qrEngagementPrograms:'wired',promotions:'partial',redemptions:'wired',campaigns:'partial',contests:'partial',events:'partial',engagementAttribution:'wired',preferredLocations:'wired',partnerships:'partial',certifications:'backend-only',clubs:'backend-only',earnedPerks:'backend-only',searchBoosts:'backend-only',roi:'wired'});
export const fleetParity=Object.freeze({operations:'wired',vehicles:'partial',drivers:'partial',routes:'partial',maintenance:'wired',alerts:'wired',performance:'wired',controllerMetrics:'wired',metricValues:'wired',serviceOpportunities:'wired',routeNotifications:'wired',telemetry:'backend-only'});
export const enterpriseParity=Object.freeze({command:'wired',partnerNetworks:'wired',partners:'wired',campaigns:'wired',allocations:'wired',outcomes:'wired',metrics:'wired',roi:'wired',fleetEnablement:'backend-only'});
export const platformParity=Object.freeze({authentication:'wired',routeAuthorization:'wired',entitlements:'partial',admin:'wired',enterprise:'wired',commerce:'wired',notifications:'wired',push:'wired',liveNetwork:'partial',intelligenceActions:'partial',support:'partial',accountDeletion:'backend-only',externalDataCatalog:'backend-only',ingestion:'infrastructure'});
export const securityParity=Object.freeze({rlsNoPolicy:'resolved',mutableSearchPath:'resolved',anonymousSecurityDefiners:'resolved-with-intentional-public-reads',authenticatedSecurityDefiners:'review-required',leakedPasswordProtection:'review-required'});
export const FEATURE_PARITY=Object.freeze({consumer:consumerParity,gamification:gamificationParity,business:businessParity,fleet:fleetParity,enterprise:enterpriseParity,platform:platformParity,security:securityParity});
export const getParity=(workspace='consumer')=>FEATURE_PARITY[workspace]||FEATURE_PARITY.consumer;
export const PARITY_STATUS_ORDER=Object.freeze(['wired','partial','partial-authority-review','backend-only','infrastructure','review-required','resolved','resolved-with-intentional-public-reads']);
