import { createCapabilityCoverageService } from '../entitlements/coverage.js';

export function createFleetMetricService(client, { coverage = createCapabilityCoverageService(client) } = {}) {
  if (!client) throw new Error('Supabase client is required.');
  const requireId = value => { if (!value || typeof value !== 'string') throw new Error('Required identifier is missing.'); return value; };
  const finite = (value, fallback = null) => value == null || value === '' ? fallback : (Number.isFinite(Number(value)) ? Number(value) : fallback);
  const access = async (featureCode, outcome, metadata = {}) => { try { await coverage?.record({ featureCode, outcome, tierCode: 'fleet', destination: 'fleet_performance', metadata }); } catch {} };
  const rpc = async (name, args) => { const { data, error } = await client.rpc(name, args); if (error) throw error; return data; };
  return Object.freeze({
    capabilities: async businessId => { const id = requireId(businessId); return (await rpc('get_fleet_metric_capabilities', { p_business_id: id })) ?? { business_id: id, measurement_sources: [], shared_primitives: [] }; },
    configuration: async businessId => rpc('get_fleet_metric_configuration', { p_business_id: requireId(businessId) }),
    values: async (businessId, asOf = new Date().toISOString().slice(0, 10)) => { const id = requireId(businessId); if (!/^\d{4}-\d{2}-\d{2}$/.test(asOf)) throw new Error('Invalid metric date.'); return rpc('get_fleet_metric_values', { p_business_id: id, p_as_of: asOf }); },
    targets: async businessId => rpc('get_fleet_metric_targets', { p_business_id: requireId(businessId) }),
    create: async (businessId, values = {}) => { const id = requireId(businessId); if (!values.metricKey || !values.featureCode || !values.name || !values.sourceDataset || !values.sourceMetric) throw new Error('Metric key, feature, name, source dataset, and source metric are required.'); try { const data = await rpc('create_fleet_metric_definition', { p_business_id:id,p_metric_key:String(values.metricKey),p_feature_code:String(values.featureCode),p_name:String(values.name),p_description:values.description||null,p_unit:values.unit||null,p_source_dataset:String(values.sourceDataset),p_source_metric:String(values.sourceMetric),p_aggregation:values.aggregation||'avg',p_direction:values.direction||'higher_is_better',p_scoring_method:values.scoringMethod||'threshold',p_goal:finite(values.goal),p_threshold:finite(values.threshold),p_max_score:finite(values.maxScore,100),p_scoring_config:values.scoringConfig||{},p_period:values.period||'weekly' }); await access(String(values.featureCode),'allowed',{action:'create',businessId:id}); return data; } catch(error){ await access(String(values.featureCode||'fleet.metric.create'),'blocked',{action:'create',businessId:id,error:error?.message}); throw error; } },
    update: async (metricDefinitionId, values = {}) => { const featureCode=String(values.featureCode||'fleet.metric.update'); try { const data=await rpc('update_fleet_metric_definition',{p_metric_definition_id:requireId(metricDefinitionId),p_name:values.name,p_description:values.description||null,p_goal:finite(values.goal),p_threshold:finite(values.threshold),p_max_score:finite(values.maxScore,100),p_scoring_method:values.scoringMethod||'threshold',p_scoring_config:values.scoringConfig||{},p_period:values.period||'weekly',p_active:values.active!==false}); await access(featureCode,'allowed',{action:'update',metricDefinitionId}); return data; } catch(error){ await access(featureCode,'blocked',{action:'update',metricDefinitionId,error:error?.message}); throw error; } },
    assign: async (metricDefinitionId,targetType,targetId=null) => { const featureCode='fleet.metric.assign'; const type=String(targetType||'').trim().toLowerCase(); const id=type==='fleet'?null:requireId(targetId); if(!['fleet','driver','vehicle','route'].includes(type)) throw new Error('Invalid Fleet metric target type.'); try { const data=await rpc('assign_fleet_metric',{p_metric_definition_id:requireId(metricDefinitionId),p_target_type:type,p_target_id:id}); await access(featureCode,'allowed',{action:'assign',metricDefinitionId,targetType:type,targetId:id}); return data; } catch(error){ await access(featureCode,'blocked',{action:'assign',metricDefinitionId,targetType:type,targetId:id,error:error?.message}); throw error; } },
    removeAssignment: async assignmentId => { const id=requireId(assignmentId); try { const data=await rpc('remove_fleet_metric_assignment',{p_assignment_id:id}); await access('fleet.metric.assign','allowed',{action:'remove_assignment',assignmentId:id}); return data; } catch(error){ await access('fleet.metric.assign','blocked',{action:'remove_assignment',assignmentId:id,error:error?.message}); throw error; } },
  });
}
