import { buildFleetRecommendations } from './recommendations.js';
import { buildNotificationCandidates } from './notifications.js';
export function createFleetOperationsService(client){
 if(!client)throw new Error('Supabase client is required.');
 async function rpc(name,args={}){const{data,error}=await client.rpc(name,args);if(error)throw error;return data}
 async function networkRecommendations(businessId){return buildFleetRecommendations((await rpc('fleet_service_opportunities_for_business',{p_business_id:businessId}))??[])}
 async function recordOperationalEvent(businessId,eventType,payload={}){try{return await rpc('record_fleet_operational_event',{p_business_id:businessId,p_event_type:eventType,p_payload:payload})}catch{return null}}
 function publishMutation(businessId,eventType,rpcName,result,operationalEvent=null){if(typeof window!=='undefined'){const detail={businessId,eventType,rpc:rpcName,result,operationalEvent};window.dispatchEvent(new CustomEvent('kleenest:fleet-updated',{detail}));window.dispatchEvent(new CustomEvent('kleenest:business-updated',{detail:{...detail,reason:'fleet-mutation'}}));}return result}
 async function mutate(businessId,eventType,rpcName,args={}){const result=await rpc(rpcName,args);const operationalEvent=await recordOperationalEvent(businessId,eventType,{result});return publishMutation(businessId,eventType,rpcName,result,operationalEvent)}
 async function authoritativeMutation(businessId,eventType,rpcName,args={}){const result=await rpc(rpcName,args);return publishMutation(businessId,eventType,rpcName,result,{serverAuthoritative:true})}
 async function routeMutation(businessId,routeId,status){const result=await authoritativeMutation(businessId,'route_status_updated','fleet_set_route_status',{p_business_id:businessId,p_route_id:routeId,p_status:status});if(!['completed','cancelled','failed'].includes(status))await recordOperationalEvent(businessId,'route_status_updated',{routeId,status,result});return result}
 const crud={
 createVehicle:(b,p)=>mutate(b,'vehicle_created','fleet_create_vehicle',{p_business_id:b,p_name:p.name,p_unit_code:p.unitCode??null,p_vehicle_type:p.vehicleType??'vehicle',p_status:p.status??'active',p_driver_name:p.driverName??null,p_current_lat:p.currentLat??null,p_current_lng:p.currentLng??null,p_odometer_miles:p.odometerMiles??null,p_metadata:p.metadata??{}}),
 updateVehicle:(b,id,p)=>mutate(b,'vehicle_updated','fleet_update_vehicle',{p_business_id:b,p_vehicle_id:id,p_name:p.name,p_unit_code:p.unitCode??null,p_vehicle_type:p.vehicleType??'vehicle',p_status:p.status??'active',p_driver_name:p.driverName??null,p_current_lat:p.currentLat??null,p_current_lng:p.currentLng??null,p_odometer_miles:p.odometerMiles??null,p_metadata:p.metadata??{}}),
 deleteVehicle:(b,id)=>mutate(b,'vehicle_deleted','fleet_delete_vehicle',{p_business_id:b,p_vehicle_id:id}),
 createDriver:(b,p)=>mutate(b,'driver_created','fleet_create_driver',{p_business_id:b,p_name:p.name,p_email:p.email??null,p_phone:p.phone??null,p_status:p.status??'active',p_vehicle_id:p.vehicleId??null,p_metadata:p.metadata??{}}),
 updateDriver:(b,id,p)=>mutate(b,'driver_updated','fleet_update_driver',{p_business_id:b,p_driver_id:id,p_name:p.name,p_email:p.email??null,p_phone:p.phone??null,p_status:p.status??'active',p_vehicle_id:p.vehicleId??null,p_metadata:p.metadata??{}}),
 deleteDriver:(b,id)=>mutate(b,'driver_deleted','fleet_delete_driver',{p_business_id:b,p_driver_id:id}),
 createRoute:(b,p)=>mutate(b,'route_created','fleet_create_route',{p_business_id:b,p_name:p.name,p_status:p.status??'planned',p_vehicle_id:p.vehicleId??null,p_driver_id:p.driverId??null,p_scheduled_for:p.scheduledFor??null,p_distance_miles:p.distanceMiles??null,p_estimated_minutes:p.estimatedMinutes??null,p_stops_count:p.stopsCount??0,p_metadata:p.metadata??{}}),
 updateRoute:(b,id,p)=>mutate(b,'route_updated','fleet_update_route',{p_business_id:b,p_route_id:id,p_name:p.name,p_status:p.status??'planned',p_vehicle_id:p.vehicleId??null,p_driver_id:p.driverId??null,p_scheduled_for:p.scheduledFor??null,p_distance_miles:p.distanceMiles??null,p_estimated_minutes:p.estimatedMinutes??null,p_stops_count:p.stopsCount??0,p_metadata:p.metadata??{}}),
 deleteRoute:(b,id)=>mutate(b,'route_deleted','fleet_delete_route',{p_business_id:b,p_route_id:id}),
 createMaintenance:(b,p)=>mutate(b,'maintenance_created','fleet_create_maintenance',{p_business_id:b,p_vehicle_id:p.vehicleId,p_maintenance_type:p.maintenanceType,p_status:p.status??'scheduled',p_scheduled_at:p.scheduledAt??null,p_odometer_miles:p.odometerMiles??null,p_cost:p.cost??null,p_vendor:p.vendor??null,p_notes:p.notes??null,p_metadata:p.metadata??{}}),
 updateMaintenance:(b,id,p)=>mutate(b,'maintenance_updated','fleet_update_maintenance',{p_business_id:b,p_maintenance_id:id,p_vehicle_id:p.vehicleId,p_maintenance_type:p.maintenanceType,p_status:p.status??'scheduled',p_completed_at:p.completedAt??null,p_scheduled_at:p.scheduledAt??null,p_odometer_miles:p.odometerMiles??null,p_cost:p.cost??null,p_vendor:p.vendor??null,p_notes:p.notes??null,p_metadata:p.metadata??{}}),
 deleteMaintenance:(b,id)=>mutate(b,'maintenance_deleted','fleet_delete_maintenance',{p_business_id:b,p_maintenance_id:id})};
 const observeAccess=b=>rpc('fleet_observe_access',{p_business_id:b}).then(Boolean);
 const searchStopLocations=async(query,{lat=null,lng=null,radiusM=80467,limit=25}={})=>{const data=await rpc('semantic_location_search',{p_query:query,p_lat:lat,p_lng:lng,p_radius_m:radiusM,p_limit:limit});return data?.results??[]};
 const subscribeDispatch=(businessId,onChange)=>{if(!businessId||typeof onChange!=='function'||typeof client.channel!=='function')return()=>{};const filter=`business_id=eq.${businessId}`;const channel=client.channel(`fleet-dispatch:${businessId}`).on('postgres_changes',{event:'*',schema:'public',table:'fleet_routes',filter},payload=>onChange({source:'fleet_routes',payload})).on('postgres_changes',{event:'*',schema:'public',table:'fleet_route_stops',filter},payload=>onChange({source:'fleet_route_stops',payload})).subscribe();return()=>{try{client.removeChannel(channel)}catch{}}};
 return Object.freeze({access:observeAccess,observeAccess,dashboard:b=>rpc('fleet_dashboard_summary_v2',{p_business_id:b}),driverAssignmentCandidates:b=>rpc('fleet_driver_assignment_candidates',{p_business_id:b}).then(d=>d??[]),...crud,maintenanceComplete:(b,id,notes='')=>mutate(b,'maintenance_completed','fleet_complete_maintenance',{p_business_id:b,p_maintenance_id:id,p_notes:notes}),resolveAlert:(b,id,resolution)=>mutate(b,'alert_resolved','fleet_resolve_alert',{p_business_id:b,p_alert_id:id,p_resolution:resolution}),driverStatus:(b,id,status)=>mutate(b,'driver_status_updated','fleet_set_driver_status',{p_business_id:b,p_driver_id:id,p_status:status}),assignDriverUser:(b,id,userId)=>mutate(b,'driver_user_assigned','fleet_assign_driver_user',{p_business_id:b,p_driver_id:id,p_user_id:userId??null}),vehicleStatus:(b,id,status)=>mutate(b,'vehicle_status_updated','fleet_set_vehicle_status',{p_business_id:b,p_vehicle_id:id,p_status:status}),routeStatus:routeMutation,searchStopLocations,subscribeDispatch,dispatchIntelligence:(b,routeId=null,limit=20)=>rpc('fleet_dispatch_intelligence',{p_business_id:b,p_route_id:routeId,p_limit:limit}),setRouteStops:(b,id,stops)=>mutate(b,'route_stops_configured','fleet_set_route_stops',{p_business_id:b,p_route_id:id,p_stops:stops??[]}),dispatchRoute:(b,id)=>authoritativeMutation(b,'route_dispatched','fleet_dispatch_route',{p_business_id:b,p_route_id:id}),recordRouteStopTiming:(b,routeId,stopId,eventType,occurredAt=null)=>authoritativeMutation(b,`route_stop_${eventType}`,'fleet_record_route_stop_timing',{p_business_id:b,p_route_id:routeId,p_route_stop_id:stopId,p_event_type:eventType,p_occurred_at:occurredAt}),routePerformance:(b,id)=>rpc('fleet_route_performance',{p_business_id:b,p_route_id:id}),operationalEvent:recordOperationalEvent,opportunities:b=>rpc('fleet_service_opportunities_for_business',{p_business_id:b}).then(d=>d??[]),recommendations:networkRecommendations,notificationCandidates:async(b,existingNotifications=[])=>buildNotificationCandidates(await networkRecommendations(b),{surface:'fleet',existingNotifications}),intelligence:async b=>{const[dashboard,opportunities]=await Promise.all([rpc('fleet_dashboard_summary_v2',{p_business_id:b}),rpc('fleet_service_opportunities_for_business',{p_business_id:b})]);const recommendations=buildFleetRecommendations(opportunities??[]);return{dashboard,opportunities:opportunities??[],recommendations,notifications:buildNotificationCandidates(recommendations,{surface:'fleet'})}},leaderboard:(b,metric='safety_score',targetType='driver',limit=20)=>rpc('get_fleet_leaderboard',{p_business_id:b,p_metric:metric,p_target_type:targetType,p_limit:limit}),networkLeaderboard:(metric='stops_completed',limit=20)=>rpc('get_fleet_network_leaderboard',{p_metric:metric,p_limit:limit}),platformLeaderboard:(key='users:points',limit=20)=>rpc('get_platform_leaderboard',{p_leaderboard_key:key,p_limit:limit})})}
