export const OBSERVATION_OPTIONS=[['clean','Clean'],['dirty','Dirty'],['supplies_ok','Supplies OK'],['supplies_low','Supplies low'],['open','Open'],['closed','Closed'],['accessible','Accessible'],['not_accessible','Not accessible'],['changing_table','Changing table'],['no_changing_table','No changing table'],['bathroom_present','Bathroom present'],['bathroom_missing','Bathroom missing']];

export function createContributionCommands({services,user,navigate,setBusy,setError,setResult,setCheckInId,setReputation,locationId,placeId,qrToken,checkInId,setNote,setComment}){
 const requireLogin=()=>{if(!user){navigate(`/auth?returnTo=${encodeURIComponent(window.location.pathname+window.location.search)}`);return false}return true};
 const refreshReputation=async(key,value)=>{if(!user?.id||!services?.reputation?.refreshAfterContribution)return;try{const next=await services.reputation.refreshAfterContribution(user.id,{type:key,locationId,checkInId:checkInId||value?.check_in_id||value?.id||null,reviewId:key==='review'?(value?.id||value?.review_id||null):null,observationId:key==='observation'?(value?.id||value?.observation_id||null):null});setReputation(next)}catch(_){}};
 const run=async(key,action)=>{if(!requireLogin())return null;setBusy(key);setError('');try{const value=await action();setResult(value);await refreshReputation(key,value);window.dispatchEvent(new CustomEvent('kleenest:consumer-action-completed',{detail:{locationId,placeId,action:key}}));window.dispatchEvent(new CustomEvent('kleenest:activity-updated',{detail:{locationId,placeId}}));if(key==='checkin')window.dispatchEvent(new CustomEvent('kleenest:checkin-completed',{detail:{locationId,placeId,checkInId:value?.check_in_id}}));if(key==='review'||key==='observation')window.dispatchEvent(new CustomEvent('kleenest:rewards-updated',{detail:{locationId,placeId}}));return value}catch(e){setError(e?.message||String(e));return null}finally{setBusy('')}};
 return {
  run,
  checkIn:async()=>{if(!qrToken||!placeId)throw new Error('A venue QR check-in requires the canonical place and QR token.');const value=await services.checkins.byQr({placeId,qrToken});const row=Array.isArray(value)?value[0]:value;if(row?.check_in_id||row?.id)setCheckInId(row.check_in_id||row.id);return row||value},
  observation:async({observation,cleanliness,note})=>{if(!locationId||!observation)throw new Error('Choose a location and observation first.');const value=await services.locationEvidence.restroomObservation({locationId,checkInId:checkInId||null,observationType:observation,cleanlinessPct:cleanliness,note:note.trim()||null});setNote('');return Array.isArray(value)?value[0]:value},
  review:async({rating,cleanliness,comment})=>{if(!locationId||!comment.trim())throw new Error('Write a review before publishing.');const value=await services.reviews.create({locationId,checkInId:checkInId||null,stars:rating,cleanlinessPct:cleanliness,comment:comment.trim()});setComment('');return value}
 };
}
