const DB_NAME='kleenest-offline-network';
const DB_VERSION=4;
const STORES=['packs','locations','businesses','routes','events'];

function openDb(){return new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined')return reject(new Error('Offline storage is unavailable in this browser.'));const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;STORES.forEach(name=>{if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:'id'});});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('Unable to open offline storage.'));});}
async function putMany(storeName,rows){if(!rows?.length)return;const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(storeName,'readwrite');rows.forEach(row=>tx.objectStore(storeName).put(row));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
async function getAll(storeName){const db=await openDb();const rows=await new Promise((resolve,reject)=>{const tx=db.transaction(storeName,'readonly');const req=tx.objectStore(storeName).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error);});db.close();return rows;}
export async function cacheOfflinePack(pack,{locations=[],businesses=[],routes=[]}={}){const normalized={...pack,id:String(pack.id),cached_at:pack.cached_at||new Date().toISOString()};await putMany('packs',[normalized]);await putMany('locations',locations.map(row=>({...row,pack_id:normalized.id,id:`${normalized.id}:location:${row.location_id||row.id}`})));await putMany('businesses',businesses.map(row=>({...row,pack_id:normalized.id,id:`${normalized.id}:business:${row.business_id||row.id}`})));await putMany('routes',routes.map(row=>({...row,pack_id:normalized.id,id:`${normalized.id}:route:${row.id||row.route_id}`})));return normalized;}
export async function queueOfflineEvent({packId,eventType,payload,clientEventId=null}){const id=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;const row={id,pack_id:String(packId),event_type:eventType,payload,client_event_id:clientEventId||globalThis.crypto?.randomUUID?.()||id,created_at:new Date().toISOString(),synced_at:null,sync_error:null,attempt_count:0,last_attempt_at:null};await putMany('events',[row]);return row;}
export async function getCachedPacks(){return(await getAll('packs')).sort((a,b)=>String(b.cached_at).localeCompare(String(a.cached_at)));}
export async function getCachedLocations(packId=null){const rows=await getAll('locations');return packId?rows.filter(row=>row.pack_id===String(packId)):rows;}
export async function getCachedBusinesses(packId=null){const rows=await getAll('businesses');return packId?rows.filter(row=>row.pack_id===String(packId)):rows;}
export async function getPendingOfflineEvents(){return(await getAll('events')).filter(row=>!row.synced_at);}
export async function markOfflineEventSynced(id){const db=await openDb();const row=await new Promise((resolve,reject)=>{const tx=db.transaction('events','readonly');const req=tx.objectStore('events').get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});if(row){row.synced_at=new Date().toISOString();row.sync_error=null;await new Promise((resolve,reject)=>{const tx=db.transaction('events','readwrite');tx.objectStore('events').put(row);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}db.close();return row;}
export function bindOnlineSync(sync){if(typeof window==='undefined'||typeof sync!=='function')return()=>{};const handler=()=>{if(navigator.onLine)sync().catch(()=>{})};window.addEventListener('online',handler);return()=>window.removeEventListener('online',handler);}
