import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.0";
const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const supabaseAdmin=createClient(Deno.env.get('SUPABASE_URL')||'',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'');
const allowedTasks=new Set(['business_growth','fleet_dispatch','fleet_debrief','enterprise_network','notification_copy','visit_review','admin_moderation','admin_operations','route_plan']);
const clamp=(value:unknown,max=18000)=>JSON.stringify(value??{}).slice(0,max);const text=(value:unknown)=>String(value??'').trim();
function fallback(task:string,context:any){
 if(task==='visit_review'){const stars=Number(context?.stars||0),clean=Number(context?.cleanliness||0),observation=text(context?.observation).replaceAll('_',' '),note=text(context?.note);const parts=[stars?`${stars}/5 visit`:null,clean?`cleanliness about ${clean}%`:null,observation||null,note||null].filter(Boolean);return `Draft from your verified visit: ${parts.join('. ')}.${note?'':' Add any specific detail you personally observed before publishing.'}`;}
 if(task==='fleet_dispatch'){const c=context?.dispatch||context||{},candidates=Array.isArray(c?.recommended_stops)?c.recommended_stops:[],readyDrivers=Number(c?.ready_driver_count??0),readyVehicles=Number(c?.ready_vehicle_count??0);const top=candidates.slice(0,3).map((r:any)=>`${r.name||'Location'} (${(r.reasons||[]).join(', ')||'service opportunity'})`);return [`Dispatch readiness: ${readyDrivers} ready driver(s), ${readyVehicles} ready vehicle(s).`,top.length?`Highest-priority stops: ${top.join('; ')}.`:'No ranked service stops are available yet.','Review assignments, timing, and stop order before dispatch.'].join(' ');}
 if(task==='fleet_debrief'){const p=context?.performance||context||{};return `Route debrief: ${p.completed_stops??0}/${p.total_stops??0} stops completed; on-time arrivals ${p.arrived_by_plan_pct??'unknown'}%; ETA variance ${p.avg_eta_variance_minutes??'unknown'} min; TTL variance ${p.avg_ttl_variance_minutes??'unknown'} min; dwell variance ${p.avg_dwell_variance_minutes??'unknown'} min; duration variance ${p.duration_variance_minutes??'unknown'} min. Review the largest measured variances before changing future plans.`;}
 if(task==='enterprise_network'){const report=context?.report||{},roi=context?.roi||{},allocation=context?.allocation||{};return `Enterprise brief from current network facts: report fields ${Object.keys(report).length}, ROI/benchmark fields ${Object.keys(roi).length}, allocation fields ${Object.keys(allocation).length}. Focus first on the largest measured gaps or strongest outcomes in those datasets, then validate any campaign or allocation change before execution.`;}
 if(task==='notification_copy'){const title=text(context?.title),audience=text(context?.audience)||'business audience',body=text(context?.body);return `Draft for ${audience}${title?` — ${title}`:''}: ${body||'Share the concrete update, customer benefit, timing, and any eligibility details. Avoid unsupported urgency or claims.'}`;}
 if(task==='business_growth'){const recs=Array.isArray(context?.recommendations)?context.recommendations:[];const top=recs.slice(0,3).map((r:any)=>`${r?.name||'Location'}: ${r?.recommendation?.title||r?.title||'review signal'}`);return top.length?`Highest-value actions from current Kleenest signals: ${top.join('; ')}. Validate each recommendation against current staffing, promotions, and location conditions before executing.`:'No strong growth recommendation is available from the current authoritative signals.';}
 if(task==='admin_moderation'){const review=text(context?.comment),reason=text(context?.reason),details=text(context?.details);return `Moderation triage only — no automatic decision. Report reason: ${reason||'unspecified'}. ${details?`Details: ${details}. `:''}${review?`Review text to inspect: ${review.slice(0,500)}`:'No review text was provided.'}`;}
 if(task==='admin_operations'){const operation=text(context?.operation)||'administrative operation',result=context?.result??context;const keys=result&&typeof result==='object'?Object.keys(result):[];return `Admin operations brief for ${operation}: the authoritative result returned ${keys.length?keys.join(', '):'no structured fields'}. Review explicit errors, zero/failed counts, stale/low-quality indicators, and reconciliation exceptions before running another maintenance action. AI has not executed or changed anything.`;}
 const stops=Array.isArray(context?.stops)?context.stops:[];return stops.length?`Route contains ${stops.length} stop(s). Prefer an order that preserves required appointments, minimizes backtracking, and leaves realistic dwell/TTL buffers. Review the proposed order before saving.`:'Add candidate stops before asking for route-plan guidance.';
}
function systemPrompt(task:string){const shared='You are Kleenest AI Assist. Use only the supplied authoritative Kleenest context. Never invent locations, metrics, reviews, business facts, driver states, or user observations. Be concise, operational, and explicit about uncertainty. Suggestions are advisory and require human review before any mutation.';const map:Record<string,string>={business_growth:' Identify the 3 highest-value business actions, explain why each matters, and cite supplied signals or metrics.',fleet_dispatch:' Recommend dispatch priorities, assignment concerns, and stop-order considerations. Do not claim live traffic unless supplied.',fleet_debrief:' Summarize measured route performance, identify the largest ETA, TTL, dwell, or duration variances, and suggest what the operator should inspect next. Never invent causes.',enterprise_network:' Summarize network, benchmark, campaign, and allocation performance and identify the 3 most important decisions to review. Never invent ROI or causal attribution.',notification_copy:' Draft concise customer-facing notification copy for the supplied audience and facts. Preserve concrete dates, restrictions, and benefits exactly as supplied. Do not invent promotions, availability, urgency, eligibility, or outcomes.',visit_review:' Draft a first-person review using only user-provided verified visit details. Do not add facts. Avoid marketing language.',admin_moderation:' Summarize the concern, separate observable text from inference, and list what a human moderator should verify. Never make the final enforcement decision.',admin_operations:' Summarize the supplied administrative health, quality, ingestion, reconciliation, or maintenance result. Identify concrete failures, stale/low-quality indicators, anomalous counts, and the safest next checks. Do not claim a repair occurred and never recommend destructive action without explicit evidence.',route_plan:' Explain a sensible route ordering strategy using only supplied stops, constraints, planned arrival, TTL, dwell, and location facts. Do not invent travel times.'};return shared+(map[task]||'');}
async function modelAssist(task:string,context:any,instruction:string){const apiKey=Deno.env.get('OPENAI_API_KEY');if(!apiKey)return null;const model=Deno.env.get('OPENAI_MODEL')||'gpt-5.6-luna';const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model,input:[{role:'system',content:[{type:'input_text',text:systemPrompt(task)}]},{role:'user',content:[{type:'input_text',text:`Instruction: ${instruction||'Help with this task.'}\nAuthoritative context:\n${clamp(context)}`}]}],max_output_tokens:700})});if(!response.ok)throw new Error(`AI provider error ${response.status}`);const payload=await response.json(),output=Array.isArray(payload?.output)?payload.output:[];const answer=output.flatMap((item:any)=>Array.isArray(item?.content)?item.content:[]).map((item:any)=>item?.text).filter(Boolean).join('\n').trim();if(!answer)throw new Error('AI provider returned no text');return{answer,model};}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers});try{const auth=req.headers.get('Authorization');if(!auth)return new Response(JSON.stringify({error:'Unauthorized'}),{status:401,headers});const token=auth.replace(/^Bearer\s+/i,'');const{data:{user},error:authError}=await supabaseAdmin.auth.getUser(token);if(authError||!user)return new Response(JSON.stringify({error:'Unauthorized'}),{status:401,headers});const body=await req.json(),task=text(body?.task);if(!allowedTasks.has(task))return new Response(JSON.stringify({error:'Unsupported AI task'}),{status:400,headers});const context=body?.context??{},instruction=text(body?.instruction).slice(0,2000);let provider:'openai'|'grounded_fallback'='grounded_fallback',model:string|null=null,answer='';try{const generated=await modelAssist(task,context,instruction);if(generated){provider='openai';model=generated.model;answer=generated.answer;}}catch(error){console.error('ai-assist provider fallback',error);}if(!answer)answer=fallback(task,context);try{await supabaseAdmin.from('data_feature_events').insert({event_type:'ai_assist_generated',feature_code:'ai_assist',subject_type:'user',subject_id:user.id,source_table:'edge_function',value_text:task,metadata:{provider,model,task}});}catch{}return new Response(JSON.stringify({task,answer,provider,model,review_required:true}),{headers});}catch(error){return new Response(JSON.stringify({error:error instanceof Error?error.message:'AI assist failed'}),{status:400,headers});}});