export const LIVE_EVENT_TYPES=Object.freeze({USER_LOCATION_VIEWED:'user.location_viewed',USER_DIRECTIONS_REQUESTED:'user.directions_requested',USER_ROUTE_STARTED:'user.route_started',USER_APPROACHING_LOCATION:'user.approaching_location',USER_ARRIVED:'user.arrived',USER_DEPARTED:'user.departed',QR_CHECK_IN:'user.qr_check_in',QR_SCANNED:'user.qr_scanned',QR_REDEEMED:'user.qr_redeemed',LOCATION_FAVORITED:'user.location_favorited',LOCATION_UNFAVORITED:'user.location_unfavorited',LOCATION_VERIFIED:'location.verified',LOCATION_STALE:'location.stale',LOCATION_CONFLICT:'location.conflict',BUSINESS_OFFER_STARTED:'business.offer_started',BUSINESS_OFFER_REDEEMED:'business.offer_redeemed',CAMPAIGN_CONVERTED:'business.campaign_converted',VEHICLE_ENTERED_ZONE:'fleet.vehicle_entered_zone',VEHICLE_ARRIVED:'fleet.vehicle_arrived',VEHICLE_DEPARTED:'fleet.vehicle_departed',FLEET_ROUTE_STARTED:'fleet.route_started',ROUTE_CHANGED:'fleet.route_changed',TASK_COMPLETED:'fleet.task_completed'});
export const PUBLIC_LIVE_EVENT_TYPES=Object.freeze([LIVE_EVENT_TYPES.LOCATION_VERIFIED,LIVE_EVENT_TYPES.LOCATION_STALE,LIVE_EVENT_TYPES.LOCATION_CONFLICT,LIVE_EVENT_TYPES.BUSINESS_OFFER_STARTED,LIVE_EVENT_TYPES.BUSINESS_OFFER_REDEEMED,LIVE_EVENT_TYPES.CAMPAIGN_CONVERTED]);
export function createLiveNetworkService(client){
 if(!client)throw new Error('Supabase client is required.');
 const requireUser=async()=>{const{data:{user},error}=await client.auth.getUser();if(error)throw error;if(!user)throw new Error('Sign in to continue.');return user;};
 const normalizePayload=payload=>payload?.new??payload?.record??payload??null;
 const publish=async({type,locationId=null,payload={},actorType='user',actorId=null,shareFleet=true}={})=>{const user=await requireUser();if(!Object.values(LIVE_EVENT_TYPES).includes(type))throw new Error(`Unsupported live event type: ${type}`);const{data,error}=await client.rpc('publish_live_network_event',{p_event_type:type,p_location_id:locationId,p_actor_type:actorType,p_actor_id:actorId||user.id,p_payload:{...payload,share_fleet:shareFleet}});if(error)throw error;const event=normalizePayload(data);if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('kleenest:live-network-event',{detail:event}));return event;};
 const list=async({locationId=null,types=null,limit=100,before=null}={})=>{const safeLimit=Math.min(Math.max(Number(limit)||100,1),100);const{data,error}=await client.rpc('list_public_live_network_events',{p_limit:safeLimit});if(error)throw error;let rows=Array.isArray(data)?data:[];if(locationId)rows=rows.filter(row=>String(row.location_id)===String(locationId));if(types?.length)rows=rows.filter(row=>types.includes(row.event_type));if(before)rows=rows.filter(row=>new Date(row.created_at)<new Date(before));return rows;};
 const subscribe=({locationId=null,onEvent,types=PUBLIC_LIVE_EVENT_TYPES}={})=>{if(typeof onEvent!=='function')throw new Error('onEvent callback is required.');const safeTypes=Array.isArray(types)&&types.length?types:PUBLIC_LIVE_EVENT_TYPES;const suffix=typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;const channel=client.channel(`live-network-public-${locationId||'global'}-${suffix}`);let closed=false;channel.on('postgres_changes',{event:'INSERT',schema:'public',table:'live_network_events',filter:`event_type=in.(${safeTypes.join(',')})`},payload=>{if(closed)return;const event=normalizePayload(payload);if(locationId&&String(event?.location_id)!==String(locationId))return;if(!event)return;onEvent(event);if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('kleenest:live-network-event',{detail:event}));});channel.subscribe();return()=>{if(closed)return;closed=true;void client.removeChannel(channel);};};
 return Object.freeze({publish,list,subscribe});
}
