import { useEffect, useMemo, useState } from 'react';
import { Link, useLocalSearchParams } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { createKleenestSupabaseClient } from '@kleenest/mobile-core';

export default function LocationDetailScreen(){
 const {id}=useLocalSearchParams<{id:string}>(); const client=useMemo(()=>{try{return createKleenestSupabaseClient()}catch{return null}},[]); const [place,setPlace]=useState<any>(null); const [error,setError]=useState('');
 useEffect(()=>{if(!client||!id)return;void (async()=>{const {data,error}=await client.from('locations').select('*').eq('id',id).maybeSingle();if(error)setError(error.message);else setPlace(data)})()},[client,id]);
 if(!place&&!error)return <View style={styles.center}><ActivityIndicator/><Text>Gathering live location intelligence…</Text></View>;
 return <ScrollView contentContainerStyle={styles.page}><Link href="/map" style={styles.back}>← Back to map</Link>{error?<Text style={styles.error}>{error}</Text>:<><Text style={styles.eyebrow}>KLEENEST LOCATION</Text><Text style={styles.title}>{place.name}</Text><Text style={styles.address}>{place.address||[place.city,place.state].filter(Boolean).join(', ')}</Text><View style={styles.panel}><Text style={styles.panelTitle}>Trust & intelligence</Text><Text>Cleanliness: {place.cleanliness_pct ?? 'Awaiting signal'}</Text><Text>Rating: {place.rating ?? '—'}</Text><Text>Reviews: {place.review_count ?? 0}</Text><Text>Accessible: {place.accessible ? 'Yes' : 'No signal'}</Text></View><View style={styles.row}><Link href={`/route?locationId=${id}&destination=${encodeURIComponent(place.name||'')}` as never} asChild><Pressable style={styles.primary}><Text style={styles.primaryText}>Add to route</Text></Pressable></Link><Link href="/map" asChild><Pressable style={styles.secondary}><Text>Back to discovery</Text></Pressable></Link></View></>}</ScrollView>}
const styles=StyleSheet.create({page:{padding:22,gap:14,backgroundColor:'#fff',flexGrow:1},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10},back:{fontWeight:'700'},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2},title:{fontSize:30,fontWeight:'800'},address:{color:'#5b6470',fontSize:15},panel:{padding:18,borderRadius:16,borderWidth:1,borderColor:'#e5e7eb',gap:9},panelTitle:{fontSize:18,fontWeight:'800'},row:{flexDirection:'row',gap:10},primary:{flex:1,backgroundColor:'#111827',padding:15,borderRadius:12,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800'},secondary:{flex:1,borderWidth:1,borderColor:'#d1d5db',padding:15,borderRadius:12,alignItems:'center'},error:{color:'#b91c1c'}});
