import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const ENDPOINTS=["https://overpass-api.de/api/interpreter","https://overpass.kumi.systems/api/interpreter","https://overpass.private.coffee/api/interpreter"];
const URL=Deno.env.get("SUPABASE_URL")!; const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!; const ANON=Deno.env.get("SUPABASE_ANON_KEY")!;
const authClient=createClient(URL,ANON,{auth:{persistSession:false}}); const serviceClient=createClient(URL,SERVICE,{auth:{persistSession:false}});
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...CORS,"Content-Type":"application/json","Cache-Control":"no-store"}});
function category(t:any){if(t.amenity==='toilets'||t.building==='toilets'||t.toilets==='yes'||t['toilets:access']==='public')return'restroom';if(t.amenity==='fuel')return'gas_station';if(t.amenity==='restaurant'||t.amenity==='fast_food')return'restaurant';if(t.amenity==='cafe')return'cafe';if(['hospital','clinic','doctors','dentist','pharmacy'].includes(t.amenity))return'health';if(['park','nature_reserve','playground','sports_centre'].includes(t.leisure))return'park';if(['supermarket','convenience','mall','department_store','bakery','pharmacy'].includes(t.shop))return'shopping';if(['townhall','courthouse','police','fire_station'].includes(t.amenity)||t.office==='government')return'public_safety';return'service';}
function rows(es:any[]){return es.map(e=>{const t=e.tags||{},lat=Number(e.lat??e.center?.lat),lng=Number(e.lon??e.center?.lon);if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;const c=category(t),id=`osm:${e.type}:${e.id}`;return{id,location_id:id,source_id:id,latitude:lat,longitude:lng,name:t.name||t.brand||t.operator||(c==='restroom'?'Public Restroom':`Unnamed ${c.replaceAll('_',' ')}`),category:c,place_type:c,address:[t['addr:housenumber'],t['addr:street']].filter(Boolean).join(' ')||t['addr:full']||'',city:t['addr:city']||'',state:t['addr:state']||'',postal_code:t['addr:postcode']||'',brand:t.brand||null,operator_name:t.operator||null,source:'live_osm',source_dataset:'openstreetmap_live',source_external_id:id,osm_tags:t,is_verified:false};}).filter(Boolean);}
function query(lat:number,lng:number,r:number){const dlat=r/111320,dlng=r/(111320*Math.max(Math.cos(lat*Math.PI/180),.2));return`[out:json][timeout:10];(nwr[amenity~"restaurant|fast_food|cafe|fuel|toilets|hospital|clinic|doctors|dentist|pharmacy|library|bus_station|townhall|courthouse|police|fire_station"](${lat-dlat},${lng-dlng},${lat+dlat},${lng+dlng});nwr[building="toilets"](${lat-dlat},${lng-dlng},${lat+dlat},${lng+dlng});nwr[toilets="yes"](${lat-dlat},${lng-dlng},${lat+dlat},${lng+dlng});nwr["toilets:access"="public"](${lat-dlat},${lng-dlng},${lat+dlat},${lng+dlng});nwr[shop~"supermarket|convenience|mall|department_store|bakery|pharmacy"](${lat-dlat},${lng-dlng},${lat+dlat},${lng+dlng});nwr[leisure~"park|nature_reserve|playground|sports_centre"](${lat-dlat},${lng-dlng},${lat+dlat},${lng+dlng});nwr[railway="station"](${lat-dlat},${lng-dlng},${lat+dlat},${lng+dlng});nwr[tourism~"hotel|motel|hostel|museum|gallery"](${lat-dlat},${lng-dlng},${lat+dlat},${lng+dlng}););out center tags;`}
async function one(ep:string,q:string,m:'POST'|'GET'){const c=new AbortController(),tm=setTimeout(()=>c.abort(),11000);try{const u=m==='GET'?`${ep}?data=${encodeURIComponent(q)}`:ep,r=await fetch(u,{method:m,headers:{'content-type':'text/plain','user-agent':'KleenestApp/1.0'},body:m==='POST'?q:undefined,signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);const p=await r.json();return Array.isArray(p.elements)?p.elements:[]}finally{clearTimeout(tm)}}
async function live(q:string){return Promise.any(ENDPOINTS.flatMap(ep=>[one(ep,q,'POST'),one(ep,q,'GET')]))}
async function userId(req:Request){const t=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!t)return null;const {data,error}=await authClient.auth.getUser(t);return error||!data.user?null:data.user.id}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});if(req.method!=='POST')return json({error:'POST required'},405);try{const uid=await userId(req),b=await req.json(),lat=Number(b.latitude??b.lat),lng=Number(b.longitude??b.lng),radius=Math.min(Math.max(Number(b.radius_km||8),1),20);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<-90||lat>90||lng<-180||lng>180)return json({error:'valid lat/lng required'},400);const discovered=rows(await live(query(lat,lng,radius*1000)));let imported=0,updated=0,ingest_error=null;if(uid){try{for(let i=0;i<discovered.length;i+=100){const out=await serviceClient.rpc('ingest_external_locations',{p_source_key:'osm',p_rows:discovered.slice(i,i+100)});if(out.error)throw out.error;imported+=Number(out.data?.imported_locations||0);updated+=Number(out.data?.updated_locations||0)}}catch(e){ingest_error=e instanceof Error?e.message:String(e)}}return json({ok:true,cached:false,authenticated:Boolean(uid),discovered:discovered.length,imported,updated,ingest_error,radius_km:radius,locations:discovered})}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e),locations:[]},502)}});
