import { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { createKleenestSupabaseClient } from '@kleenest/mobile-core';

export default function NotificationsScreen(){
 const client=useMemo(()=>{try{return createKleenestSupabaseClient()}catch{return null}},[]); const [items,setItems]=useState<any[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const load=useCallback(async()=>{if(!client)return;setBusy(true);setMessage('');try{const {data,error}=await client.from('notifications').select('*').order('created_at',{ascending:false}).limit(50);if(error)throw error;setItems(data||[])}catch(e:any){setMessage(e?.message||'Notifications are temporarily unavailable.')}finally{setBusy(false)}},[client]);
 useEffect(()=>{void load()},[load]);
 const markAll=async()=>{if(!client)return;setBusy(true);try{const {error}=await client.rpc('mark_all_notifications_read');if(error)throw error;setItems(rows=>rows.map(row=>({...row,read_at:row.read_at||new Date().toISOString()})));setMessage('All notifications marked as read.')}catch(e:any){setMessage(e?.message||'Unable to mark notifications read.')}finally{setBusy(false)}};
 return <ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()}/>} contentContainerStyle={styles.page}><Text style={styles.eyebrow}>NOTIFICATIONS</Text><Text style={styles.title}>What needs your attention.</Text><Text style={styles.subtitle}>Arrivals, rewards, QR check-ins, reviews, contests and community activity belong here.</Text><Pressable style={styles.primary} disabled={busy||!items.some(n=>!n.read_at)} onPress={()=>void markAll()}><Text style={styles.primaryText}>Mark all read</Text></Pressable>{!!message&&<Text style={styles.message}>{message}</Text>}{items.length?items.map((n:any)=><View style={[styles.card,!n.read_at&&styles.unread]} key={n.id}><Text style={styles.cardTitle}>{n.title||n.type||'Kleenest update'}</Text><Text>{n.body||n.message||'New activity is available.'}</Text>{n.read_at?<Text style={styles.meta}>Read</Text>:<Text style={styles.meta}>Unread</Text>}</View>):<View style={styles.empty}><Text style={styles.cardTitle}>You're caught up.</Text><Text>No new activity yet.</Text></View>}</ScrollView>}
const styles=StyleSheet.create({page:{padding:22,gap:14,backgroundColor:'#fff',flexGrow:1},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2},title:{fontSize:30,fontWeight:'800'},subtitle:{fontSize:15,lineHeight:22,color:'#5b6470'},primary:{padding:14,borderRadius:12,backgroundColor:'#111827',alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800'},card:{padding:16,borderWidth:1,borderColor:'#e5e7eb',borderRadius:14,gap:6},unread:{borderColor:'#111827'},cardTitle:{fontSize:16,fontWeight:'800'},meta:{fontSize:12,fontWeight:'700',color:'#6b7280'},empty:{padding:24,backgroundColor:'#f3f4f6',borderRadius:14,gap:6},message:{color:'#b45309'}});
