import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { createKleenestSupabaseClient, createMobileIdentityService } from '@kleenest/mobile-core';

export default function ProfileScreen(){
 const client=useMemo(()=>{try{return createKleenestSupabaseClient()}catch{return null}},[]);
 const identity=useMemo(()=>client?createMobileIdentityService(client):null,[client]);
 const [user,setUser]=useState<any>(null); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const load=useCallback(async()=>{if(!identity)return;try{setUser(await identity.getCurrentUser())}catch(e:any){setMessage(e?.message||'Unable to load account.')}},[identity]);
 useEffect(()=>{void load();},[load]);
 const signIn=async()=>{if(!identity||!email.trim()||!password)return;setBusy(true);setMessage('');try{const {data,error}=await identity.signIn({email:email.trim(),password});if(error)throw error;setUser(data.user);setPassword('');setMessage('Signed in successfully.')}catch(e:any){setMessage(e?.message||'Sign in failed.')}finally{setBusy(false)}};
 const signUp=async()=>{if(!identity||!email.trim()||password.length<8)return setMessage('Use an email and a password of at least 8 characters.');setBusy(true);setMessage('');try{const {data,error}=await identity.signUp({email:email.trim(),password,fullName:name.trim()});if(error)throw error;setUser(data.user);setPassword('');setMessage(data.session?'Account created and signed in.':'Account created. Check your email if confirmation is required.')}catch(e:any){setMessage(e?.message||'Account creation failed.')}finally{setBusy(false)}};
 const reset=async()=>{if(!identity||!email.trim())return setMessage('Enter your email first.');setBusy(true);try{const {error}=await identity.sendPasswordReset(email.trim());if(error)throw error;setMessage('Password reset instructions sent.')}catch(e:any){setMessage(e?.message||'Unable to send reset instructions.')}finally{setBusy(false)}};
 const signOut=async()=>{if(!identity)return;setBusy(true);try{const {error}=await identity.signOut();if(error)throw error;setUser(null);setMessage('Signed out.')}catch(e:any){setMessage(e?.message||'Unable to sign out.')}finally{setBusy(false)}};
 return <ScrollView contentContainerStyle={styles.page}><Text style={styles.eyebrow}>PROFILE</Text><Text style={styles.title}>Your Kleenest.</Text><Text style={styles.subtitle}>Identity, visits, rewards, family access and account controls stay connected to your authenticated account.</Text>{user?<View style={styles.panel}><Text style={styles.panelTitle}>Signed in</Text><Text>{user.email}</Text><Pressable style={styles.secondary} disabled={busy} onPress={()=>void signOut()}><Text style={styles.secondaryText}>{busy?'Working…':'Sign out'}</Text></Pressable></View>:<View style={styles.panel}><Text style={styles.panelTitle}>Sign in or create your account</Text><TextInput value={name} onChangeText={setName} placeholder="Full name (for new accounts)" style={styles.input}/><TextInput value={email} onChangeText={setEmail} placeholder="Email" autoCapitalize="none" keyboardType="email-address" style={styles.input}/><TextInput value={password} onChangeText={setPassword} placeholder="Password" secureTextEntry style={styles.input}/><View style={styles.row}><Pressable style={styles.primary} disabled={busy} onPress={()=>void signIn()}><Text style={styles.primaryText}>Sign in</Text></Pressable><Pressable style={styles.secondary} disabled={busy} onPress={()=>void signUp()}><Text style={styles.secondaryText}>Create account</Text></Pressable></View><Pressable disabled={busy} onPress={()=>void reset()}><Text style={styles.link}>Forgot password?</Text></Pressable></View>}{!!message&&<Text style={styles.message}>{message}</Text>}<Link href="/checkin" asChild><Pressable style={styles.card}><Text style={styles.cardTitle}>Check in</Text><Text>Verify a visit with GPS or QR.</Text></Pressable></Link><Link href="/qr" asChild><Pressable style={styles.card}><Text style={styles.cardTitle}>QR engagement</Text><Text>Redeem a Kleenest QR.</Text></Pressable></Link><Link href="/rewards" asChild><Pressable style={styles.card}><Text style={styles.cardTitle}>Rewards</Text><Text>See server-authoritative progression.</Text></Pressable></Link><Link href="/notifications" asChild><Pressable style={styles.card}><Text style={styles.cardTitle}>Notifications</Text><Text>Alerts, rewards, QR activity and community updates.</Text></Pressable></Link><Link href="/family" asChild><Pressable style={styles.card}><Text style={styles.cardTitle}>Family</Text><Text>Coordinate premium access with your household.</Text></Pressable></Link><Link href="/premium" asChild><Pressable style={styles.card}><Text style={styles.cardTitle}>Premium · $5 one time</Text><Text>Remove advertising with no recurring charge.</Text></Pressable></Link></ScrollView>}
const styles=StyleSheet.create({page:{padding:22,gap:14,backgroundColor:'#fff',flexGrow:1},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2},title:{fontSize:30,fontWeight:'800'},subtitle:{fontSize:15,lineHeight:22,color:'#5b6470'},panel:{padding:18,borderRadius:16,borderWidth:1,borderColor:'#e5e7eb',gap:10},panelTitle:{fontSize:18,fontWeight:'800'},input:{borderWidth:1,borderColor:'#d1d5db',borderRadius:12,padding:13,fontSize:16},row:{flexDirection:'row',gap:10},primary:{flex:1,backgroundColor:'#111827',padding:14,borderRadius:12,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800'},secondary:{flex:1,padding:14,borderRadius:12,borderWidth:1,borderColor:'#111827',alignItems:'center'},secondaryText:{fontWeight:'800'},card:{padding:16,borderRadius:14,borderWidth:1,borderColor:'#e5e7eb',gap:5},cardTitle:{fontSize:17,fontWeight:'800'},link:{fontWeight:'800'},message:{padding:12,borderRadius:12,backgroundColor:'#f3f4f6',color:'#374151'}});
