import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { createKleenestSupabaseClient, createMobileEngagementService } from '@kleenest/mobile-core';

export default function QrScreen() {
  const [code,setCode]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const redeem=async()=>{if(!code.trim())return setError('Enter a Kleenest QR code.');setBusy(true);setError('');setMessage('');try{const data=await createMobileEngagementService(createKleenestSupabaseClient()).redeemQr(code.trim());setMessage('QR redeemed successfully. Kleenest recorded the engagement and can now apply the eligible downstream progression.');setCode('');return data;}catch(e:any){setError(e?.message||'Unable to redeem this QR code.');}finally{setBusy(false);}};
  return <View style={styles.page}><Text style={styles.eyebrow}>QR ENGAGEMENT</Text><Text style={styles.title}>Redeem a Kleenest QR</Text><Text style={styles.body}>Business QR programs remain server-authoritative. The consumer app submits the code; Supabase decides whether it is valid, single-use, authorized and redeemable.</Text><TextInput value={code} onChangeText={setCode} placeholder="Enter or paste QR code" autoCapitalize="none" style={styles.input}/><Pressable disabled={busy||!code.trim()} style={styles.primary} onPress={redeem}><Text style={styles.primaryText}>{busy?'Redeeming…':'Redeem QR'}</Text></Pressable>{!!message&&<Text style={styles.success}>{message}</Text>}{!!error&&<Text style={styles.error}>{error}</Text>}</View>;
}
const styles=StyleSheet.create({page:{flex:1,padding:24,gap:16,backgroundColor:'#fff'},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,marginTop:18},title:{fontSize:32,fontWeight:'800'},body:{fontSize:15,lineHeight:22,color:'#5b6470'},input:{borderWidth:1,borderColor:'#d1d5db',borderRadius:12,padding:15,fontSize:16},primary:{padding:16,borderRadius:14,backgroundColor:'#111827',alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800'},success:{padding:14,borderRadius:12,backgroundColor:'#ecfdf5',color:'#065f46'},error:{padding:14,borderRadius:12,backgroundColor:'#fef2f2',color:'#991b1b'}});
