import { useEffect, useMemo, useState } from 'react';
import { useLocalSearchParams, Link } from 'expo-router';
import * as Location from 'expo-location';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { createKleenestSupabaseClient, createMobileRoutingService, type MobileRoute } from '@kleenest/mobile-core';

export default function RouteScreen(){
 const {destination,locationId}=useLocalSearchParams<{destination?:string;locationId?:string}>();
 const client=useMemo(()=>{try{return createKleenestSupabaseClient()}catch{return null}},[]);
 const routing=useMemo(()=>client?createMobileRoutingService(client):null,[client]);
 const [destinationText,setDestinationText]=useState(destination||''); const [coords,setCoords]=useState<[number,number]|null>(null); const [target,setTarget]=useState<[number,number]|null>(null); const [route,setRoute]=useState<MobileRoute|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [phase,setPhase]=useState<'ready'|'started'|'approaching'|'arrived'|'departed'>('ready');
 useEffect(()=>{void locate();},[]);
 const locate=async()=>{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted'){setMessage('Location permission is required to build a route.');return;}const current=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setCoords([current.coords.longitude,current.coords.latitude]);};
 const loadTarget=async()=>{if(!client||!locationId)return;const {data,error}=await client.from('locations').select('latitude,longitude').eq('id',locationId).maybeSingle();if(error)throw error;if(data?.latitude!=null&&data?.longitude!=null)setTarget([Number(data.longitude),Number(data.latitude)]);};
 useEffect(()=>{void loadTarget().catch(e=>setMessage(e.message));},[client,locationId]);
 const build=async()=>{if(!routing)return setMessage('Mobile configuration is missing.');if(!coords)return setMessage('Use my location first.');if(!target)return setMessage('The selected restroom has no usable coordinates.');setBusy(true);setMessage('Building a live route…');try{const result=await routing.request({origin:coords,destination:target,locationId:locationId||null});setRoute(result);setPhase('ready');setMessage(`Route ready · ${result.distanceKm} km · ${result.durationMinutes} min`);}catch(e:any){setMessage(e?.message||'Route could not be built.');}finally{setBusy(false);}};
 const lifecycle=async(next:'user_route_started'|'user_approaching_location'|'user_arrived'|'user_departed',label:string)=>{if(!routing||!route)return;setBusy(true);try{await routing.publishLifecycle(next,route);setPhase(next==='user_route_started'?'started':next==='user_approaching_location'?'approaching':next==='user_arrived'?'arrived':'departed');setMessage(label);}catch(e:any){setMessage(e?.message||'That route action could not be recorded.');}finally{setBusy(false);}};
 return <ScrollView contentContainerStyle={styles.page}>
  <Text style={styles.eyebrow}>SMART ROUTES</Text><Text style={styles.title}>Plan the trip, not just the destination.</Text>
  <Text style={styles.subtitle}>Every route action is recorded against the canonical location when you're signed in.</Text>
  <View style={styles.panel}><Text style={styles.label}>Destination</Text><TextInput value={destinationText} onChangeText={setDestinationText} placeholder="Your destination" style={styles.input}/><Text style={styles.label}>Selected restroom</Text><Text style={styles.value}>{locationId||'None yet'}</Text></View>
  <View style={styles.row}><Pressable style={styles.secondary} onPress={locate}><Text style={styles.buttonText}>{coords?'Location ready':'Use my location'}</Text></Pressable><Pressable style={styles.primary} onPress={build} disabled={busy}>{busy?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>Build route</Text>}</Pressable></View>
  {!!message&&<Text style={styles.message}>{message}</Text>}
  {route&&<><View style={styles.panel}><Text style={styles.panelTitle}>Live route</Text><Text>{route.distanceKm} km · about {route.durationMinutes} min</Text><Text>{route.steps.length} navigation steps · {route.routingProvider}</Text></View><View style={styles.row}><Pressable style={styles.primary} disabled={busy} onPress={()=>lifecycle('user_route_started','Route started.')}><Text style={styles.primaryText}>Start route</Text></Pressable><Pressable style={styles.secondary} disabled={busy} onPress={()=>lifecycle('user_approaching_location','Approaching location recorded.')}><Text style={styles.buttonText}>Approaching</Text></Pressable></View><View style={styles.row}><Pressable style={styles.secondary} disabled={busy} onPress={()=>lifecycle('user_arrived','Arrival recorded.')}><Text style={styles.buttonText}>Arrived</Text></Pressable><Pressable style={styles.secondary} disabled={busy} onPress={()=>lifecycle('user_departed','Departure recorded.')}><Text style={styles.buttonText}>Departed</Text></Pressable></View><Text style={styles.status}>Status: {phase}</Text></>}
  <Link href="/map" style={styles.link}>← Add another restroom from the map</Link>
 </ScrollView>;
}
const styles=StyleSheet.create({page:{padding:22,gap:16,backgroundColor:'#fff',flexGrow:1},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2},title:{fontSize:30,fontWeight:'800'},subtitle:{fontSize:15,lineHeight:22,color:'#5b6470'},panel:{padding:18,borderRadius:16,borderWidth:1,borderColor:'#e5e7eb',gap:10},label:{fontSize:12,fontWeight:'800',textTransform:'uppercase'},value:{fontSize:17},input:{borderWidth:1,borderColor:'#d1d5db',borderRadius:12,padding:13,fontSize:16},row:{flexDirection:'row',gap:10},primary:{flex:1,backgroundColor:'#111827',padding:15,borderRadius:12,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800'},secondary:{flex:1,borderWidth:1,borderColor:'#d1d5db',padding:15,borderRadius:12,alignItems:'center'},buttonText:{fontWeight:'800'},panelTitle:{fontSize:18,fontWeight:'800'},message:{color:'#4b5563'},status:{fontWeight:'800'},link:{fontWeight:'800'}});
