import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const URL=Deno.env.get('SUPABASE_URL')!, SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const DATA_GOV_KEY=Deno.env.get('DATA_GOV_API_KEY')||'DEMO_KEY';
const db=createClient(URL,SERVICE,{auth:{persistSession:false}});
const OSM_ENDPOINTS=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.private.coffee/api/interpreter'];
const H={'content-type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-kleenest-scheduler'};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const now=()=>new Date().toISOString();
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));

async function guard(req:Request){const supplied=req.headers.get('x-kleenest-scheduler')||'';if(!supplied)throw Error('Scheduler authentication required');const {data,error}=await db.rpc('get_internal_scheduler_secret',{p_name:'kleenest_maps_scheduler'});if(error||!data||supplied!==data)throw Error('Invalid scheduler authentication');}
async function one(table:string,query:(q:any)=>any){const {data,error}=await query(db.from(table));if(error)throw error;return data;}
async function usage(source:string){const day=new Date();day.setUTCHours(0,0,0,0);const {data,error}=await db.from('national_ingestion_runs').select('requests_used,bytes_downloaded').eq('source_key',source).gte('started_at',day.toISOString());if(error)throw error;const rows=data||[];return{dailyRequests:rows.reduce((n:any,r:any)=>n+Number(r.requests_used||0),0),dailyBytes:rows.reduce((n:any,r:any)=>n+Number(r.bytes_downloaded||0),0)};}
async function hourlyUsage(source:string){const {data,error}=await db.from('national_ingestion_runs').select('requests_used').eq('source_key',source).gte('started_at',new Date(Date.now()-60*60_000).toISOString());if(error)throw error;return(data||[]).reduce((n:any,r:any)=>n+Number(r.requests_used||0),0);}
async function policy(source:string){const {data,error}=await db.from('national_ingestion_source_policies').select('*').eq('source_key',source).single();if(error)throw error;return data;}
function progress(m:any,key:string){const p=m.source_progress&&typeof m.source_progress==='object'?m.source_progress:{};return p[key]&&typeof p[key]==='object'?p[key]:{};}
async function patchMarket(id:string,patch:any){const {error}=await db.from('national_ingestion_markets').update({...patch,updated_at:now(),last_run_at:now()}).eq('id',id);if(error)throw error;}
async function recordRun(run:any){const {data,error}=await db.from('national_ingestion_runs').insert(run).select('id').single();if(error)throw error;return data.id;}
async function finishRun(id:string,patch:any){const {error}=await db.from('national_ingestion_runs').update({...patch,finished_at:now()}).eq('id',id);if(error)throw error;}

async function claimMarket(){let {data,error}=await db.from('national_ingestion_markets').select('*').eq('status','running').order('priority').limit(1).maybeSingle();if(error)throw error;if(data)return data;({data,error}=await db.from('national_ingestion_markets').select('*').eq('status','pending').order('priority').limit(1).maybeSingle());if(error)throw error;if(!data)return null;await patchMarket(data.id,{status:'running',started_at:data.started_at||now(),attempt_count:Number(data.attempt_count||0)+1});return{...data,status:'running'};}

async function resolveBbox(m:any){if(Array.isArray(m.bbox)&&m.bbox.length===4)return m.bbox.map(Number);const q=encodeURIComponent(`${m.name}, ${m.state_code||''}, United States`);const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=us&q=${q}`,{headers:{'user-agent':'KleenestApp/1.0 (national ingestion market resolver)'}});if(!r.ok)throw Error(`Market boundary lookup HTTP ${r.status}`);const a=await r.json();const b=a?.[0]?.boundingbox;if(!Array.isArray(b)||b.length<4)throw Error('Market boundary lookup returned no bbox');const bbox=[Number(b[0]),Number(b[2]),Number(b[1]),Number(b[3])];if(bbox.some((x:number)=>!Number.isFinite(x)))throw Error('Market boundary lookup returned invalid bbox');await patchMarket(m.id,{bbox});await sleep(1100);return bbox;}
function tiles(b:number[],kind:string){const[s,w,n,e]=b;const step=kind==='city'?0.10:0.18;const out:number[][]=[];for(let lat=s;lat<n;lat+=step)for(let lon=w;lon<e;lon+=step)out.push([lat,lon,Math.min(lat+step,n),Math.min(lon+step,e)]);return out;}
function osmQuery(b:number[]){const[s,w,n,e]=b;return`[out:json][timeout:30];(nwr[amenity~"restaurant|fast_food|cafe|fuel|toilets|hospital|clinic|doctors|dentist|pharmacy|library|bus_station|townhall|courthouse|police|fire_station|drinking_water|shower|charging_station|atm"](${s},${w},${n},${e});nwr[building="toilets"](${s},${w},${n},${e});nwr[toilets="yes"](${s},${w},${n},${e});nwr["toilets:access"="public"](${s},${w},${n},${e});nwr[shop](${s},${w},${n},${e});nwr[leisure~"park|nature_reserve|playground|sports_centre"](${s},${w},${n},${e});nwr[railway="station"](${s},${w},${n},${e});nwr[tourism](${s},${w},${n},${e});nwr[changing_table="yes"](${s},${w},${n},${e});nwr[wheelchair="yes"](${s},${w},${n},${e}););out center tags;`}
function category(t:any){if(t.amenity==='toilets'||t.building==='toilets'||t.toilets==='yes'||t['toilets:access']==='public')return'restroom';if(t.amenity==='fuel')return'gas_station';if(['restaurant','fast_food'].includes(t.amenity))return'restaurant';if(t.amenity==='cafe')return'cafe';if(['hospital','clinic','doctors','dentist','pharmacy'].includes(t.amenity))return'health';if(t.leisure)return'park';if(t.shop)return'shopping';return'service';}
function osmRows(es:any[],market:any){const captured=now();return es.map(e=>{const t=e.tags||{},lat=Number(e.lat??e.center?.lat),lng=Number(e.lon??e.center?.lon);if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;const id=`osm:${e.type}:${e.id}`,pt=category(t);return{source_id:id,latitude:lat,longitude:lng,name:t.name||t.brand||t.operator||(pt==='restroom'?'Public Restroom':`Unnamed ${pt}`),place_type:pt,address:[t['addr:housenumber'],t['addr:street']].filter(Boolean).join(' ')||t['addr:full']||null,city:t['addr:city']||market.name,state:t['addr:state']||market.state_code,postal_code:t['addr:postcode']||null,phone:t.phone||t['contact:phone']||null,website:t.website||t['contact:website']||null,brand:t.brand||null,operator_name:t.operator||null,source_metadata:{tags:t,provider:'overpass',source_dataset:'openstreetmap_live',captured_at:captured,market_key:market.market_key}}}).filter(Boolean);}
async function persist(source:string,rows:any[]){let imported=0,updated=0;for(let i=0;i<rows.length;i+=500){const {data,error}=await db.rpc('ingest_external_locations',{p_source_key:source,p_rows:rows.slice(i,i+500)});if(error)throw error;imported+=Number(data?.imported_locations||0);updated+=Number(data?.updated_locations||0);}return{imported,updated};}
async function runOsm(m:any,bbox:number[]){const p=await policy('osm'),u=await usage('osm'),hu=await hourlyUsage('osm');if((p.daily_request_limit&&u.dailyRequests>=p.daily_request_limit)||(p.hourly_request_limit&&hu>=p.hourly_request_limit)||(p.daily_byte_limit&&u.dailyBytes>=p.daily_byte_limit))return{skipped:true,reason:'quota'};const all=tiles(bbox,m.market_kind),st=progress(m,'osm'),cursor=Math.max(0,Number(st.tile_cursor||0));if(cursor>=all.length)return{completed:true,progress:{...st,completed:true,tile_cursor:all.length,tile_count:all.length}};const runId=await recordRun({market_id:m.id,source_key:'osm',status:'running',detail:{tile_cursor:cursor,tile_count:all.length,bbox:all[cursor]}});let requests=0,bytes=0;try{const ep=OSM_ENDPOINTS[cursor%OSM_ENDPOINTS.length],r=await fetch(ep,{method:'POST',headers:{'content-type':'text/plain','user-agent':'KleenestApp/1.0 national-ingestion'},body:osmQuery(all[cursor])});requests=1;const text=await r.text();bytes=new TextEncoder().encode(text).length;if(!r.ok)throw Error(`Overpass HTTP ${r.status}`);const body=JSON.parse(text),rows=osmRows(Array.isArray(body.elements)?body.elements:[],m),tot=await persist('osm',rows);const next=cursor+1,done=next>=all.length,newState={...st,tile_cursor:next,tile_count:all.length,completed:done,records_seen:Number(st.records_seen||0)+rows.length,records_imported:Number(st.records_imported||0)+tot.imported,records_updated:Number(st.records_updated||0)+tot.updated};await finishRun(runId,{status:'completed',requests_used:requests,bytes_downloaded:bytes,records_seen:rows.length,records_imported:tot.imported,records_updated:tot.updated,detail:{tile_cursor:cursor,tile_count:all.length,endpoint:ep}});return{completed:done,progress:newState,rows:rows.length,...tot};}catch(e){await finishRun(runId,{status:'failed',requests_used:requests,bytes_downloaded:bytes,error:e instanceof Error?e.message:String(e)});throw e;}}

function dataGovTerms(m:any){const place=m.market_kind==='state_fill'?m.name:`${m.name} ${m.state_code||''}`;return[`${place} public restrooms`,`${place} public facilities`,`${place} parks`,`${place} restaurant inspections`,`${place} transit facilities`,`${place} accessibility facilities`];}
function distUrls(d:any){const arr=Array.isArray(d?.dcat?.distribution)?d.dcat.distribution:[];const urls:string[]=[];for(const x of arr){if(typeof x==='string')urls.push(x);else if(x&&typeof x==='object')for(const k of ['downloadURL','accessURL','url','URL'])if(x[k])urls.push(String(x[k]));}return[...new Set(urls)].filter(u=>/^https?:\/\//i.test(u));}
function point(x:any){const g=x.geometry||x.geo_shape||x.geolocation||x.location;if(g?.type==='Point'&&Array.isArray(g.coordinates))return{lat:Number(g.coordinates[1]),lon:Number(g.coordinates[0])};if(Array.isArray(g?.coordinates)){let c:any=g.coordinates;while(Array.isArray(c?.[0]))c=c[0];if(Array.isArray(c)&&c.length>=2)return{lat:Number(c[1]),lon:Number(c[0])};}return{lat:Number(x.latitude??x.lat??g?.latitude),lon:Number(x.longitude??x.lon??x.lng??g?.longitude)};}
function dataRows(raw:any[],dataset:any,m:any,b:number[]){return raw.map((x:any,i:number)=>{const p=point(x);if(!Number.isFinite(p.lat)||!Number.isFinite(p.lon)||p.lat<b[0]||p.lat>b[2]||p.lon<b[1]||p.lon>b[3])return null;const text=JSON.stringify(x).toLowerCase();const pt=/restroom|bathroom|toilet|lavatory/.test(text)?'restroom':/restaurant|food establishment|eatery|food service/.test(text)?'restaurant':/park|recreation|greenway/.test(text)?'park':/cafe|coffee/.test(text)?'cafe':'service';return{source_id:`datagov:${dataset.identifier||dataset.slug||'dataset'}:${x.id||x.objectid||x.OBJECTID||i}`,latitude:p.lat,longitude:p.lon,name:x.name||x.facility_name||x.site_name||x.business_name||x.location_name||`${dataset.title} ${i+1}`,place_type:pt,address:x.address||x.street_address||x.location_address||null,city:x.city||m.name,state:x.state||m.state_code,postal_code:String(x.zip||x.zipcode||x.postal_code||'')||null,phone:x.phone||x.telephone||null,website:x.website||x.url||null,source_metadata:{provider:'data.gov',catalog_dataset_id:dataset.identifier||null,dataset:dataset.title,publisher:dataset.publisher||dataset.organization?.name||null,record:x,captured_at:now(),market_key:m.market_key}}}).filter(Boolean);}
async function loadResource(url:string){const r=await fetch(url,{headers:{accept:'application/json,application/geo+json,text/csv,*/*','user-agent':'KleenestApp/1.0 national-ingestion'}});if(!r.ok)return[];const ct=r.headers.get('content-type')||'';if(ct.includes('json')||/\.json($|\?)/i.test(url)){const j=await r.json();if(Array.isArray(j))return j;if(Array.isArray(j.features))return j.features.map((f:any)=>({...f.properties,geometry:f.geometry}));return j.result?.records||j.records||j.data||[];}if(ct.includes('csv')||/\.csv($|\?)/i.test(url)){const lines=(await r.text()).split(/\r?\n/).filter(Boolean).slice(0,5001);if(lines.length<2)return[];const parse=(s:string)=>s.split(/,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)/).map(v=>v.trim().replace(/^\"|\"$/g,''));const h=parse(lines[0]);return lines.slice(1).map(l=>{const v=parse(l);return Object.fromEntries(h.map((k,i)=>[k,v[i]??'']))});}return[];}
async function catalogDataset(d:any,m:any){const src=await one('external_data_sources',(q:any)=>q.select('id').eq('source_key','data_gov').single());if(!src?.id)return;await db.from('external_data_datasets').upsert({source_id:src.id,external_dataset_id:String(d.identifier||d.slug||d.title),title:d.title||'Untitled dataset',publisher:d.publisher||d.organization?.name||null,description:d.description||d.dcat?.description||null,landing_url:d.dcat?.landingPage||null,license_url:d.dcat?.license||null,access_level:d.dcat?.accessLevel||'public',format:'mixed',spatial:Boolean(d.has_spatial),geography:m.name,keywords:Array.isArray(d.keyword)?d.keyword:[],schema_hint:{market_key:m.market_key,organization:d.organization||null,distribution_titles:d.distribution_titles||[]},import_policy:'automatic_market_ingestion',status:'active',last_cataloged_at:now(),updated_at:now()},{onConflict:'source_id,external_dataset_id'});}
async function runDataGov(m:any,bbox:number[]){const p=await policy('data_gov'),u=await usage('data_gov'),hu=await hourlyUsage('data_gov'),personal=DATA_GOV_KEY!=='DEMO_KEY',dailyLimit=personal?null:p.daily_request_limit,hourlyLimit=personal?1000:p.hourly_request_limit;if((dailyLimit&&u.dailyRequests>=dailyLimit)||(hourlyLimit&&hu>=hourlyLimit))return{skipped:true,reason:'quota'};const terms=dataGovTerms(m),st=progress(m,'data_gov'),cursor=Math.max(0,Number(st.query_cursor||0));if(cursor>=terms.length)return{completed:true,progress:{...st,completed:true,query_cursor:terms.length,query_count:terms.length}};const allowance=Math.min(Number(p.max_requests_per_cycle||1),terms.length-cursor,personal?10:Math.max(1,50-u.dailyRequests));const runId=await recordRun({market_id:m.id,source_key:'data_gov',status:'running',detail:{query_cursor:cursor,query_count:terms.length,key_mode:personal?'personal':'demo'}});let requests=0,seen=0,imported=0,updated=0,datasets=0;try{let next=cursor;for(let i=0;i<allowance;i++){const term=terms[next],geom=JSON.stringify({type:'Polygon',coordinates:[[[bbox[1],bbox[0]],[bbox[3],bbox[0]],[bbox[3],bbox[2]],[bbox[1],bbox[2]],[bbox[1],bbox[0]]]]}),r=await fetch(`https://api.gsa.gov/technology/datagov/v4/search?q=${encodeURIComponent(term)}&sort=popularity&per_page=25&spatial_filter=geospatial&spatial_geometry=${encodeURIComponent(geom)}`,{headers:{'X-Api-Key':DATA_GOV_KEY,'user-agent':'KleenestApp/1.0 national-ingestion'}});requests++;if(r.status===429)break;if(!r.ok)throw Error(`Data.gov HTTP ${r.status}`);const body=await r.json(),results=Array.isArray(body.results)?body.results:[];for(const d of results.slice(0,15)){await catalogDataset(d,m);datasets++;for(const url of distUrls(d).slice(0,2)){try{const raw=await loadResource(url);if(!Array.isArray(raw)||!raw.length)continue;const rows=dataRows(raw.slice(0,5000),d,m,bbox);seen+=rows.length;if(rows.length){const tot=await persist('data_gov',rows);imported+=tot.imported;updated+=tot.updated;break;}}catch{}}}next++;if(next>=terms.length)break;await sleep(2100);}const done=next>=terms.length,newState={...st,query_cursor:next,query_count:terms.length,completed:done,datasets_cataloged:Number(st.datasets_cataloged||0)+datasets,records_seen:Number(st.records_seen||0)+seen,records_imported:Number(st.records_imported||0)+imported,records_updated:Number(st.records_updated||0)+updated};await finishRun(runId,{status:'completed',requests_used:requests,records_seen:seen,records_imported:imported,records_updated:updated,detail:{query_cursor:cursor,next_query_cursor:next,query_count:terms.length,key_mode:personal?'personal':'demo',datasets_cataloged:datasets}});return{completed:done,progress:newState,requests,datasets,seen,imported,updated};}catch(e){await finishRun(runId,{status:'failed',requests_used:requests,records_seen:seen,records_imported:imported,records_updated:updated,error:e instanceof Error?e.message:String(e)});throw e;}}

async function cycle(){const m=await claimMarket();if(!m)return{ok:true,status:'complete',message:'National ingestion queue is complete.'};let bbox:number[];try{bbox=await resolveBbox(m);}catch(e){await patchMarket(m.id,{status:'blocked',last_error:e instanceof Error?e.message:String(e)});return{ok:false,status:'blocked',market:m.market_key,error:e instanceof Error?e.message:String(e)}}const sp={...(m.source_progress||{})};try{let worked=false;const osm=progress({...m,source_progress:sp},'osm');if(!osm.completed){const r=await runOsm({...m,source_progress:sp},bbox);if(r.progress)sp.osm=r.progress;if(!r.skipped)worked=true;}const dg=progress({...m,source_progress:sp},'data_gov');if(!dg.completed){const r=await runDataGov({...m,source_progress:sp},bbox);if(r.progress)sp.data_gov=r.progress;if(!r.skipped)worked=true;}const done=Boolean(sp.osm?.completed)&&Boolean(sp.data_gov?.completed);await patchMarket(m.id,{source_progress:sp,status:done?'completed':'running',completed_at:done?now():null,last_error:null,current_source:done?null:(!sp.osm?.completed?'osm':'data_gov')});return{ok:true,status:done?'market_completed':worked?'progressed':'quota_wait',market:{key:m.market_key,name:m.name,kind:m.market_kind},source_progress:sp};}catch(e){await patchMarket(m.id,{status:'running',source_progress:sp,last_error:e instanceof Error?e.message:String(e)});return{ok:false,status:'retryable_error',market:m.market_key,error:e instanceof Error?e.message:String(e),source_progress:sp};}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:H});if(req.method!=='POST')return json({ok:false,error:'POST required'},405);try{await guard(req);const body=await req.json().catch(()=>({}));if(String(body.action||'cycle')!=='cycle')return json({ok:false,error:'Unsupported action'},400);return json(await cycle());}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500);}});
