import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import Stripe from "npm:stripe@18.5.0";
import { createClient } from "npm:@supabase/supabase-js@2.57.0";
const stripe=new Stripe(Deno.env.get('STRIPE_SECRET_KEY')||'',{apiVersion:'2025-07-30.basil'});
const supabaseAdmin=createClient(Deno.env.get('SUPABASE_URL')||'',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'');
const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const appBase='https://matthagersenior.github.io/Kleenest_Architecture/';
const defaultCancel=`${appBase}#/pricing?checkout=cancelled`;
const planSuccess=(planCode:string)=>`${appBase}#/pricing?checkout=success&plan=${encodeURIComponent(planCode)}&session_id={CHECKOUT_SESSION_ID}`;
const tierRank:Record<string,number>={free:0,premium:1,family:2,fleet:3,enterprise:4};
const oneTimeTier:Record<string,string>={premium_user:'premium',premium:'premium',family:'family'};
async function customerFor(user:{id:string,email?:string|null}){const existing=await supabaseAdmin.from('stripe_billing_customers').select('stripe_customer_id').eq('user_id',user.id).maybeSingle();if(existing.error)throw existing.error;if(existing.data?.stripe_customer_id)return existing.data.stripe_customer_id;const customer=await stripe.customers.create({email:user.email||undefined,metadata:{kleenest_user_id:user.id}});const inserted=await supabaseAdmin.from('stripe_billing_customers').insert({user_id:user.id,stripe_customer_id:customer.id});if(inserted.error)throw inserted.error;return customer.id;}
async function assertOneTimeUpgrade(userId:string,planCode:string){const target=oneTimeTier[planCode];if(!target)throw new Error('This one-time plan is not a consumer membership purchase');const {data:profile,error}=await supabaseAdmin.from('profiles').select('subscription_tier').eq('id',userId).maybeSingle();if(error)throw error;const current=String(profile?.subscription_tier||'free');if((tierRank[current]??0)>=(tierRank[target]??0))throw new Error('Membership already includes this purchase');}
async function assertNoActiveSubscription(userId:string,planCode:string){const {data,error}=await supabaseAdmin.from('subscriptions').select('id').eq('user_id',userId).eq('plan_code',planCode).in('status',['active','trialing','past_due']).limit(1);if(error)throw error;if(data?.length)throw new Error('This subscription is already active');}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers});try{const auth=req.headers.get('Authorization');if(!auth)return new Response(JSON.stringify({error:'Unauthorized'}),{status:401,headers});const token=auth.replace(/^Bearer\s+/i,'');const {data:{user},error:authError}=await supabaseAdmin.auth.getUser(token);if(authError||!user)return new Response(JSON.stringify({error:'Unauthorized'}),{status:401,headers});const {planCode,accessOfferId,successUrl,cancelUrl}=await req.json();if(Boolean(planCode)===Boolean(accessOfferId))throw new Error('Provide exactly one checkout target');const customerId=await customerFor(user);
if(accessOfferId){const {data:offer,error:offerError}=await supabaseAdmin.from('single_use_access_offers').select('id,name,description,price_cents,enabled,expires_at').eq('id',accessOfferId).eq('enabled',true).maybeSingle();if(offerError||!offer)throw new Error('Offer is unavailable');if(offer.expires_at&&new Date(offer.expires_at).getTime()<=Date.now())throw new Error('Offer is unavailable');if(!offer.price_cents||offer.price_cents<=0)throw new Error('This offer does not require paid checkout');const existing=await supabaseAdmin.from('single_use_access_purchases').select('id').eq('offer_id',offer.id).eq('user_id',user.id).eq('status','purchased').maybeSingle();if(existing.error)throw existing.error;if(existing.data?.id)throw new Error('Offer already purchased');const session=await stripe.checkout.sessions.create({mode:'payment',customer:customerId,line_items:[{price_data:{currency:'usd',unit_amount:offer.price_cents,product_data:{name:offer.name,description:offer.description||undefined}},quantity:1}],success_url:successUrl||`${appBase}#/access?checkout=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:cancelUrl||`${appBase}#/access?checkout=cancelled`,client_reference_id:user.id,metadata:{kleenest_user_id:user.id,kleenest_purchase_type:'single_use_access',kleenest_offer_id:offer.id},payment_intent_data:{metadata:{kleenest_user_id:user.id,kleenest_purchase_type:'single_use_access',kleenest_offer_id:offer.id}}});return new Response(JSON.stringify({url:session.url,sessionId:session.id,type:'single_use_access'}),{headers});}
const requested=String(planCode||'').toLowerCase();const {data:plan,error:planError}=await supabaseAdmin.from('pricing_catalog').select('code,name,category,price_cents,interval,price_note,active').eq('code',requested).eq('active',true).maybeSingle();if(planError||!plan)throw new Error('Plan is unavailable');if(!plan.price_cents||plan.price_cents<=0)throw new Error('This plan is not configured for self-serve checkout');if(!['once','month'].includes(String(plan.interval)))throw new Error('This plan is not configured for self-serve checkout');const metadata={kleenest_user_id:user.id,kleenest_plan_code:plan.code,kleenest_purchase_type:plan.interval==='once'?'membership_one_time':'subscription'};const redirectSuccess=successUrl||planSuccess(plan.code);
if(plan.interval==='once'){await assertOneTimeUpgrade(user.id,plan.code);const session=await stripe.checkout.sessions.create({mode:'payment',customer:customerId,line_items:[{price_data:{currency:'usd',unit_amount:plan.price_cents,product_data:{name:plan.name,description:plan.price_note||undefined}},quantity:1}],success_url:redirectSuccess,cancel_url:cancelUrl||defaultCancel,client_reference_id:user.id,metadata,payment_intent_data:{metadata}});return new Response(JSON.stringify({url:session.url,sessionId:session.id,type:'membership_one_time'}),{headers});}
await assertNoActiveSubscription(user.id,plan.code);const session=await stripe.checkout.sessions.create({mode:'subscription',customer:customerId,line_items:[{price_data:{currency:'usd',unit_amount:plan.price_cents,recurring:{interval:'month'},product_data:{name:plan.name,description:plan.price_note||undefined}},quantity:1}],success_url:redirectSuccess,cancel_url:cancelUrl||defaultCancel,client_reference_id:user.id,metadata,subscription_data:{metadata}});return new Response(JSON.stringify({url:session.url,sessionId:session.id,type:'subscription'}),{headers});}catch(error){return new Response(JSON.stringify({error:error instanceof Error?error.message:'Unable to create checkout'}),{status:400,headers});}});
